### ISSUE TITLE
'Convert to manual ...' code action doesn't send the missing members code when snippetTextEdits are disabled

### ISSUE THREAD

**Issue by simrat39** [rust-lang/rust-analyzer#10171]
Pretty much the title.

Without snippet text edits enabled:

![image](https://user-images.githubusercontent.com/37233846/132269746-8d8d3b21-396f-4bd1-9ac7-56acac7164dd.png)

With:

![image](https://user-images.githubusercontent.com/37233846/132269793-6fcb284c-6bd6-4bba-a27c-c94f1c056a82.png)

References:
https://github.com/simrat39/rust-tools.nvim/issues/53
https://github.com/simrat39/rust-tools.nvim/issues/60

**Comment by DropDemBits** [comment]
On the match arm that handles when `snippetTextEdits` is unavailable, it ignores whether `impl_def_with_items` is `Some`, which is important since `impl_def_with_items` contains the `impl` with the correct missing members.
https://github.com/rust-lang/rust-analyzer/blob/ea7fdada6a0940b239ddbde2048a4d7dac1efe1e/crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs#L147-L155

The other match arms correctly deal with `impl_def_with_items` but only differ in that they add snippets. Ideally this match arm should be removed and the snippet capability handling moved inside of the other two match arms.

**Comment by Samarth1696** [comment]
I would like to take the issue.
