### ISSUE TITLE
Fill match arms replaces whole impl block with proc macro attribute

### ISSUE THREAD

**Issue by azerupi** [rust-lang/rust-analyzer#10573]
I have some code that I unfortunately can't share where the "fill match arms" replaces a whole impl block.

I think it is related to the fact that I use a proc-macro attribute:

```rust
#[payload]
impl Payload {
    #[write(address = 0, length = 1)]
    fn enable_front_led(&mut self, data: U8) -> Result<(), u8> {
        // ...
    }
    
    // ...

   fn test(&mut self) {
        match self.trigger_mode {
            
        }
    }
}
```

When I use the "fill match arms" action it replaces the whole impl block and I am left with this:

```rust
{
    TriggerMode::Off => todo!(),
    TriggerMode::Laser => todo!(),
    TriggerMode::LedPattern(_) => todo!(),
    TriggerMode::Torch => todo!(),
}
```

This might be a recent regression, I don't remember having any problems before 2 or 3 weeks ago.  I have been trying to reproduce this with a small self-contained example but haven't been able to yet. I'll see if I can find some example code that triggers this behavior so that I can share it.

In the meantime, if I can provide any more useful information let me know.

**Comment by lnicola** [comment]
> This might be a recent regression, I don't remember having any problems before 2 or 3 weeks ago.

That's when we enabled attribute proc macros. You can still disable them to work around this issue.

**Comment by Veykril** [comment]
The problem is that we find the match expression in the expanded code, we then want to map it back up to the text range of the original one so we edit it, but we fail in doing so for some reason. And currently if we fail this mapping we fall back to the entire macro invocation, which in this case is the impl with the attribute.

The part that tries to get the correct range is this here,
https://github.com/rust-analyzer/rust-analyzer/blob/5704de66c271b35ffa6f22aa0b3f8f3f50f7f561/crates/ide_assists/src/handlers/add_missing_match_arms.rs#L174
for starters this should be a `original_range_opt` call instead and in case of `None` we shouldn't emit the assist at all as we don't know what to replace.
Figuring out why we fail to map up here is somewhere in the call hierarchy of those functions.

**Comment by azerupi** [comment]
This problem seems to appear when using the syn and quote crate.

This works
```rust
#[proc_macro_attribute]
pub fn payload(_args: TokenStream, input: TokenStream) -> TokenStream {
    input
}
```

But this does not work
```rust
#[proc_macro_attribute]
pub fn payload(_args: TokenStream, input: TokenStream) -> TokenStream {
    let item = parse_macro_input!(input as Item);

    let output = quote! {
        #item
    };

    output.into()
}
```
