### ISSUE TITLE
Feature Request: Diagnostic to replace trailing `return <val>;` with just `<val>`

### ISSUE THREAD

**Issue by izik1** [rust-lang/rust-analyzer#10970]
Example:
```rs
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Id(pub i32);

pub fn path(next: &[Id], width: usize, u: Id, v: Id) -> Vec<Id> {
    let mut u = u;
    let mut path = vec![];
    while u != v {
        u = next[u.0 as usize * width + v.0 as usize];
        path.push(u);
    }
    return<|> path;
}
```
->
```rs
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Id(pub i32);

pub fn path(next: &[Id], width: usize, u: Id, v: Id) -> Vec<Id> {
    let mut u = u;
    let mut path = vec![];
    while u != v {
        u = next[u.0 as usize * width + v.0 as usize];
        path.push(u);
    }
    <|>path
}
```
(not actually too sure where to put the cursor)

If this _does_ get picked up at some point: edge-case warning: the trailing semi might not exist.

I'd honestly be interested in doing this myself

**Comment by Veykril** [comment]
Instead of an assist this should just be a diagnostic with a fixit.

Relevant code parts to follow are https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_diagnostics/src/lib.rs and https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/hir/src/diagnostics.rs.

Most similar ones to this would probably be the `RemoveThisSemicolon` and/or `ReplaceFilterMapNextWithFindMap` diagnostics, so following how those work should give you insight on how to do this.

**Comment by gowrizrh** [comment]
i'd like to pick this up and work through it

**Comment by izik1** [comment]
So, I have gotten started with this and am still working on it (see: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/implementing.2010970.20.28diagnostic.20for.20trailing.20.60return.3B.60.29/near/264587951), umm, honestly, I'd like to get this done tonight or tomorrow night, life did what life is oh so good at and distracted me for a while
