### ISSUE TITLE
Empty diagnostics break VS Code?

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#11404]
Huh so this might be a code bug
```rs

macro_rules! f {
    () => {
        compile_error!("");
    };
}

f!();
```
breaks the diagnostics of the file, which I assume is because we post an empty diagnostics message

_Originally posted by @Veykril in https://github.com/rust-analyzer/rust-analyzer/issues/10051#issuecomment-1027226141_

**Comment by lowr** [comment]
I've dug into VSCode's codebase, and indeed they filter out the diagnostics with an empty message ([code](https://github.com/microsoft/vscode/blob/5acd9508c913b1d0ce3243f056c3cb039bac6938/src/vs/platform/markers/common/markerService.ts#L201-L203) and [relevant issue](https://github.com/microsoft/vscode/issues/5952); note that `IMarkerData`s are created from `Diagnostic`s). It's a bit unkind of them that they didn't document this...

I'm not sure if this should be fixed on their end (after all they "fixed" a bug), so we may want to workaround this limitation by inserting a whitespace (confirmed it works) or maybe some dummy text like "(empty)".

**Comment by Veykril** [comment]
~ for one I believe it is a bug in VSCode that posting an empty diagnostic breaks all diagnostics in that file, if anything only the empty one should be filtered out in my opinion.

That aside, I think we want to replace empty diagnostics (maybe even ones that consist solely of whitespace) with some dummy message like your `(empty)` idea, solely because I don't think empty diagnostics are ever wanted.

**Comment by lnicola** [comment]
We should probably file an issue against Code.

**Comment by lnicola** [comment]
Filed the issue.

This also has the weird effect of showing stale diagnostics like ``compile_error!` argument must be a string` for `compile_error!("");`.

**Comment by lnicola** [comment]
CC https://github.com/rust-lang/rust-analyzer/pull/12440.
