### ISSUE TITLE
completion detail always renders {unknown} for return type from async fn.

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#11438]
while working on #11437 i noticed that async fn's return type renders as `{unknown}`  in completion detail:

take this minimal repro:

```rust
async fn returns_a_string() -> String {
    todo!()
}

fn main() {
    returns_a_$0
}
```
![image](https://user-images.githubusercontent.com/5489149/153097273-9ab29fa1-a95f-488e-9504-cce8b19260ee.png)

**Comment by HansAuger** [comment]
I just digged into this a bit, to see if I can handle this, recognized that I was out of my depth and wanted to present my results for anyone who wants to pick this up:

It starts here:
https://github.com/rust-analyzer/rust-analyzer/blob/1c1d900d0bb71b2611b2a6c72d3f0f31cbcc3b06/crates/ide_completion/src/render/function.rs#L112

-> 
https://github.com/rust-analyzer/rust-analyzer/blob/1c1d900d0bb71b2611b2a6c72d3f0f31cbcc3b06/crates/hir/src/lib.rs#L1323-L1330

So here `ret_type` will resolve into `TypeRef::ImplTrait` of `Future` which is what is expected, however, `ty` will resolve to `Ty::Error` because the evaluation of `lower_ty` lands here:
https://github.com/rust-analyzer/rust-analyzer/blob/1c1d900d0bb71b2611b2a6c72d3f0f31cbcc3b06/crates/hir_ty/src/lower.rs#L279-L281

I did not familiarize myself with the `hir` crate at all yet, so this is where I will stop. I hope this means something to somebody :-)

**Comment by flodiebold** [comment]
The `TyLoweringContext` for the return type should use `ImplTraitLoweringMode::Opaque`. It's a bit unfortunate that this code repeats logic from the 'official' lowering code, and maybe would be better if it used the `callable_item_signature` query.
