### ISSUE TITLE
Escape sequences are not highlighted in byte strings

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust-analyzer#11605]
Escape sequences are highlighted in normal strings, but not in byte strings.

![https://i.imgur.com/7xN9n0f.png](https://i.imgur.com/7xN9n0f.png)

Also somehow the first string is weirdly highlighted too.

**rust-analyzer version**: 4e72700e3 2022-02-28 stable

**rustc version**: rustc 1.58.0 (02072b482 2022-01-11)

**relevant settings**: None

**Comment by Veykril** [comment]
Regarding the first string, it renders fine for me, is that in an attribute macro invocation? Otherwise maybe (assuming VSCode) your client desynced and messed up its highlighting ranges, VSCode likes to do that for me sometimes.

![image](https://user-images.githubusercontent.com/3757771/156558289-604fb38f-3ee6-4bc5-a791-73da4cb66796.png)

**Comment by Veykril** [comment]
Highlighting only currently considers `ast::String`s and not also `ast::ByteString` here https://github.com/rust-analyzer/rust-analyzer/blob/a55dd29e88c6f2aa37c39b790ab7036596e74686/crates/ide/src/syntax_highlighting.rs#L346-L348
should be as easy as just handling both I believe.

**Comment by CryZe** [comment]
> Regarding the first string, it renders fine for me, is that in an attribute macro invocation?

Oh yeah sorry it was.

**Comment by jonas-schievink** [comment]
Fixed by  #11687
