### ISSUE TITLE
Rust analyzer incorrectly analyzes file as "Does not belong to any crate"

### ISSUE THREAD

**Issue by tigercat2000** [rust-lang/rust-analyzer#12189]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 5d5bbec9b 2022-05-08 nightly

**rustc version**: (eg. output of `rustc -V`)
rustc 1.62.0-nightly (52ca603da 2022-04-12)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
Unknown.

In my project here:
https://github.com/spacestation13/BYONDDiffBots

Rust Analyzer won't load [`crates/mapdiffbot2/src/github_processor.rs`](https://github.com/spacestation13/BYONDDiffBots/blob/master/crates/mapdiffbot2/src/github_processor.rs) as part of the `mapdiffbot2` crate. Instead, it just reports "File info: Does not belong to any crate", as seen below.

![Problem shown in VSCode](https://i.tigercat2000.net/2022/05/Code_IWwFPjk6RF.png)

This doesn't happen with any other files in the repository. [`crates/mapdiffbot2/src/rendering.rs`](https://github.com/spacestation13/BYONDDiffBots/blob/master/crates/mapdiffbot2/src/rendering.rs) loads fine:

![Example of problem not occuring](https://i.tigercat2000.net/2022/05/Code_8JU5y5gt7I.png)

Furthermore, on the [`idb2` branch](https://github.com/spacestation13/BYONDDiffBots/tree/idb2), [`crates/icondiffbot2/src/github_processor.rs`](https://github.com/spacestation13/BYONDDiffBots/blob/idb2/crates/icondiffbot2/src/github_processor.rs) does not have the issue, while [`crates/mapdiffbot2/src/github_processor.rs`](https://github.com/spacestation13/BYONDDiffBots/blob/idb2/crates/mapdiffbot2/src/github_processor.rs) does, despite having the same file name, and being included with the same `mod` statement in the respective `main.rs`.

![Example of problem not occuring](https://i.tigercat2000.net/2022/05/Code_yZ5tXTfZIz.png)
![Example of problem occuring in file of the same name](https://i.tigercat2000.net/2022/05/Code_FszPVx4kcF.png)

Please let me know if there is any more information I can provide, I'm not familiar with how to debug rust-analyzer.

**Comment by tigercat2000** [comment]
I also can't reproduce my own bug. It now just works.
![Image of the same file now working correctly](https://i.tigercat2000.net/2022/05/Code_Fmfhu1onCO.png)

I tried to restart VScode completely, reload rust-analyzer, delete the file contents, rename the file, and none of it worked before... and now it just works.

Weird.

**Comment by Veykril** [comment]
Will close the issue then since we have no hints on what caused this, if it re-appears feel free to reopen it.

**Comment by ConsoleTVs** [comment]
I just had this happened to me right now.

![Screenshot 2023-04-11 at 19 09 03](https://user-images.githubusercontent.com/6124435/231237995-

![Screenshot 2023-04-11 at 19 09 23](https://user-images.githubusercontent.com/6124435/231238073-f8555930-4b38-4cfe-91ab-3ca12b9f8f1d.png)
d19b3f19-72f5-444a-9ea4-e298f28d8d40.png)

![Screenshot 2023-04-11 at 19 09 36](https://user-images.githubusercontent.com/6124435/231238124-6eb72e9a-c912-49af-bf0d-5b5a0d24d7b4.png)

If I rename the file it then works. I assume it has to do with the file name being duplicated somehow... (as there's also another cache.rs file somewhere else)

Happy to share you more about it, it is an open source. Here's the current file structure, frozen for you to try out: https://github.com/ConsoleTVs/Valar/tree/36a4704a48559594ae2574f75483d68755004cf8

Let me know if you need anything else, cheers!

**Comment by AuracleTech** [comment]
Keeps happening to me too... I noticed its most often when I create a new file and copy paste some code. Can't tell which part does that exactly, but either way very annoying.

**Comment by flodiebold** [comment]
@AuracleTech when you just create a new file, it's not part of any crate. So unless it's still showing up after you added the `mod` statement, the notification is working as intended.

**Comment by AuracleTech** [comment]
Not only I get the notification after adding mod, the notification is always for the cargo.toml file for some reason, or cargo.lock not sure, one of the 2

**Comment by ElHyperion** [comment]
Also keeps happening to me for some reason. whenever I open Cargo.toml. This didn't happen a few months ago.
![image](https://user-images.githubusercontent.com/5313557/232419245-c3df1a4a-5f18-4750-97a5-e20b449fcb3d.png)

**Comment by AuracleTech** [comment]
Because there's an issue use [this](https://github.com/rust-lang/rust-analyzer/issues/12189#issuecomment-1504682854) to fix it up until they fix it

**Comment by ConsoleTVs** [comment]
> 

I am not sure if that issue would fix the file not getting "analysed", therefore losing type information.

**Comment by nngeorgiy** [comment]
I'm being bombarded by the same `file does not belong to` prompts, but my circumstances are different. First, there's an additional error right after starting VS Code:
```
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/jammy/Workspace/notes/./Cargo.toml, Some(Version { major: 1, minor: 68, patch: 2 }): Failed to run `cd "/home/jammy/Workspace/notes" && "cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/jammy/Workspace/notes/./Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: manifest path `/home/jammy/Workspace/notes/./Cargo.toml` does not exist
```
The difference is, unlike posters above, I use multiple root folders in my workspace, and the `notes` folder is just a bunch of `.md` files. The only Rust code is in the `hello` folder, and it's just an empty project courtesy of cargo. When I reorder the two folders in VS Code so that the `hello` folder is first, all the errors vanish. When I reorder them back, they reappear. It looks to me that the VS Code extension just grabs the first root folder in the workspace and ignores the rest?

I use `rust-analyzer v0.3.1481` with `rustc 1.68.2`. The issue reproduces with all extensions other than `rust-analyzer` disabled and VS Code restarted.

**Comment by AsafFisher** [comment]
Can confirm that what @nngeorgiy noticed it true.
There is an issue here, please reopen.

**Comment by Veykril** [comment]
Make sure to check your vscode workspace settings don't have any `linkedProjects` settings configured. Other than that, please open a new issue ideally with a repo that reproduces this.

**Comment by Robbepop** [comment]
Since a few days I have this problem with some test code. VS Code (`rust-analyzer`) constantly generates a `.vscode/settings` file with following contents:
```json
{
    "rust-analyzer.showUnlinkedFileNotification": false
}
```
This is very annoying and I hope this will get fixed soon.

The testcode that constantly triggers this is the following:
https://github.com/paritytech/wasmi/blob/rf-engine-regmach/crates/wasmi/src/engine/tests/regmach/op/call/indirect.rs

**Comment by elBuitre** [comment]
This is happening to me too, only for a file within a subfolder

**Comment by Robbepop** [comment]
btw.: I think this bug is connected to https://github.com/rust-lang/rust-analyzer/issues/15352.

**Comment by DXist** [comment]
I reproduce the bug in a project that has one Cargo.toml both for workspace and root package configuration.

**Comment by emircanerkul** [comment]
I also facing the same problem. Why this issue is closed?

**Comment by willhansen** [comment]
I am also running into this

**Comment by saviaa1** [comment]
I also encountered this. Not sure if this helps but closing VScode and deleting workspaceStorage folder content (located in Windows: "C:\Users\<USERNAME>\AppData\Roaming\Code\User\workspaceStorage") seemed to have solved my case which to me indicates that there might be some sort of cache corruption that requires some specific circumstances to happen because I have not been able to reproduce this problem to test if deleting that folder content actually solved it or was it something else I was doing.

**Comment by servusdei2018** [comment]
> I also encountered this. Not sure if this helps but closing VScode and deleting workspaceStorage folder content (located in Windows: "C:\Users<USERNAME>\AppData\Roaming\Code\User\workspaceStorage") seemed to have solved my case which to me indicates that there might be some sort of cache corruption that requires some specific circumstances to happen because I have not been able to reproduce this problem to test if deleting that folder content actually solved it or was it something else I was doing.

I just ran into the same issue; restarting VSCode and WSL didn't work.

Then I realized the issue:

- On disk, I had
  -  commands/
     - mod.rs
     - ...(other module files)
- Which were up-to-date and compiled, but when I opened any of them, `rust-analyzer` warned that they were unused (which was false).
- **The issue was that** I had a temporary, unsaved editor open for `commands.rs`, which was a file that had *used to exist* before I had split its functionality up into the `commands/` directory + files.
- Closing this editor immediately caused `rust-analyzer` to stop reporting the false positive.

Not sure if this counts as a bug, but with a ton of editors open, it can really be hard to realize this is causing the rust-analyzer issue and lead people to scratch their heads for a long time.

**Comment by naiquevin** [comment]
I just encountered this and it was the exact same case as mentioned by @servusdei2018: 

> The issue was that I had a temporary, unsaved editor open for commands.rs, which was a file that had used to exist before I had split its functionality up into the commands/ directory + files.

Closing the old buffer fixed it immediately, without having to restart the editor (emacs + eglot)
