### ISSUE TITLE
Hover on floating consts shows zero if their value is positive

### ISSUE THREAD

**Issue by RReverser** [rust-lang/rust-analyzer#12380]
**rust-analyzer version**: rust-analyzer version: 81805d4cf 2022-05-24 nightly

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

If I have consts like those:

```rust
const INT_POS: i32 = 10;
const INT_NEG: i32 = -10;
const F32_POS: f32 = 10.0;
const F32_NEG: f32 = -10.0;
const F64_POS: f64 = 10.0;
const F64_NEG: f64 = -10.0;
```

Then hovering on `INT_POS`, `INT_NEG`, `F32_NEG` and `F64_NEG` shows their values as expected. E.g.:

![image](https://user-images.githubusercontent.com/557590/170147657-57856512-3da7-4437-b89d-ac1fbf492380.png)

However, hovering `F32_POS` and `F64_POS`, for some reason, shows zeros:

![image](https://user-images.githubusercontent.com/557590/170147740-5f85bfcd-88b3-4f6c-b3f7-bdc155d3e83e.png)

**Comment by jhgg** [comment]
We never actually seem to lower the `ast::LiteralKind` for a `FloatNumber` to its proper value in hir:

https://github.com/rust-analyzer/rust-analyzer/blob/60a2ab4c676964311d8eaca733323c221cc466e1/crates/hir-def/src/body/lower.rs#L981

**Comment by RReverser** [comment]
Then I'm even more puzzled why negative numbers work as expected.

**Comment by jhgg** [comment]
So, the root of the issue is that const evaluation doesn't support negated unary op for floats:

https://github.com/rust-lang/rust-analyzer/blob/1f011fa4a3c9793abc4b856d0a6248b9a0451fc1/crates/hir-ty/src/consteval.rs#L205 

Thus, we fall-back to using the syntax tree to render the value:

https://github.com/rust-lang/rust-analyzer/blob/1f011fa4a3c9793abc4b856d0a6248b9a0451fc1/crates/hir-ty/src/consteval.rs#L205

However, when handling a raw literal e.g: `10.0` we look at the literal value directly, which is set to 0 by the aforementioned code. 

https://github.com/rust-analyzer/rust-analyzer/blob/1f011fa4a3c9793abc4b856d0a6248b9a0451fc1/crates/hir-ty/src/consteval.rs#L159

**Comment by feniljain** [comment]
On looking into it, the reason it is not implemented over here:

https://github.com/rust-lang/rust-analyzer/blob/d7c147406eff20783abba6ff1fe250ecc44cf800/crates/hir-def/src/body/lower.rs#L981

is because of this `FIXME` reason note:

https://github.com/rust-lang/rust-analyzer/blob/d7c147406eff20783abba6ff1fe250ecc44cf800/crates/hir-def/src/expr.rs#L49

**Comment by RReverser** [comment]
> is because of this `FIXME` reason note

If that's not something quick to implement, could we at least fall back to raw literal handling as in

> Thus, we fall-back to using the syntax tree to render the value:

Instead of rendering zero?

**Comment by feniljain** [comment]
@jhgg would it better to return `ConstEvalError::NotSupported` for `Float` variant of `Literal` over here:

https://github.com/rust-lang/rust-analyzer/blob/d7c147406eff20783abba6ff1fe250ecc44cf800/crates/hir-ty/src/consteval.rs#L159

And I will add a note around here

https://github.com/rust-lang/rust-analyzer/blob/d7c147406eff20783abba6ff1fe250ecc44cf800/crates/hir-def/src/expr.rs#L49

for fixing this error, in case we implement some semi-precisoned/hacky way of `Eq` for `f64` in future

**Comment by flodiebold** [comment]
We should be able to just encode the float into the u64 as bits, using `to_bits` and `from_bits`. We don't need ordering here, and bit-wise equality should be fine.

**Comment by RReverser** [comment]
That works too. Personally I'd still use some newtype wrapper that would use `{to,from}_bits` only in implementation of `PartialEq` for readability, otherwise the next contributor will be equally confused by float being represented as `u64`.

**Comment by rben01** [comment]
I'm seeing this issue on `rust-analyzer version: 0.3.1178-standalone (a670ff888 2022-08-21)`. Not sure if it's due to a regression or if bd06902f90ecc5d411d1743c9cfdbd2bb956e4f5 just hasn't made it into master yet, but just thought I'd bring it up.
