### ISSUE TITLE
A method inside a trait, when generated by a macro and implemented in another module, won't show in autocomplete list

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/rust-analyzer#12483]
**rust-analyzer version**: ad6810e90 2022-06-06 stable

**rustc version**: 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: VSCode 1.67.2, Windows 10 x64

Mininum reproducible example:

```rust
mod other_mod {
    macro_rules! make_method {
        ($name:ident) => {
            fn $name(&self) {}
        };
    }

    pub trait MyTrait {
        make_method! { by_macro }
        fn not_by_macro(&self) {}
    }

    pub struct Foo {}

    impl MyTrait for Foo {}
}

fn main() {
    use other_mod::{Foo, MyTrait};
    let f = Foo {};
    f.by_macro(); // <-- this method won't show in autocomplete
    f.not_by_macro();
}
```

A screenshot. The `by_macro()` method is not shown:

![macro_show](https://user-images.githubusercontent.com/1283868/172272967-52ff3da5-5d59-445c-acda-69a36c57f942.png)

But if you remove the `other_mod` module, the method is actually shown in the autocomplete list:

![method-shows](https://user-images.githubusercontent.com/1283868/172273239-3405920d-d7eb-4d65-832a-d4f1a134828d.png)

Note: I remember maybe 2 or 3 months ago when rust-analyzer showed everything perfectly fine, so I believe some change was made in this period that broke this functionality.

**Comment by flodiebold** [comment]
Huh. Type inference and hover still work, so this seems to actually be a completion problem.

**Comment by xuhongxu96** [comment]
I've investigated this issue. It has existed since https://github.com/rust-lang/rust-analyzer/commit/2a7793d912bafef2d97c0e899262b94efe977543. But the change just disabled the private members for auto completion and is not the root cause.

Seems the root cause is that the `fn` expanded from the `macro_rules!` has `private` visibility because there is no `inherited_visibility` when lowering the macro.
