### ISSUE TITLE
Feature Request: Special casing for PhantomData in "Generate new" and "Fill struct fields" assists

### ISSUE THREAD

**Issue by soruh** [rust-lang/rust-analyzer#12535]
I think it would be good for the "Generate new" and "Fill struct fields" assists to automatically insert `PhantomData` for all values of type `PhantomData`.

So for a struct like this:

```rust
struct Foo<T> {
    bar: u8,
    _phantom: PhantomData<T>,
}
```

the current behavior is this:
```rust
impl<T> {
    pub fn new(bar: u8, _phantom: PhantomData<T>) -> Self { // generate new
        Self { bar, _phantom }
    }
    pub fn from_t(t: T) -> Self {
        Self { // fill struct fields
            bar: todo!(),
            _phantom: todo!()
        }
    }
}
```
and it should be
```rust
impl<T> {
    pub fn new(bar: u8) -> Self { // generate new
        Self {
            bar,
           _phantom: PhantomData
        }
    }
    pub fn from_t(t: T) -> Self {
        Self { // fill struct fields
            bar: todo!(),
            _phantom: PhantomData,
        }
    }
}
```

If there is no capacity to implement this I would be interested in potentially implementing this myself. In that case I would appreciate a few pointers on where to start, as I am completely  unfamiliar with the code base.

**Comment by flodiebold** [comment]
The "generate new" assist is here:
https://github.com/rust-lang/rust-analyzer/blob/65874dfff205335840cc9265ba06d74f234b719d/crates/ide-assists/src/handlers/generate_new.rs#L51-L55
Whereas for the "fill struct fields" assist, the relevant code is here:
https://github.com/rust-lang/rust-analyzer/blob/65874dfff205335840cc9265ba06d74f234b719d/crates/ide-diagnostics/src/handlers/missing_fields.rs#L94-L99

To detect PhantomData, you'll want to add it to `FamousDefs`:
https://github.com/rust-lang/rust-analyzer/blob/65874dfff205335840cc9265ba06d74f234b719d/crates/ide-db/src/famous_defs.rs#L8-L11

**Comment by soruh** [comment]
> The "generate new" assist is here:
> 
> https://github.com/rust-lang/rust-analyzer/blob/65874dfff205335840cc9265ba06d74f234b719d/crates/ide-assists/src/handlers/generate_new.rs#L51-L55
> 
> Whereas for the "fill struct fields" assist, the relevant code is here:
> 
> https://github.com/rust-lang/rust-analyzer/blob/65874dfff205335840cc9265ba06d74f234b719d/crates/ide-diagnostics/src/handlers/missing_fields.rs#L94-L99
> 
> To detect PhantomData, you'll want to add it to `FamousDefs`:
> 
> https://github.com/rust-lang/rust-analyzer/blob/65874dfff205335840cc9265ba06d74f234b719d/crates/ide-db/src/famous_defs.rs#L8-L11

Thanks a ton, I'll get started with looking into those places

**Comment by soruh** [comment]
> It might make sense to do this for every empty struct or enum with a single variant.

That's a good point. Is there a good way to detect if a type is an empty struct enum with a single variant?

**Comment by soruh** [comment]
Also, when I want to write a test for this, I will probably need to extend `MiniCore` to include `PhantomData`, right?

**Comment by soruh** [comment]
Okay so I think I have found a way to detect empty enums and structs. I'll try implementing that first and if there turn out to be reasons against it I'll change it to use `FamousDefs` and only `PhatonData`

**Comment by jhgg** [comment]
Practically speaking, single value enums aren't really a thing, and I don't think should be special cased by this assist. 

Usually, when I'm writing an enum, if it has a single value, that's just because I haven't gotten to writing the rest yet. Would much prefer if this assist had no special handling for enums, but I can totally understand empty structs being reasonable. Then again, in the prototyping stage, I do sometimes just write a bunch of structs that might not contain much/anything in them, get the "API" working (of which new functions can exist), and *then* do I fill them in with things. This would make the "generate new" much much less useful in these situations. 

However, I think that for the "fill struct fields" assist, if there is only one way to construct said thing, that's probably what I wanted the assist to do. 

So, I don't think we should apply the empty struct/single variant enum to the "generate new" function. I absolutely think we should however handle `PhantomData` specially though, since it is almost never sensible to pass a phantomdata into a new function, or any function for that matter.

**Comment by soruh** [comment]
I would be open to modifying my PRbut I would like know what exactly the assist should do. Is there some established way to find a consensus for these kinds of situations?
