### ISSUE TITLE
VSCode: Enum struct variant patterns auto-complete to invalid code

### ISSUE THREAD

**Issue by msrd0** [rust-lang/rust-analyzer#12593]
When auto-completing an enum struct variant, i.e. starting to type `Test::Va` and hitting enter, I get the following completion:

![image](https://user-images.githubusercontent.com/7853372/174631896-3851ebb1-1e1b-4451-82aa-51c743de7742.png)

Please remove the `: ()` part from the completion.

**Comment by jonas-schievink** [comment]
This is arguably correct though. It matches what that completion does in expression position. Probably assuming that the shorthand syntax is wanted is better though.

**Comment by Veykril** [comment]
I think the shorthand in patterns is always preferred. With `: ()` being emitted you at best gain a free `:` but if you want the shorthand you have to delete parts of the completion again. Meanwhile if we only did shorthands here at worst you'd have to type out an extra `:`.

Though maybe this is configuration worthy.

**Comment by msrd0** [comment]
I think in a pattern position, `: ()` is always unwanted. In expression positions, the `()` part is almost never what I want, and using a locally available variable as the value is, at least in the code I write, not that uncommon, where the `:` is also unwanted.

**Comment by yue4u** [comment]
We are already suggesting local variable aware code in the `missing_fields` diagnostic so I think it's also doable in this case? 

https://github.com/rust-lang/rust-analyzer/blob/187bd7d48afda84d6aff578274585d9835cbd4bb/crates/ide-diagnostics/src/handlers/missing_fields.rs#L528-L553

In comparison, `missing_fields` was changed to fill `todo!()` instead of `()` as discussed in https://github.com/rust-lang/rust-analyzer/pull/10105

**Comment by Veykril** [comment]
This doesn't really need any of that functionality there, we should just not emit a `: ()` by default.

The problem here seems to be that we render this completions via https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/render/variant.rs#L19 while we should use https://github.com/rust-lang/rust-analyzer/blob/6fc5c3cd2117a29981ba9b7cef8a51c1d6804089/crates/ide-completion/src/render/pattern.rs#L43-L49 instead, not entirely sure haven't digged into it.
