### ISSUE TITLE
Make `--nocapture` optional

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust-analyzer#12737]
When running tests, rust-analyzer [unconditionally](https://github.com/rust-lang/rust-analyzer/blob/361cddc16ca85b9981d3d892eda474aa57d92bcc/crates/rust-analyzer/src/cargo_target_spec.rs) adds `--nocapture` to the test arguments. I would like this to be optional, because using `--nocapture` leads to sometimes-unreadable interleaved output, especially when two tests fail simultaneously, or when successful tests are producing verbose output intended to be read only if the test fails.

**Comment by dnut** [comment]
I would implement this by making cargo args configurable in general, allowing the user to enter an arbitrary string. There's nothing particularly special about --nocapture that entitles it to special treatment compared to other cargo args. I would also make it empty by default, as in --nocapture should not be enabled unless the user explicitly turns it on by typing it, due to the reasoning in #13040.

**Comment by kpreid** [comment]
A possible complication in "just" making test arguments customizable: there are both arguments to cargo and arguments to the test binary, and users might want to specify one or both. I think accepting an argument list that may include `"--"` should solve that problem adequately and intuitively.

**Comment by matklad** [comment]
I personally feel strongly that `--nocapture` is the right default. The current default of `--show-output` makes it impossible to debug the tests, as you don't see the output until the end, which might not come.

The more "stuff" happens between the user and the test binary, the harder it is to realize what's happening. 

The problem with interleaved test output should be fixed by making sure that passing tests do not print anything.

Interleaving output is a _feature_ when you debug a tricky concurrency bug caused by interraction between the tests.

It is of course file to have an _option_ to use `--show-output` as an easy-accessible checkbox, but I am 0.8 sure that `--nocapture` would be the right default leading to better ecosystem, _precisely_ because it forces you to be intentional about your test's output. 

To reiterate, this is my personal opinion, and, while I do hold is strongly, it could be wrong.

**Comment by dnut** [comment]
Regarding the treatment of stdout, I can see reasonable arguments on both sides, but I don't think these arguments are relevant to rust-analyzer. These arguments are more relevant to rustc. If the default behavior should be to not capture stdout, then why shouldn't we change rustc to have that behavior? I believe that rust-analyzer's defaults should be consistent with rustc's defaults, whatever they are. Discrepancies in behavior are a source of confusion and frustration.

**Comment by kpreid** [comment]
> I personally feel strongly that `--nocapture` is the right default.  … The problem with interleaved test output should be fixed by making sure that passing tests do not print anything.

For what it’s worth, I'll give some additional background, as the author of this issue and PR, since our experiences of testing seem to be very different:

I find it very frequently useful to write tests that “log” their actions with simple `println!`s, so that if the test fails, I can see what was computed *before* the failure, that led to the erroneous situation. It would be possible to implement this within individual tests, using an explicit log and a `Drop` implementation that prints it on panic; but setting one up is work the rustc test harness saves me from. And to me, if I have to _modify an existing test_, e.g. adding more printing, to understand why it failed, that's a deficiency in the test suite; it means I have to spend time editing tests and rerunning before I can get to fixing the bug I just introduced.

Instead of “passing tests do not print anything”, the property I like is “I don't *see* anything from passing tests”, which is what the test harness’s default mode (not `--nocapture` and not `--show-output`) does. The only reason my PR #17105 switched to `--show-output` rather than no flags was for a smaller change to the status quo (and I find the verbosity of `--show-output` less bothersome when it's isolated in its own tab of test output instead of in my main terminal).

> Interleaving output is a *feature* when you debug a tricky concurrency bug caused by interraction between the tests.

I agree with the logic, but the case is rare for me: I have *never* had tests interfere with each other (in the kind of code I write, which is on the “avoid global state at nearly all costs” side of things), and hanging tests are very rare and usually need more intervention than _just_ being able to look at the output in `--nocapture` style (e.g. modifying the code to print more of its progress, and running with other additional options). I’m also surprised by these two claims occurring simultaneously: if a passing test is designed to print nothing, then surely it is likely that a hanging test will also print nothing, so default `--nocapture` will not help?

Also, when RA used `--nocapture`, I regularly saw users having trouble with understanding interleaved output from multiple test failures — even the panic hook output by itself could be interleaved in illegible fashion (though that was recently improved by https://github.com/rust-lang/rust/pull/127397).

---

One exception: I do think it would make sense to pass `--nocapture` along with `--exact`; when running _exactly one test_, there is no disadvantage to uncaptured output.
