### ISSUE TITLE
[Feature Request] Show visual hint when there is a "Panic" section in the document.

### ISSUE THREAD

**Issue by uonr** [rust-lang/rust-analyzer#13070]
When there is a "Panic" section in the document:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/34709816/185716055-ecfb605f-d887-4cd4-9249-e84278e2fd2a.png">

Show some visual hint (for example):

<img width="401" alt="image" src="https://user-images.githubusercontent.com/34709816/185716165-0428b0f4-779b-4847-b635-b9b01addfcaa.png">

or change background, etc.

If this feature is worth implementing, I would be interested in contributing.

**Comment by Veykril** [comment]
Showing what call sites can panic and what don't sound great, but not all things that do panic will document that they do, so people might rely on something like this that doesn't actually show the full picture.

We could probably query a function for whether it panics by checking what it calls and checking all those calls for whether they panic etc, but that sounds very much expensive to do (not sure how nice salsa and its revalidation would play with this, since this implies a lot of dependencies (the entire call graph up to the panic calls in fact))

**Comment by flodiebold** [comment]
> query a function for whether it panics by checking what it calls and checking all those calls for whether they panic etc

Note that this would need to involve doing monomorphization of generic calls; also with dyn calls it'd be impossible to know whether they can panic; plus there might be lots of cases where a function can panic in theory, but is actually called in a way where it can't. So my guess would be that this would have so many false positives as to be useless.

Considering that, the checking-the-docs idea actually seems somewhat more feasible, but I agree there's a danger of false negatives. I'm not convinced this would be an actually useful feature.

**Comment by Veykril** [comment]
Right, that wouldn't be feasible at all. Ye, then I am inclinced to close this. As nice as it would be to have something like this, it doesn't seem like that can be implemented in a way that that doesn't create false negatives that could trip people up.
