### ISSUE TITLE
Surface in a more prominent way an error when a project cannot be parsed

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/rust-analyzer#13117]
When a project cannot be parsed rust-analyzer logs an error, but that error may not be obvious or clear to the developer. It can be easy to introduce something into a project, like a cyclic dev dependency, and for a developer to not realize that is why rust-analyzer is starting to fail to function.

If a project cannot be parsed by rust-analyzer there should be a prominent message about the error because chances are the developer is going to feel pain as they continue to wade on without help from RA.

Some related prior discussion to this issue is in #13115.

**Comment by jonas-schievink** [comment]
We already open (too many) popups when we cannot fetch the workspace data from Cargo, and the rust-analyzer status icon turns red too. We can't possibly make it any more prominent. As for the mostly silent error you get when you hit https://github.com/rust-lang/rust-analyzer/issues/2414, that should just be fixed by fixing https://github.com/rust-lang/rust-analyzer/issues/2414 itself.
