### ISSUE TITLE
Let in constant expression declared from macro, Incorrectly-removed spaces in hover

### ISSUE THREAD

**Issue by RuijieYu** [rust-lang/rust-analyzer#13143]
The following code snippet contains a few minimal scenarios I came up for somewhat different cases.  I hovered on all of `V1..V4` and the hover message is shown below their respective declaration site.  

As seen in the snippet, the hover messages on `V1`, `V2` and `V3` are incorrect, where the spaces are incorrectly removed between `let` and `e`.  In addition, I noticed that `V4` does not expand the `m4` macro, which I figured *might* relate to the root of the issue.

The code compiles and runs successfully.

```rust
use std::num::NonZeroU8;

macro_rules! m1 {
    ($($i:ident = $e:expr,)*) => {$(
        pub const $i: NonZeroU8 = {
            let e = $e;
            unsafe { NonZeroU8::new_unchecked(e) }
        };
    )*};
}
m1!(V1 = 2,);
// pub const V1: NonZeroU8 = {lete=2;unsafe{NonZeroU8::new_unchecked(e)}}

const fn f(n: i8) -> i8 {
    -n
}

macro_rules! m2 {
    ($($i:ident = $e:expr,)*) => {$(
        pub const $i: i8 = {
            let e = $e;
            // this is safe function
            f(e)
        };
    )*};
}
m2!(V2 = 4,);
// pub const V2: i8 = {lete=4;f(e)}

macro_rules! m3 {
    ($i:ident = $e:expr) => {
        pub const $i: i8 = {
            let e = $e;
            f(e)
        };
    };
}

m3!(V3 = -22);
// pub const V3: i8 = {lete=(-22);f(e)}

macro_rules! m4 {
    ($e:expr) => {{
        let e = $e;
        f(e)
    }};
}
pub const V4: i8 = m4!(-42);
// pub const V4: i8 = m4!(-42)

fn main() {
    println!("{:?}", (V1, V2, V3, V4));
}
```

---

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

```console
$ rust-analyzer --version
rust-analyzer 0.0.0 (a670ff888 2022-08-21)
```

**rustc version**: (eg. output of `rustc -V`)

```console
$ rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
Environment: emacs with lsp.  I don't believe any of my configurations are relevant.

**Comment by ChayimFriedman2** [comment]
This is not the same issue. `m4!()` is not expanded because we don't descend into macros when printing const bodies, it is just that `m1!()`, `m2!()` and `m3!()` are descended into because they also create the const itself, so to get its definition we need to expand them.

The space is missing because macro expansion removes all trivias; a fix can be to call [`insert_ws_into()`](https://github.com/rust-lang/rust-analyzer/blob/989b09d20cafc2b1eb9198e25701b9e2234d8ba0/crates/ide-db/src/syntax_helpers/insert_whitespace_into_node.rs#L13) for macro expanded const bodies, the same we do for "Expand macro recursively".
