### ISSUE TITLE
Small inconsistency in module completion

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-analyzer#13196]
Say I have a module `mmio.rs` on disk, then I go to complete the following line:
```
pub mod mmi
```
RA will suggest to complete the line as `mmio;`

However, if instead the line already says
```
pub mod mmio
```
Then RA won't have any suggested completions at all.

It would be better if it could still to suggest that the line be completed with `;`

**Comment by Veykril** [comment]
The cause is this line here https://github.com/rust-lang/rust-analyzer/blob/6dfd8aebdfa1ee1824446f01daf5bdb229b32f92/crates/ide-completion/src/completions/mod_.rs#L94

`existing_mod_declarations` is created here, https://github.com/rust-lang/rust-analyzer/blob/6dfd8aebdfa1ee1824446f01daf5bdb229b32f92/crates/ide-completion/src/completions/mod_.rs#L53-L56
and as soon as the mod declaration that is being completed resolves it will filter itself out by existing in that set. We should filter out the declaration we are currently completing from the set there.

**Comment by michealkeines** [comment]
Hi, can i work on this?
