### ISSUE TITLE
Allow toggling code lens positions

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/rust-analyzer#13218]
Currently code lenses are positioned between doc comments/attributes and the item they're decorating, like this

![image](https://user-images.githubusercontent.com/25047011/189497651-3dd67b59-8e94-4cbb-b64f-7a7ade0391f4.png)

But I personally would rather it be above the doc comments and attributes, so an option to toggle their position would be awesome

**Comment by Veykril** [comment]
Relevant code is here (minus the config part) https://github.com/rust-lang/rust-analyzer/blob/b7e8b9a6b8f25f269bc141f2749555418ab0f370/crates/ide/src/annotations.rs#L123-L134

For this new case we should just take the range of the whole node instead of the name, that should make editors place it above the comments and attributes. This should as stated be done with a config flag toggling the behavior, with the current behavior staying the default.

**Comment by mdx97** [comment]
I'm working on this one but am running into an issue regarding how to configure this feature.

I figured it would be best to add a new enum configuration value. I've called this `lens_annotation_location`, which now will have values of `above_name` and `above_whole_item` (naming can be hashed out in the PR, just giving this information for context).

I'm not exactly sure where to put the Rust enum definition at, however. I need acess to this type in both the `ide` and `rust-analyzer` crates. But there are problems with either option:
- I can't really put the type in `rust-analyzer` because it depends upon the `ide` crate, which would result in a circular reference between the two crates.
- Having a config type exist in the `ide` crate doesn't seem to be a common pattern of the project. I'd have to add `serde` as a dependency of `ide`, which feels weird for this one-off scenario.

Does anyone have opinions?

**Comment by Veykril** [comment]
usually we define the enum twice, once in IDE as the actual used thing, and the second time just for deserializing purposes in the config module in rust-analyzer, and then we map between the two. Thre should be some enum in config.rs doing this already.
