### ISSUE TITLE
move_format_string_arg issue if arguments contain parentheses/token trees

### ISSUE THREAD

**Issue by la10736** [rust-lang/rust-analyzer#13261]
**rust-analyzer version**: `0.3.1212-standalone`

**rustc version**: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`

**relevant settings**: nothing

I found a little glitch in the amazing `move_format_string_arg`:

```rust
    fn yeld(&self) {
        let x = 2;
        println!("My name is {} {x + x}", stringify!(Paperino))
    }
```

Apply assistant to `{x + x}` transform it in 

```rust
println!("My name is {} {}", stringify!, x + x)
```

**Comment by Veykril** [comment]
In this case the macro isnt the problem, the same happens if you remove the `!`, the problem are the parentheses.


> would a newtype wrapper over the text ranges we want in an edit prevent these issues?

We already have such a thing technically, `FileRange` which contains a `FileId` (opposed to a HirFileId, so that range is always a non-macro range). Usually the file id is just redundant which is why its barely used in these cases.
