### ISSUE TITLE
rust-analyzer doesn't respect VSCode "editor.paramaterHints.enable" setting

### ISSUE THREAD

**Issue by westernwontons** [rust-lang/rust-analyzer#13472]
- VS Code Version: 
1.73.0-insider
504c5a768a001b2099dd2b44e9dc39e10ccdfb56
arm64

- OS Version:
MacOS Monterey 14.6

- cargo version
cargo 1.66.0-nightly (071eeaf21 2022-10-22)

Steps to Reproduce:

1. Disable parameter hints, by putting this line into your settings: "editor.parameterHints.enabled" : false
2. Open any file and start typing a function or methods name.
3. Accept a suggestion.

Side note: I've also disabled this on the language level, by having the following line in my settings:
```json
"[rust]": {
    "editor.parameterHints.enabled": false
},
```

Video of it in action:

https://user-images.githubusercontent.com/75550932/197389995-605fab5d-ddd1-424c-ae5b-e3382512e9cc.mov

**Comment by jonas-schievink** [comment]
Looks like this happens because we explicitly request them when that type of completion is applied. The setting only seems to affect parameter hints showing up when typing `(`, and you can still request them explicitly with Ctrl+Shift+Space.

We could maybe add another setting that controls whether these hints show up after accepting a completion for a function, and have it default to the value of `editor.parameterHints.enable`? Not sure if there's precedence for that.

**Comment by novice88** [comment]
same problem

**Comment by westernwontons** [comment]
If it's alright, with a little direction I'd be happy to work on this

**Comment by westernwontons** [comment]
I have a working solution. I'm a first time contributor, so I'd appreciate a little help with submitting a PR. My fork is here:

https://github.com/westernwontons/rust-analyzer

What is expected of me and how does the PR submission flow work for rust-analyzer?
