### ISSUE TITLE
release not available on open-vsx.org

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/rust-analyzer#13543]
The previous version of the rust-analyzer plugin, that was under the command id `matklad.rust-analyzer` was published to the open-vsx.org marketplace, which made the plugin available on a variety of editor deployments, such as gitpod.io.

Starting today I noticed that `matklad.rust-analyzer` extension has been moved to `rust-lang.rust-analyzer`, however in the move the extension has not been published with a non-pre-release release.

The only release available on open-vsx.org from today (or recently) is a pre-release version.

Could the extension continue to be published to open-vsx.org so that the extension is accessible to gitpod.io and other IDEs that use it?

Related issue: https://github.com/gitpod-io/gitpod/issues/14416

**Comment by lnicola** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/11080.

The extension you were using from OpenVSX was almost a year old because it couldn't be published any more. This caused quite a few issues with newer toolchains. It is now available under the new namespace and a stable release will be published on Monday.

**Comment by lnicola** [comment]
A stable release is now out: https://open-vsx.org/extension/rust-lang/rust-analyzer/0.3.1277.
