### ISSUE TITLE
clippy::needless_return quick fix changes functionality of code

### ISSUE THREAD

**Issue by DusterTheFirst** [rust-lang/rust-analyzer#13675]
**rust-analyzer version**: 0.3.1293-standalone

**rustc version**: rustc 1.66.0-beta.2 (0040709e3 2022-11-20)

Reproduction code:
```rs
use std::process::ExitCode;

fn main() -> ExitCode {
    return ExitCode::SUCCESS;
}
```

Quick fix in question:
![image](https://user-images.githubusercontent.com/14093962/203968144-95f58e6f-bb05-4c5d-b186-d2d4acb8e517.png)

The quick ""Fix"" removes the return, but not the semicolon, thus making the value no longer get returned:
![image](https://user-images.githubusercontent.com/14093962/203968200-fb370c7e-4aa3-4b02-8545-94294b5a3460.png)

**Comment by bjorn3** [comment]
Does the suggestion returned by clippy remove the semicolon? If not, this is a clippy bug.

**Comment by DusterTheFirst** [comment]
cargo clippy --fix produces
```rs
use std::process::ExitCode;

fn main() -> ExitCode {
    ExitCode::SUCCESS
}
```

**Comment by lowr** [comment]
You need the following settings to reproduce (with beta toolchain installed):
```json
{
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.server.extraEnv": { "RUSTUP_TOOLCHAIN": "beta" }
}
```

The problem is that, due to rust-lang/rust-clippy#9497, `needless_return` now [produces multiple subdiagnostics](https://github.com/rust-lang/rust-clippy/pull/9497/files?diff=unified&w=0#diff-8f0855f6d317c27d014d172305afe96b317ac395277afd3324d468e17c808d50R263-R269), one for removing `return` and others for removing (possibly multiple) semicolons. If you hover on the line, you can see "remove this semicolon" message, and you can actually apply the quick fix if you place your cursor around the semicolon.

"remove this semicolon" diagnostics are hidden when you run clippy in terminal (see [`Diagnostic::tool_only_span_suggestion()`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_errors/diagnostic/struct.Diagnostic.html#method.tool_only_span_suggestion)) so ideally we'd want to coalesce them into the "primary" quickfix (remove `return`), but I'm not sure if we have any way to distinguish those hidden ones from others without special-casing every such diagnostic. Or can we just coalesce all subdiagnostics that have machine-applicable fix into one?

**Comment by kpreid** [comment]
I remember seeing this misbehavior myself, but I cannot reproduce it now (Rust 1.77.0 and RA 0.3.1896-standalone (6f6b03f9d 2024-03-24)) — the only relevant quick fix option removes both the "return" and the ";". Should this issue be closed as fixed?

**Comment by DusterTheFirst** [comment]
I can agree. With `rust-analyzer 1.78.0-beta.2 (277d06b 2024-03-23)` and `rustc 1.78.0-beta.2 (277d06bc9 2024-03-23)` the quick fix removes both the semicolon and the return statement. I will close this as resolved.
