### ISSUE TITLE
associated consts for trait impls are ignored

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#13694]
We only resolve them to the trait declaration, no matter if a value is supplied there or not.
```rs
trait Trait {
    const B: bool = false;
}

impl Trait for () {
    const B: bool = true;
}

fn main() {
    <()>::B; // hovering B here shows `const B: bool = false`
}
```
This might be an ide layer only bug, not sure

**Comment by bvanjoi** [comment]
When I try to solve this problem, I can never find the right `Substitution` to locate `actual_trait_ref` (like https://github.com/rust-lang/rust-analyzer/blob/master/crates/hir-ty/src/method_resolution.rs#L674 does), maybe a better solution is to add `TyKind` to all 



<img width="933" alt="image" src="https://user-images.githubusercontent.com/30187863/205494722-9fa09d04-561d-49f8-a392-b52786d77439.png">

**Comment by flodiebold** [comment]
I don't think I understand your question, but I'm pretty sure modifying `TyKind` should not be necessary for this.

**Comment by unexge** [comment]
I was also looking this issue, we are getting `AssocItemId`s from `InferenceResult` and they point to definitions from traits. After getting `AssocItemId`s, for functions we are finding `TyKind::FnDef` from expression and that contains `Substitution`: https://github.com/rust-lang/rust-analyzer/blob/957b4bb2164e57a58d7e6cb5b4915b298dab9391/crates/hir/src/source_analyzer.rs#L485-L509
and since first parameter of `Substitution` is self type [`method_resolution::lookup_impl_method`](https://github.com/rust-lang/rust-analyzer/blob/master/crates/hir-ty/src/method_resolution.rs#L630-L669) finds `FunctionId` that points to function from impl block instead of trait block. But I guess there is nothing similar for `const`s

**Comment by flodiebold** [comment]
Yes, I don't think we record the substitution currently. I guess `InferenceResult::assoc_resolutions` should also contain substitutions.

**Comment by bvanjoi** [comment]
> Yes, I don't think we record the substitution currently. I guess `InferenceResult::assoc_resolutions` should also contain substitutions.

Thanks for your tips, #13725 may solve this problem.
