### ISSUE TITLE
use custom rustc compiler that uses cranelift

### ISSUE THREAD

**Issue by alexzanderr** [rust-lang/rust-analyzer#13878]
hello

i have an issue from this location: https://github.com/bjorn3/rustc_codegen_cranelift/issues/1335

i've used cranelift (cargo-clif) and build was very fast, i like it.

how can i use the `rustc-clif` from cranelift with rust-analyzer?

i didnt see any settings which specify custom compiler or compilation flags or even linker settings.

in short is just need to tell rust-analyzer to use `rustc-clif` and `cargo-clif` when doing the compilation for the project.

is it even possible?

any ideas?

thanks in advance.

if you wonder why im asking this, please read the above linked issue.

**Comment by bjorn3** [comment]
Rust-analyzer uses `cargo check` by default, which entirely skips codegen, so using rustc_codegen_cranelift won't have any effect. Mixing `cargo check` and `cargo-clif build` shouldn't invalidate the build cache if you aren't using nightly, but if you are having problems with that anyway, you can use `"rust-analyzer.server.extraEnv": { "CARGO_TARGET_DIR": "ra_target" }` as config to put the build cache used by rust-analyzer in the "ra_target" dir instead of the "target" dir.

**Comment by alexzanderr** [comment]
> shouldn't invalidate the build cache if you aren't using nightly

oh, im using nightly ...

**Comment by alexzanderr** [comment]
> you can use "rust-analyzer.server.extraEnv": { "CARGO_TARGET_DIR": "ra_target" } as config to put the build cache used by rust-analyzer in the "ra_target" dir instead of the "target" dir.

interesting, having a separate dir. wouldnt this ocupy a lot of disk space? having 2 target dirs? or basically its the same think, because RA would use a separate dir inside the target? but that doesnt make sense since the build cache is invalid. so back to first question.

**Comment by bjorn3** [comment]
Cargo allows multiple rustc versions to co-exist within the same target dir, but considers all nightly rustc to be a single rustc version to prevent every nightly update causing the target dir to grow. In your case both the `cargo check` of rust-analyzer and `cargo-clif build` you run yourself are nightly rustc and as such can affect each other's cache. Because `cargo-clif build` sets `RUSTFLAGS` to one value and `cargo check` doesn't set (or sets it to another value), cargo thinks it needs to invalidate all existing build artifacts for nightly rustc. Using a separate target dir prevents both from tripping over each other.

> interesting, having a separate dir. wouldnt this ocupy a lot of disk space? having 2 target dirs?

It would occupy more disk space, but not a whole lot in most cases. Basically only the build scripts and proc macros (and their dependencies) would get duplicated. Everything else is already duplicated between `cargo check` and `cargo build` anyway.

**Comment by alexzanderr** [comment]
ok, nice. thanks for explanation.

but the property is invalid:
```
"rust-analyzer.server.extraEnv": {
	"CARGO_TARGET_DIR": "ra_target"
}
```

**Comment by bjorn3** [comment]
Right, that is the vscode syntax. Sublime text seems to have a different configuration format. I took a look at https://lsp.readthedocs.io/en/latest/#server-configuration and I think it is something like

```json
{
  "clients": [
    "rust-analyzer": {
      "settings": {
        "rust-analyzer": {
          "server": {
            "extraEnv": { "CARGO_TARGET_DIR": "ra_target" }
          }
        }
      }
    }
  ]
}
```

but I'm not sure.

**Comment by alexzanderr** [comment]
nope. its not working, sorry.

but i found a working one:

this is for sublime-project settings
```json
"settings": {
	"LSP": {
		"rust-analyzer": {
			"enabled": true,
			"env": {
				"CARGO_TARGET_DIR": "ra-target"
			},
			"settings": {}
		}
	}
}
```
and this is for rust analyzer plugin settings
```json

			"env": {
				"CARGO_TARGET_DIR": "ra-target"
			},
			"settings": { // here are normal settings }
```

**Comment by alexzanderr** [comment]
i can confirm that the directory was populated and build cache want invalidated anymore using nightly.

and also i saw exactly what you said that proc-macros are expanded.

thanks a lot for support!
