### ISSUE TITLE
Inconsistent syntax highlighting of const generics 

### ISSUE THREAD

**Issue by veber-alex** [rust-lang/rust-analyzer#13903]
Single letter const generics show up in green while multi letter are white.
When hovering over a single letter const generic it is white.
Enabling or disabling semantic highlighting doesn't make a difference.

![image](https://user-images.githubusercontent.com/29788806/211156662-dd9c1c7d-b1c7-4e2e-bc0b-e3449f34a035.png)

rust-analyzer version: 0.4.1352-standalone

**Comment by Veykril** [comment]
There isn't much we can do here, your theme doesn't support the `constParameter` semantic token type, it only uses the textmate scopes.

The `A` const has the following textmate scopes:
```
entity.name.type.rust
meta.function.definition.rust
source.rust
```
while the `FOO` const parameter has:
```
constant.other.caps.rust
meta.function.definition.rust
source.rust
```

rust-analyzer doesn't define the textmate grammer. While we do define a mapping from the semantic token type `constParameter` to `constant.other.caps.rust`, it doesn't work here because your theme resolves the `entity.name.type.rust` already. 

I believe this is a bug in the textmate grammar where `A` should be assigned the `constant.other.caps.rust` scope instead.

**Comment by veber-alex** [comment]
It looks like my theme (it's Dark+, the default vscode theme) supports `constParameter`
If I set `"constParameter": "#ff0000"` under `editor.semanticTokenColorCustomizations.rules` I get:
![image](https://user-images.githubusercontent.com/29788806/211159979-10b9be20-4212-49eb-8834-bc659570df45.png)
The hover is still white but it looks like styles from semantic tokens don't show up in the hover in general.

**Comment by Veykril** [comment]
well that color doesn't come from your theme, its a manual override by you. With support I meant that the theme does not supply a color for `constParameter` itself. The hover always uses textmate scopes currently, that's a shortcoming of VSCode.
