### ISSUE TITLE
Inlay type hints interfere with caret placement

### ISSUE THREAD

**Issue by ze** [rust-lang/rust-analyzer#13968]
Example input:
```rs
let rd = instr >> 16 & 0xF;
```
`instr` is a u32, rd is as well as a result.

![image](https://user-images.githubusercontent.com/16655930/212819765-a5ea5107-6b44-4980-9752-61538b2ff8ec.png)
Here is me clicking on `r`.

If I click on `d`, my cursor does not move, but if I type a single letter, it does move.

![image](https://user-images.githubusercontent.com/16655930/212819930-00cbdced-9f55-44fd-97df-d663871ff8a4.png)
Here is my caret when I move via the arrow keys one spot to the right. This is an issue. The caret should be next to the `d`, but is instead placed past the type hint.

As a result, I had to disable inlay type hints as they keep messing up my caret placement.

**e.g.t-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
rust-analyzer version: 0.3.1361-standalone (f77b68a3c 2023-01-08)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.65.0 (897e37553 2022-11-02)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
None should be relevant

**Comment by lnicola** [comment]
The hints are displayed by VS Code, and you're seeing the intended behavior: https://github.com/microsoft/vscode/issues/166927. We can't do anything about it.

**Comment by bjorn3** [comment]
That issue is actually different. The vscode issie is talking about the inlay hint not being treated as a character when moving the cursor. That is when going right on `rd<|>: u32 = ...` it shows `rd: u32 = <|>...` rather than `rd: u32 =<|> ...`. But this issue is about vscode misplacing the presented cursor conpared to where it is. That is vscode shows `r<|>d: u32` when the cursor is actually at `rd<|>: u32`. This is a vscode bug, but not the same as the issue you referenced. In addition imagine it is intended behavior unlike the issue you referenced.

**Comment by lnicola** [comment]
Having tested, I can't really reproduce this. When I click on a letter, the caret goes to the left or right of it depending on exactly where I've clicked relative to the letters midpoint. But same happens before an inlay hint. If I click on the right half of the `d`, I get:

![image](https://user-images.githubusercontent.com/308347/212887144-66b7b801-3509-4682-981e-056b2e8bd4bc.png)

and typing adds a letter next to it:

![image](https://user-images.githubusercontent.com/308347/212887231-1e5e6e51-1945-4b31-b388-b0db05b6f59b.png)

**Comment by bjorn3** [comment]
I have been reliably getting it for the past couple of days.
