### ISSUE TITLE
rust analyzer failed to load workspace

### ISSUE THREAD

**Issue by ionutrogojan** [rust-lang/rust-analyzer#14042]
Error:
```ini
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /mnt/SSD/Code/Porn Folder/test_cli_animation/Cargo.toml,
Some(Version { major: 1, minor: 65, patch: 0 }): Failed to run `"/home/electricthunder/.cargo/bin/cargo" "metadata" "--format-version" "1" "--manifest-path" "/mnt/SSD/Code/Porn Folder/test_cli_animation/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error:
error: could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
```
This error does not seem to want to go away. I tried to add
```json
    "rust-analyzer.server.extraEnv": {
        "CARGO": "~/.cargo/bin/cargo",
    },
```
to the settings.json, but now I get:
```ini
rust-analyzer failed to load workspace: "~/.cargo/bin/cargo" "--version" failed: No such file or directory (os error 2)
```

I am using VSCodium from flatpak and I thought I didn't give it the correct permissions to access cargo but running
```sh
bash-5.1$ cargo -V
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```
in the VSCodium terminal outputs the version, not an error, which means VSCodium has access to the binary.
So I have no idea what to do now. Any pointers?
Cheers!

**Comment by lnicola** [comment]
Try with a non-Flatpak version of Code, we have some trouble with that.

**Comment by bjorn3** [comment]
I think using `~` in the path doesn't work. `~` is interpreted by the shell, not by the syscall to spawn a new process that is used by nodejs.

**Comment by lnicola** [comment]
I think we expand those, at least in some places.

**Comment by Veykril** [comment]
We substitute some of the vscode vars https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables

**Comment by lnicola** [comment]
Right, I was thinking of https://github.com/rust-lang/rust-analyzer/blob/master/editors/code/src/bootstrap.ts#L40-L43, but that's only for the server.

**Comment by ionutrogojan** [comment]
> Try with a non-Flatpak version of Code, we have some trouble with that (#13926).
> 
> I imagine the problem is the Flatpak sandbox preventing access to the filesystem.

It looks like installing and running the extension on the rpm binary instead of the flatpak works just fine. So the issue is with flatpak.
I can use the rpm version for now, but does anyone have an idea of what permissions I might be missing to have it run the same with the flatpak version?

**Comment by lnicola** [comment]
No, not really. Flatpak apps run in a sandbox and can't access most files on your computer. You can make it more permissive using Flatseal (available on Flahub), but that's not enough. One of the problems is that the apps won't see your real `/usr/bin`, but instead see their own (where they are installed).

On my system, I have `rustup` from a distro package, but I use it to manage the toolchains. When I run `cargo`, that's actually a symlink under `/usr/bin` pointing to `/usr/bin/rustup`, which calls `~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo`. The sandboxed Codium will see neither `/usr/bin/cargo`, nor `/usr/bin/rustup`. I can add the real location to `PATH` using Flatseal (run `echo $PATH` in Codium's terminal and include the existing ones at the beginning if you want to give it a try), but it currently doesn't work on my system because of another variable I don't know how to unset without logging out and back in.

But if you're using a distro `rustc`, this approach doesn't work. The real `/usr/bin` is accessible from `/run/host/usr/bin/rustup`, but you need to at least set `LD_LIBRARY_PATH`, and I assume that's not going to be enough.

So yeah, unless I'm missing something, this seems quite complicated, and I think the benefits of using the Flatkpak Codium are questionable. If you're worried about the telemetry, you can disable it using `"telemetry.telemetryLevel": "off"`.

**Comment by ionutrogojan** [comment]
Thanks for the answer.
I got rustup from the [manual install](https://www.rust-lang.org/learn/get-started), not a distro package like in your case, I do have `LD_LIBRARY_PATH=/usr/local/lib` set as an exported variable and from flatseal, I gave it access to the `/home` directory since there's where the cargo and rustc binaries are, so I'm not sure what's missing because the error was about the cargo bin missing which is in the home directory. 
I guess if it works with the rpm version, don't fix it.
Anyway, thanks again.

**Comment by lnicola** [comment]
> I do have LD_LIBRARY_PATH=/usr/local/lib set as an exported variable and from flatseal

That has no relevance here. You would need to set it to `/run/host/usr/lib` for the programs in `/run/host/usr/bin`, but that's not needed in your setup.

I managed to make it work by adding `~/.cargo/bin` to `PATH` in Flatseal. It looks like that's the only thing that was missing. To set it up, you need to:

 - install `rustup` from rustup.rs
 - Open Codium, start a terminal (for some reason that's very slow on my system, and it doesn't respect my shell, of course, as it doesn't exist inside the sandbox)
 - run `echo $PATH`, copy that, make a new `PATH` variable in Flatseal, paste it here, then append `:~/.cargo/bin`, replacing `~` with the path to your home directory. Include the colon too.

![image](https://user-images.githubusercontent.com/308347/215311100-aaf27936-c800-4743-8d30-ad7c19cd15ec.png)

CC @DanielProg39

**Comment by ionutrogojan** [comment]
Oh, cool!
That's very helpful. I appreciate your time and effort to help me out.
I'll try that and see how well it goes, and if it doesn't, I'll still have the rpm version, which just works out of the box.
Maybe someone else has the same issue and finds this thread useful. I was trying to search online for a solution to no success, so I guess using flatpaks is still not that popular.
Thanks again 😊

**Comment by HemanthDavuluri** [comment]
Upgrade your rust-analyzer extension to the pre-release(v0.4.1525) one. This fixed the issue on my Macbook Pro m1.
