### ISSUE TITLE
Postfix completions trigger on block expressions that are part of other expressions

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14096]
```rs
if true {}.$0 else {}
```

Triggering completions at $0 will show postfix completions that affect the `if true {}` part even though it is indivisible from the `else {}`. We should check this and not show any postfix completions in this position.

**Comment by dqkqd** [comment]
Hi, I have 2 solutions, but I'm not sure which one is good.
1. Checking if `receiver` is part of if-else statements, then early return from this.
https://github.com/rust-lang/rust-analyzer/blob/8011029d3a0f4014217e1ade75688c0f3c5305db/crates/ide-completion/src/completions/postfix.rs#L21-L28

3. Create new attribute  `receiver_is_part_of_indivisible_expression` and put it into `DotAccessKind::Field` here.
https://github.com/rust-lang/rust-analyzer/blob/8011029d3a0f4014217e1ade75688c0f3c5305db/crates/ide-completion/src/context/analysis.rs#L599-L614

 I'm leaning toward the second approach, but I'm not sure if it's fine since it will change data structure.

**Comment by Veykril** [comment]
Neither really works I think, the first will fail due to parser recovery, that is once the `.` is typed in that odd position the parser will probably recover the syntax tree in a weird way such that the check does not work (might be wrong here though).

The second approach sounds like the wrong way to fix this, we don't really want to calculate any completions in that position, so the completion analysis result should probably not yield anything in this case.

Somewhat related I think https://github.com/rust-lang/rust-analyzer/issues/10410

So ye, I think the proper fix is to somehow recognize this "invalid" position in the completions analysis module.

**Comment by dqkqd** [comment]
> Neither really works I think, the first will fail due to parser recovery, that is once the . is typed in that odd position the parser will probably recover the syntax tree in a weird way such that the check does not work (might be wrong here though).

Yes, here's the ast. Look like it's recovered as a `FieldExpr` with `else` is a error field name.
```
    syntax: SOURCE_FILE@0..38
      FN@0..37
        FN_KW@0..2 "fn"
        WHITESPACE@2..3 " "
        NAME@3..7
          IDENT@3..7 "test"
        PARAM_LIST@7..9
          L_PAREN@7..8 "("
          R_PAREN@8..9 ")"
        WHITESPACE@9..10 " "
        BLOCK_EXPR@10..37
          STMT_LIST@10..37
            L_CURLY@10..11 "{"
            WHITESPACE@11..16 "\n    "
            EXPR_STMT@16..27
              FIELD_EXPR@16..27
                IF_EXPR@16..26
                  IF_KW@16..18 "if"
                  WHITESPACE@18..19 " "
                  LITERAL@19..23
                    TRUE_KW@19..23 "true"
                  WHITESPACE@23..24 " "
                  BLOCK_EXPR@24..26
                    STMT_LIST@24..26
                      L_CURLY@24..25 "{"
                      R_CURLY@25..26 "}"
                DOT@26..27 "."
            WHITESPACE@27..28 " "
            ERROR@28..32
              ELSE_KW@28..32 "else"
            WHITESPACE@32..33 " "
            BLOCK_EXPR@33..35
              STMT_LIST@33..35
                L_CURLY@33..34 "{"
                R_CURLY@34..35 "}"
            WHITESPACE@35..36 "\n"
            R_CURLY@36..37 "}"
      WHITESPACE@37..38 "\n"
    ,
}
```

**Comment by dqkqd** [comment]
So I think It could be fixed by checking if previous child is `IF_EXPR` and next non trivia sibling is `ELSE_KW` wrapped in an `ERROR` node. If that true, we return `None` and don't process further.

I could think of 2 places to plug it in. 

The first one is as you said, inside completion analysis module.
https://github.com/rust-lang/rust-analyzer/blob/8011029d3a0f4014217e1ade75688c0f3c5305db/crates/ide-completion/src/context/analysis.rs#L217-L227

The second one is inside `CompletionContext` constructor
https://github.com/rust-lang/rust-analyzer/blob/8011029d3a0f4014217e1ade75688c0f3c5305db/crates/ide-completion/src/context.rs#L570-L583

How does that sound?

**Comment by Veykril** [comment]
I think the check should happen here actually, https://github.com/rust-lang/rust-analyzer/blob/8011029d3a0f4014217e1ade75688c0f3c5305db/crates/ide-completion/src/context/analysis.rs#L599-L614

(we should land in this place, as completion analysis inserts a fake identifier that will cause us to have a nameref after the `.`)

**Comment by dqkqd** [comment]
Thanks @Veykril, I will prepare a PR for this.
