### ISSUE TITLE
VSCode - Suppress Error Toast

### ISSUE THREAD

**Issue by AThilenius** [rust-lang/rust-analyzer#14193]
Feature request: Add an option to suppress all Rust Analyzer errors from bubbling up to VSCode toasts.

---

Each and every single Rust Analyzer crash results in a toast being displayed in VSCode. Even if you chose to ignore the toast and leave it up, repeat toasts will play an attention-grabbing animation. I love Rust, I love Rust Analyzer, I'm immensely grateful to everyone in the world that made those two possible, but the toasts are like a splinter I just can't ignore. Maybe it's some type of OCD, but it's really painful 🙏 I brought this up in [issue 717](https://github.com/rust-lang/rust-analyzer/issues/717) as well.

## "We should fix the bugs instead"

I get a deluge of popups when I'm trying to `git rebase`. As I would fully expect, git merge conflicts aren't valid Rust and I don't expect (or want) Rust Analyzer to understand them. There are an infinite number of edge cases that fit this description. Process was killed, container was closed, SSH terminated, filesystem is FUBAR... it's impossible to fix every bug. Making the server hardened against crashes is one option (IMO probably not a great option, panics are a good way to report stack traces and handle truly unrecoverable situations 'cleanly'). I don't think fixing every bug is a good substitution for hiding these toasts.

## "We need bug reports"

Microsoft has a [guide on user telemetry](https://code.visualstudio.com/api/extension-guides/telemetry) for VSCode. A few hundred people opted into telemetry is orders of magnitude more useful than hoping someone opens an issue for each of the many error toasts that popup throughout the day, many of which aren't useful because the user knows exactly why the Rust isn't valid. This kind of stuff is largely plug-and-play too, things like Sentry.io can help you filter out non-errors (like trying to parse a git merge conflict).

**Comment by Zeenobit** [comment]
I want to bump this issue because it has been slowly driving me insane lately. Usually whenever I'm developing in [Bevy](https://github.com/bevyengine/bevy) a chunk of my screen space is dedicated to Rust analyzer error notifications that seem to have absolutely no functional effect. I feel like lately it has just been getting worse, but I have no data to back up this claim.

Please give me my screen space and sanity back. 🥲

**Comment by Veykril** [comment]
While adding a button to the error toasts to surpress further ones for the session sounds okay, its still less than ideal that a rebase can cause panics. r-a should ideally never panic no matter what text input it gets fed.

@Zeenobit does this occur to you due to fiddling with the git repo as well, or is it just a thing with your bevy project?

**Comment by Zeenobit** [comment]
For me, it's usually just as I'm editing code. I suspect it may have something to do with lots of macro usage in Bevy, but that's just a guess. I'll try to collect some data and post any findings here.

**Comment by Veykril** [comment]
please report panics like that if you can, the point of this issue is not being able to ignore rust-analyzer from failing.

**Comment by AThilenius** [comment]
> r-a should ideally never panic no matter what text input it gets fed

Not wanting a server (a persistent process) to even panic is a good goal. I think a one-shot process panicking on garbage input is not just reasonable, it's a good design. It communicates error state clearly to a calling process. It happens in every Rust codebase I've ever worked on, often when Rust/Cargo files are in transient nonsensical states from editing.

**BUT I really wan to stress this again, that is NOT what this issue is about.** It is about disruptive error spam in VSCode, which is [against almost every single recommendation Microsoft has on VSCode notification handling](https://code.visualstudio.com/api/ux-guidelines/notifications).

**Comment by Zeenobit** [comment]
> @AThilenius have you actually reported your crash? I know you're saying this issue isn't about that, but before you start claiming that it's impossible to address your annoyance by just fixing the crashes, you could at least try; otherwise it's just a self-fulfilling prophecy.

I think everyone here fully understands that the correct reaction to these errors is fixing them.
This isn't about fixing rust-analyzer errors. This is about using telemetry to report these errors directly to people who are better equipped to do something about it, instead of passing it to the user and hoping they do that manually or try and fix it themselves.

Most people would simply dismiss these errors since it's very difficult (at least for me) to shift one's focus from solving a complicated programming problem to debugging rust-analyzer. So more often than not, the error message just serves to annoy the user and not provide any actual value.

**Comment by Zeenobit** [comment]
I seem to be getting these 2 error notifications when moving/renaming source files and saving `Cargo.toml` mid-edit:

```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file...
```

Followed by:
```
cargo check failed
```

Any edits which invalidate the cargo seem to cause these notifications. Why should these be reported to user as errors? I know the cargo is invalid, I'm in the process of fixing it.

**Comment by AThilenius** [comment]
@Zeenobit said it well.

And yes, I have. Like contributing to [this issue](https://github.com/rust-lang/rust-analyzer/issues/717) which was opened in 2019. But once again... that is NOT what this issue is about. I'm going to keep repeating that ad nauseam 😋

> you could at least try

I have a day job and very limited time to contribute to the open source community, but I contribute where I can (and am offering a PR for this with some guidance). Speaking of Bevy, I wrote the [original transform hierarchy impl Bevy is based on](https://github.com/amethyst/legion_transform) for Legion, and I donate to the project financially. Responses like "don't be lazy and fix it yourself" aren't productive or useful, they will quickly derail this conversation. I'm not lazy, nor am I entitled about open-source. I am human and only have 24 hours in my day.

**Comment by lnicola** [comment]
I think crashes while switching git branches are an old problem and we don't gain much from getting hundreds of reports about it.

**Comment by flodiebold** [comment]
> And yes, I have. Like contributing to https://github.com/rust-lang/rust-analyzer/issues/717 which was opened in 2019. But once again... that is NOT what this issue is about. I'm going to keep repeating that ad nauseam yum

The problem you mentioned in that issue was supposedly fixed 5 days later. Are you saying you're still encountering that crash, even with current rust-analyzer? If so, that would be important to know.

> Responses like "don't be lazy and fix it yourself" aren't productive or useful, they will quickly derail this conversation. I'm not lazy, nor am I entitled about open-source. I am human and only have 24 hours in my day.

I'm sorry for not expressing myself clearly; I meant you could try _reporting_ the issue, not fixing it. I don't expect anyone to spend time trying to fix issues they encounter, I completely understand not having the time for that; but I do expect them to at least report issues they complain about.

**Comment by flodiebold** [comment]
> I seem to be getting these 2 error notifications when moving/renaming source files and saving `Cargo.toml` mid-edit:
> 
> ```
> rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file...
> ```
> 
> Followed by:
> 
> ```
> cargo check failed
> ```
> 
> Any edits which invalidate the cargo seem to cause these notifications. Why should these be reported to user as error _notifications_? I know the cargo is invalid, I'm in the process of fixing it.

Completely agree, these should be displayed as some kind of persistent error state instead of a notification.

**Comment by AThilenius** [comment]
I'm offering a PR to disable repeat errors if someone will help me get a development environment setup/offer guidance, and if the PR will be accepted. I am not offering to be a human telemetry gathering tool. Add telemetry if you need telemetry.

**Comment by Zeenobit** [comment]
> Completely agree, these should be displayed as some kind of persistent error state instead of a notification.

@flodiebold Thing is, we already have this feature:
![xWhzduI](https://user-images.githubusercontent.com/12216742/223219250-8b918f0b-8f52-4aa8-a2fa-e32ac1f037f3.png)
I can get full information just by hovering over that button in VSCode.

But in addition to that, I also get this:
![IDjSR4h](https://user-images.githubusercontent.com/12216742/223219301-da7a7d78-84b1-403e-9ef9-096af1f5de56.png)

**Comment by Zeenobit** [comment]
I also get stuff like this:
![image](https://user-images.githubusercontent.com/12216742/223220826-3f218ac9-4be0-42f0-a01a-587cce2820c4.png)

This is completely valid code. My project compiles and runs ok, but rust-analyzer doesn't seem to like it. Ok, I can live with that.
But then I also get this:
![image](https://user-images.githubusercontent.com/12216742/223220984-f072966a-32f4-4932-84f7-85b26e191d07.png)
Again, I know cargo check is failing. Why am I being notified about it?

**Comment by Veykril** [comment]
Workspace loading failures shouldn't cause a pop given the status bar icon that is indeed a good point. `cargo check` failing I am less sure about as that is a deliberate action that shouldn't fail silently (and as it isn't stateful it has no place to be in the status bar either) so I think that having cause a pop up is okay, as it usually means a configuration problem (and at worst the user can disable checking on save).

**Comment by Zeenobit** [comment]
> Workspace loading failures shouldn't cause a pop given the status bar icon that is indeed a good point. `cargo check` failing I am less sure about as that is a deliberate action that shouldn't fail silently (and as it isn't stateful it has no place to be in the status bar either) so I think that having cause a pop up is okay, as it usually means a configuration problem (and at worst the user can disable checking on save).

To me, if the cargo check is failing due to compiler error, there is no need for a notification. We can see code errors in the Problems tab just fine.

But if the cargo check is failing due to an internal rust-analyzer error (which I think it may be in my case), then that's a perfect candidate for an error that should really be a telemetry event, because the user can't do anything about it at the time unless they drop everything they're doing at that moment to debug or report it. The way it works now is analogous to letting an exception bubble all the way up to UI in a GUI app, which is often not a good user experience.

If we can't differentiate between the different types of `cargo check` failures, then maybe that's a different problem that must be solved first.

**Comment by Veykril** [comment]
> To me, if the cargo check is failing due to compiler error, there is no need for a notification

That's not what this means, if you get that pop up the invocation of cargo check failed, not that there were compiler errors.

> But if the cargo check is failing due to an internal rust-analyzer error (which I think it may be in my case), then that's a perfect candidate for an error that should really be a telemetry event, because the user can't do anything about it at the time unless they drop everything they're doing at that moment to debug or report it

99% of the cases where this cargo check pop up appears its a problem with the users configuration or set up. Telemetry won't help there since it's not in rust-analyzer's hands.

**Comment by AThilenius** [comment]
I'm going to nudge again... what is causing the exceptions isn't germane to this issue.

Could be a software bug in r-a that desperately needs fixing, could be ChatGPT becoming sentient, but it's most likely an issue with the nut that connects my office chair to my keyboard. Doesn't matter, all are out of the scope of this issue. The scope of this issue is: I don't want to see error toasts for Rust Analyzer.

---

Telemetry deserves it's own issue IMO, the value proposition of telemetry is immense.

>99% of the cases where this cargo check pop up appears its a problem with the users configuration or set up. Telemetry won't help there since it's not in rust-analyzer's hands.

Only telemetry can tell you that, otherwise you're just guessing. Maybe it's 98% and a nasty bug is lurking in that 1% that causing user pain. Telemetry can tell you that once you filter out the noise which is a standard feature of all telemetry solutions.

**Comment by griffi-gh** [comment]
Yep, these are annoying and sometimes pop up when i save too fast

**Comment by chenyukang** [comment]
This is annoying!
Even when I use `Do not disturb mode` in VSCode, the notification still comes up.
Status bar is enough for most experienced users to get the current status, if we need to dig into the details we can go to have an investigation on it. 

But most of the time, we don't want to be disturbed in daily workflow.

**Comment by kryptan** [comment]
I get constant "cargo check failed" popups while editing Cargo.toml. What is even their purpose? Like I know that Cargo.toml is invalid while I'm editing it.

**Comment by Veykril** [comment]
Do you have `autosave` enabled?

**Comment by kryptan** [comment]
> Do you have `autosave` enabled?

Yes

**Comment by Veykril** [comment]
Opened https://github.com/rust-lang/rust-analyzer/issues/14453 for that, we shouldn't run cargo check when workspace loading fails

**Comment by hecatia-elegua** [comment]
> I don't want to see error toasts for Rust Analyzer.

isn't there a way to turn off error toasts in vscode? then you can add this as a language-specific setting until it's fixed here

**Comment by dzdrav** [comment]
Is it really that difficult to comprehend users may not want an annoying, repeating notification popping up, interrupting the programming flow, and taking up screen real-estate by covering parts of the terminal?

Every discussion like this derails to "*just report the underlying issue*". The popup being non-hideable, even when after [4 years of issues](https://github.com/microsoft/vscode/issues/46676), MS finally decided to give an option to hide all non-error level popups. RA extensions outsmarts this convenience by emitting an error level popup.

The fact is: this is horrible UX. How could a **non-configurable error toast** that nags the user over and over again, and doesn't give them an option to have peace, **even in Do Not Disturb mode**, because the guiding design principle was from a moral high ground of "users have a right to know", be considered good design?

Please, don't speak for us (users). We want **control** over our tools, not for the tool to **hit us in the face during regular workflow**. If a user already doesn't know his workspace doesn't compile or the `build.rs` script failed, and wants a toast popup about it, that should at least be configurable.

To clarify why this isn't fixable by "just reporting the crash": it's normal part of the workflow for workspace to intermittently be non-buildable, or to open a project that we know has errors. As long as the discussion keeps derailing towards "report why it crashes", it's off-topic and doesn't bring us anywhere closer to the solution.

Is it really that much to ask to **have an option** (not even to disable this completely) to **not** get bombarded in the face with notifications **we don't want**?

**Comment by hecatia-elegua** [comment]
@dzdrav I think the problem isn't that we're all idiots who don't want to improve UX, but that there's only a small amount of contributors. I like @OmarTawfik's idea, but e.g. I don't know how to start implementing this. On the same vein, maybe someone can guide *you* to implement this.

**Comment by Veykril** [comment]
Alright, I did a second pass through things, with #14901 there are only 2 cases where the server itself sends a error/warning pop up request:
- if the server is a dev built or profiling is enabled, overly long loop turns and server panics are reported as pop ups.
- the client does not support the experimental status notification (the status icon in the bottom bar in vscode)

But there is actually a third error pop up that can occur, that is not from a request of the server to the client, but instead when the server responds to a client request with an error (as is the case for panics). VSCode screams at the user in this case that a request has failed, I'll look into whether thats configurable on the client code but if not I would consider that a VSCode "feature" or whatever since that handling is out of our hands. So assuming `Do not disturb mode` does not make VSCode ignore those errors, I'd consider that part a VSCode bug.

**Comment by AThilenius** [comment]
@Veykril Can you TL;DR that for us?

I'm reading it as: 'Language server errors are handled by panicking, vscode displays those as error toasts, and the panic behavior is being marked "won't fix" by the RA team?' It's sounding like we have the answer to this issue then, and it can be closed as "won't fix", or is there a reason to leave it open?

Microsoft has made very clear they won't disable error notifications: https://github.com/microsoft/vscode/issues/41767  This is one of the more Kafkaesk situations I've found myself in with software; both you and Microsoft have valid arguments in isolation, but combined the situation is truly maddening.

**Comment by juliusl** [comment]
@AThilenius

>  kafkaesk situation

I have decided the only real workaround is either sticky notes, or this: 

![image](https://github.com/rust-lang/rust-analyzer/assets/5741075/69083e5b-efcf-43aa-bc04-208920903ec8)

(Double right-click on a relaxing video in Youtube and click on picture-in-picture)

**Comment by jprochazk** [comment]
> But there is actually a third error pop up that can occur, that is not from a request of the server to the client, but instead when the server responds to a client request with an error (as is the case for panics). VSCode screams at the user in this case that a request has failed, ~I'll look into whether thats configurable/hookable on the client code but if not I would consider that a VSCode "feature" or whatever since~ that handling is out of our hands (and I refuse to add a flag to make the server not report errors to the client, raise that problem upstream on the VSCode repo then). Assuming `Do not disturb mode` does not make VSCode ignore LSP request errors, I'd consider that part a VSCode bug.

It turns out this _is_ something that can be hooked into. [Here is the diff](https://github.com/rust-lang/rust-analyzer/compare/master...jprochazk:rust-analyzer:disable-error-notification) for an MVP which suppresses the error notifications completely. I confirmed this works by causing a panic and watching it appear in the output window, but _without sending a notification_. The solution is very barebones, but I'd be happy to work on this further and submit a PR which makes this user-configurable, if it's something that would be likely to get accepted.

Side note: It should be very easy to hook up telemetry on the language client side so that the r-a devs can be notified of _every_ panic, not just the ones reported by users. I would also be more than happy to look into that.

**Comment by AThilenius** [comment]
@jprochazk If you can get a PR merged, my $50 bounty still stands 😁 8 months and 36 comments later, R-A error spam in vscode still drives me insane.

**Comment by chenyukang** [comment]
My solution for this issue is appending this CSS to
`/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css`

```css
.monaco-workbench>.notifications-toasts {
    position: absolute;
    z-index: 1000;
    right: 30px;
    display: none;
    overflow: hidden;
    bottom: -400px;
}
```
The drawback is I need to update it whenever `VsCode` is upgraded 🤔

**Comment by jprochazk** [comment]
@AThilenius please use the money to sponsor r-a development instead 👍
