### ISSUE TITLE
Autocomplete/hover broken in IndexMap with tuple key

### ISSUE THREAD

**Issue by jprochazk** [rust-lang/rust-analyzer#14871]
When hovering over `retain` in the following snippet, rust-analyzer does not display any tooltip.
```rust
use indexmap::IndexMap; // 1.9.3

fn main() {
    let mut map = IndexMap::<(usize, usize), usize>::new();
    map.retain(|_, _| true);
}
```

If the key is changed to just `usize`, it starts working again:
```rust
use indexmap::IndexMap; // 1.9.3

fn main() {
    let mut map = IndexMap::<usize, usize>::new();
    map.retain(|_, _| true);
}
```

`std::collections::HashMap` doesn't seem to have the same issue.

**rust-analyzer version**: rust-analyzer version: 0.3.1524-standalone

**rustc version**: rustc 1.71.0-nightly (77f4f828a 2023-05-20)

**relevant settings**: -

**Comment by lowr** [comment]
This is... not nice. We're now failing to prove trait references for tuples because they are implemented by [this macro][impl-tuple], which contains `${count(x)}` metavariable expression on nightly that we haven't implemented yet (#11952). It was introduced in rust-lang/rust@4d04a062c8660d0fbbceae27a78dba201b9477a1 as part of rust-lang/rust#97594.

We have two options: implement `${count(x)}` asap (before it lands on stable at the very least) or file a PR to revert that commit. I'll look into it in the coming days.

[impl-tuple]: https://github.com/rust-lang/rust/blob/03761a50a3b26daded09e6da79252692c9bbad5f/library/core/src/tuple.rs#L9
