### ISSUE TITLE
No completion inside of macro args

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust-analyzer#15016]
**rust-analyzer version**: rust-analyzer version: 0.4.1545-standalone

**rustc version**: rustc 1.72.0-nightly (101fa903b 2023-06-05)

I have the following code:

```rust
fn main() {
    let x = String::new();
    // write the macros here
}
```
and where the comment is I write something along these lines with each and every macro:

`assert!(x.`<kbd>ctrl</kbd>+<kbd>space</kbd>
and observe whether RA gives a suggestion on the x parameter

| Macro Name | First Parameter | Second Paramter | additional |
|----------------|------------------|--------------------|------------|
| assert | ✅ |  ❌ ||
| assert_eq | ✅ |  ✅ | stops working after second parameter |
| assert_ne | ✅ |  ✅ | stops working after second parameter |
| compile_error|  ❌ | ❌ ||
| dbg | ✅ | ❌ ||
| debug_assert | ✅ | ❌ ||
| debug_assert_eq | ✅ |  ✅ | stops working after second parameter |
| debug_assert_ne | ✅ |  ✅ | stops working after second paremeter |
| env | ❌ | ❌ ||
| eprint | ❌ | ❌ ||
| eprintln | ❌ | ❌ ||
| format | ❌ | ❌ ||
| format_args | ❌ | ❌ ||
| matches | ✅ |  ✅ | stops working after second parameter |
| panic | ❌ | ❌ ||
| print | ❌ | ❌ ||
| println | ❌ | ❌ ||
| todo | ❌ | ❌ ||
| unimplemened | ❌ | ❌ ||
| unreachable | ❌ | ❌ ||
| vec | ❌ | ❌ ||

It's funny that some macros work, while others dont... also somewhat inconsistent i.e. in `dbg!` where the first parameter has suggestion, but the second (and third...) hasn't.

Is this something that can be easily done? Some macros have suggestion, so there must be a codepath for that somewhere.

**Comment by Veykril** [comment]
This is kind of expected, our recovery for macro inputs is not that great yet. We don't pick an ideal matching arm for incorrect inputs yet, and we also do not consider the fragment type of captures to aid in recovery either. 

To answer the question whether this can be easily fixed right now, I'd say not necessarily. Picking a better matching arm for incorrect/partial inputs for macros can be worked on though it's a tough problem. Considering fragment types we are missing the infra for currently.

**Comment by flodiebold** [comment]
For format strings, the format string parameter itself (e.g. first argument of `print!`, second argument of `assert!`, third argument of `assert_eq!`) is expected to not give completions because it needs to be a string literal. All further arguments work if you have the corresponding `{}` in the format string. It used to work without that, but I guess because we made the implementation of `format_args` more realistic now it doesn't anymore. It might be nice to fix that.
That covers most of the cases listed.

`compile_error!`, `env!`: The argument needs to be a string literal, so no completions are expected.
`vec!`: Yeah, this one I couldn't get to work with my older RA either. It's indeed just a matter of failing recovery though, as `vec![s.a<|>]` does give completions.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16060 fixes the format_args family of macros, `vec!` is still broken though
