### ISSUE TITLE
Allow creation (or more feedback) when attempting to create a nested module

### ISSUE THREAD

**Issue by schneems** [rust-lang/rust-analyzer#15055]
Currently you can use quickfix to create a module file:

<img width="1136" alt="Screenshot 2023-06-14 at 4 13 51 PM" src="https://github.com/rust-lang/rust-analyzer/assets/59744/f399f4fe-6be9-45aa-abbf-f95fd1caed8e">

But not if there are nested modules:

<img width="1136" alt="Screenshot 2023-06-14 at 4 15 22 PM" src="https://github.com/rust-lang/rust-analyzer/assets/59744/059551be-5390-4eb1-9576-032f7f8741ff">

It would be great to be able to either create the whole chain or if it's too ambiguous maybe give some feedback (somehow?) like "The `lol` module does not exist. Cannot create `lol::haha`. Please create `lol` before creating `lol::haha`"

This came up in a conversation on my blog post that uses rust-analyzer to teach how the module system interacts with files https://lobste.rs/s/e3lj0p/it_s_dangerous_go_alone_pub_mod_use_this_rs#c_7kz26f.

**Comment by matklad** [comment]
Not sure if we should do this. `mod foo::bar` isn’t a valid *syntax*, so the problem here is much shallower than “can’t create nested modules”, it’s that `mod foo::bar` isn’t a thing in Rust.

pracitclaly, yeah, type `mod foo;`, press cmd+., create module (this’ll focus the editor in the new file), type `mod bar;`, press cmd+. again.
