### ISSUE TITLE
Allow configuring the default action of the status bar click action in VSCode

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#15441]
cc https://github.com/rust-lang/rust-analyzer/pull/15391

**Comment by dfireBird** [comment]
I have got two questions regarding this:
1. On the latest VSCode (1.82.2), I couldn't see rust-analyzer extension's status bar icon. Is that disabled because of a VSCode upgrade or is it just my system?
2. For the configuration, does naming the property something like this works: `rust-analyzer.statusBarAction` or `rust-analyzer.statusBar.action`?

**Comment by Veykril** [comment]
1. The extension doesn't enable itself unless a Cargo.toml or rust file is opened, so you won;t see it until then.

2. I'd say something like `rust-analyzer.statusBar.defaultClickAction` is the most descriptive here

**Comment by dfireBird** [comment]
> The extension doesn't enable itself unless a Cargo.toml or rust file is opened, so you won;t see it until then.

My bad, I have somehow disabled the status bar for Rust Analyzer Extension. I have now found the way.

> I'd say something like rust-analyzer.statusBar.defaultClickAction is the most descriptive here

IMO `defaultClickAction` suggests the click action will change depending on the context but the default click action is given by the setting.
