### ISSUE TITLE
how to fix error on c

### ISSUE THREAD

**Issue by getchard** [rust-lang/rust-analyzer#15624]
Thats my code:

#include <stdio.h>
#include <math.h>

int main() {
    double bigger_radius, smaller_radius, area;

    printf("Enter the bigger radius: ");
    scanf("%lf", &bigger_radius);

    printf("Enter the smaller radius: ");
    scanf("%lf", &smaller_radius);

    if (bigger_radius <= smaller_radius) {
        printf("Error: The bigger radius must be larger than the smaller radius.\n");
        return 1;
    }

    area = 3.14 * (bigger_radius * bigger_radius - smaller_radius * smaller_radius);

    printf("The area of the ring is: %.2lf square units\n", area);

    return 0;
}

and as output i get 
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../libmingw32.a(main.o):(.text.startup+0xa0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status

**Comment by lnicola** [comment]
Not sure which IDE you're using, but in Visual Studio you'd have to make a new project and choose Console instead of Win32 Application (or change the subsystem in the linker settings).

You're using a different compiler, but the main issue is most likely the same. Feel free to use a search engine.

In any case, this repository has to do with a completely different language (Rust). There's no point in asking about C here.

**Comment by getchard** [comment]
i solved a problem, i forgot save the code and i was running empty code
