### ISSUE TITLE
[Since 0.4.1658] Cannot rename a non-local definition.

### ISSUE THREAD

**Issue by Sewer56** [rust-lang/rust-analyzer#15656]
# System Details

**rust-analyzer version**: 0.3.1665-standalone (first broken stable version)
**rustc version**: rustc 1.72.1 (d5c2e9c34 2023-09-13)

## Details

Since `v0.4.1658-standalone` it is not possible to rename any item inside one of my projects. More details in [reproduction](#reproduction) section.

## Regression

Broken since `v0.4.1658-standalone` (nightly). Earlier versions work as expected.

------

1658 (first broken ver.):
Actions Run:  https://github.com/rust-lang/rust-analyzer/actions/runs/6153193088
Commit: https://github.com/rust-lang/rust-analyzer/commit/cc6c8209cbaf7df55013977cf5cc8488d6b7ff1c

1655 (previous functional release): 
Commit: https://github.com/rust-lang/rust-analyzer/commit/994df3d6a31d39f11600f30a6df0b744b13937c1

------

I believe this was introduced in https://github.com/rust-lang/rust-analyzer/pull/15232 . 
However probably not directly caused by said commit (the commit seems to restrict needed functionality), but an unexpected edge case where a local item is believed to be non-local.

## Reproduction

I have tried to create a minimal reproduction, however did not succeed in creating a minimal repro (I even tried copying dependency structure and workspace code settings). 

So I am forced to instead link to one of my real [WIP] projects.

Reproduction Steps:
- Clone `https://github.com/Reloaded-Project/Reloaded.Hooks-rs.git`
- Checkout `main`
- Open main folder in VSCode (folder with README.MD)
  - Note: Projects are included via `.vscode/settings.json` -> `rust-analyzer.linkedProjects`.
- Open any file in `reloaded-hooks-portable` such as `projects/reloaded-hooks-portable/src/api/wrapper_instruction_generator.rs`.

It is not possible to rename any type or even local variable due to:

```
[Error - 03:04:27] Request textDocument/rename failed.
  Message: Cannot rename a non-local definition.
  Code: -32602
```

**Comment by alibektas** [comment]
I tried to emulate the given situation using our test infra and it worked just fine. 
The difference that is important for us is the value of `CrateOrigin` for the project we are linking. 

https://github.com/rust-lang/rust-analyzer/blob/e5e937ae5eafe38b995e26f0e6c4f1035d52a313/crates/base-db/src/input.rs#L143-L152

While testing the project is correctly recognized as a `Local` whereas in the reported case it is being seen as a `Library { repo: Some("https://github.com/Reloaded-Project/reloaded-hooks"), name: "reloaded-hooks-portable" }`. At this point maybe a second opinion would  be nice @Veykril. Here is [my local branch](https://github.com/alibektas/rust-analyzer/tree/15656/linked_projects_are_local_too) where the test is at.

**Comment by alibektas** [comment]
OK after days and days of looking into this I finally managed to find the root cause of this. We use a graph to represent how crates within a project relate to one another. With #15232 we forbade renaming of non-local items which means that if a crate's origin 

https://github.com/rust-lang/rust-analyzer/blob/f19479a2ad238ad861cfe8d57e63beeccb56169e/crates/base-db/src/input.rs#L143-L152

is something else other `Local` we cannot allow renaming to take place. The given example uses `linkedProjects`. This will create a "healthy" crate graph.

```mermaid
flowchart TB
    ProjectRoot -- CrateOrigin::Local --> Foo
    ProjectRoot -- CrateOrigin::Local --> Bar
```

The trouble starts when `Foo` depends on `Bar` ( Following the repro foo is `reloaded-hooks-x86-sys` and Bar is `reloaded-hooks-portable`  . This will cause `Bar` to be of `CrateOrigin::Library` from Foo's perspective. This would have been OK had the `linkedProjects` not already registered `Bar` as `CrateOrigin::Local`. So now we have something like

```mermaid
flowchart TB
    ProjectRoot -- CrateOrigin::Local --> Foo
    ProjectRoot -- CrateOrigin::Local --> Bar
    Foo -- CrateOrigin::Library --> BarAsLib
```

Or in simplified terms :

```mermaid
flowchart TB
    ProjectRoot -- CrateOrigin::Local --> Foo
    ProjectRoot -- CrateOrigin::Local --> Bar
    Foo -- CrateOrigin::Library --> Bar
```

So resolving this issue will entail changes in `CrateGraph` which may/may not be easy. I think until then we can revert change from #15232 . 

Here's a [test case](https://github.com/alibektas/rust-analyzer/blob/90011bdc946a453b3627974677108343a3fb2dcf/crates/rust-analyzer/tests/slow-tests/main.rs#L1135-L1209) where you can find a minimal repro.

**Comment by Veykril** [comment]
Ah, that would explain that indeed. I think your merged crate graph in your examples is wrong though no? I would expect us to actually have two `Bar` crates in the graph, as origin is part of the crate data and it differing means we don't deduplicate the crate. This kind of duplication trips up a lot of things in general, I'm not sure what the best approach to take here is though.

**Comment by alibektas** [comment]
It is indeed wrong but the whole point was to show that `Bar` and `BarAsLib` are actually one and the same crate ( for the user ). I think we should revert #15232 for now until we have a solution to this.

**Comment by Veykril** [comment]
I think we should instead take a look at `CrateOrigin` and check if the current split of things makes sense. That is, cargo assigns `is_local` and `is_member` as properties to crates in a workspace, we use `CrateOrigin::Local` to mean member really. Now I don't remember what `is_local` implies for cargo but it might make sense to change stuff here depending on what it means.

Also, the duplicated crates only differ in the `CrateOrigin`, so it might make sense to consider the origin when deduplicating and when only the origin differs, try to deduplicate by merging the origin into the more sensible option. So in this case, keeping the local origin copy, and discarding the library one etc. But again, that depends on what the `Local` crate origin is being used for right now by other features. (A clear case of documentation on `CrateOrigin` and its variants is missing/not descriptive enough)

**Comment by Zalathar** [comment]
Ah, this issue might be why Rename Symbol no longer works on local variables in some rustc crates.

**Comment by Zalathar** [comment]
I've confirmed that reverting to 0.3.1657 allows Rename Symbol to work in `rustc_mir_transform`.

**Comment by alibektas** [comment]
So first of all sorry for taking so much time I was sick for a week. I have addressed the reasons behind this issue and my PR solves most of them. The project given as a repro however will still not be able use renaming. I will address them in a following PR.
But let me mention why it currently remains unresolved.

As I mentioned before we deal with multiple occurrences of the same crate and the dedup rules were until now too strict ( two crates must be equal to be merged into one but this is not possible in the given example, see comment above) . After I relaxed the conditions for merging I saw that there are inconsistencies in versions of one crate "hashbrown" in the given repro ( see metadata for both reloaded_hooks_{portable,x86_sys} @Sewer56 ). But I couldn't have relaxed the condition to say if one project has a dependency that has a different version than its other occurrence then merge them anyway. So this still needs to be addressed somehow but until then my current PR aims to solve the majority of cases.

**Comment by Veykril** [comment]
There is nothing to address in that case (aside from our PR relaxing things in regards to the origin), the root of the problem is that the crate that is being loaded in the linked projects while also being loaded as a dependency of another is subject to different `Cargo.lock` files. This makes it inherently impossible for rust-analyzer to dedup the crate if dependencies of said crate have differing versions in the respective lock files. As such, the project should either take care of trying to sync the lock files or only add the cargo workspace to the linked projects that contains the other crate in its dep graph as well as that will be effectively loaded due to that anyways.

The only thing that we should be looking into is recognizing this, and somehow inform the user that this kind of set up *can* cause IDE features like renaming to fail. Although I think there is a bug here in how we assign CrateOrigin's still / how we forbid renaming as well. The crates in question where renaming fails here are still inside the project folders (presumably via `path` dependencies) in which case we shouldn't forbid renames in the first place I think, since those are technically fine to modify. We only want to prevent the std lib sources and crates.io sources from being modified.

**Comment by ogapo** [comment]
"The crates in question where renaming fails here are still inside the project folders (presumably via path dependencies) in which case we shouldn't forbid renames in the first place I think, since those are technically fine to modify."

I've just recently run into this issue (using v0.3.1713) when using multi-root Workspaces and with submodules declared between them via `path`. I'm not entirely certain what is causing it to trigger (I wasn't able to make a minimum repro project yet) but it would be really nice if there was an escape-hatch setting to simply disable this check and allow renaming "non-local" defs if opted in for complex projects?

**Comment by alibektas** [comment]
:wave: We use configurations to customize behavior, in your case your request is more of a workaround kind. Although practically this could work, we'd rather see a solution that resolves this issue once and for all. We still couldn't merge the PR upstream so until then ( merged version will probably be available in nightly between 13.11-17.11) you could do two things 

1. Go back to the commit where the breaking changes were first introduced ( see [here](https://github.com/rust-lang/rust-analyzer/pull/15232 )

Or 

https://github.com/rust-lang/rust-analyzer/blob/c1c9e10f72ffd2e829d20ff1439ff49c2e121731/crates/ide-db/src/rename.rs#L78-L82

delete lines 79-82 and build the project using the command `cargo xtask install`. 

Sorry if you couldn't find the answer you were looking for.

**Comment by ogapo** [comment]
Thanks for the instructions!
 
I went ahead and took a crack at a fix. I believe the correct course might be to relax the definition of `CrateOrigin::is_local` to include libraries which do not have a repo specified. Since we can't know who the code at that path belongs to really, best to err on the conservative side. I had a look at all the current callsites and they seem to be using it to mean "is possibly user code". It may be worth renaming `is_local` to `is_possibly_user_code` or something like that to convey what it really means (especially with the behavior change I'm proposing). 

```rust
impl CrateOrigin {
    pub fn is_local(&self) -> bool {
        match self {
            Self::Local { .. } => true,
            Self::Library { repo, .. } => repo.is_none(),
            _ => false,
        }
    }
}
```

This change fixes my project. I am able to rename things in the cross-referenced crates but it still fails if I try to rename a symbol inside `std` and also fails if I try to rename something inside a regular crates.io dependency (I tried with `tokio`).

I made a PR here https://github.com/ogapo/rust-analyzer/pull/1. I wasn't sure enough about the change to want to PR against this repo (happy to do so if you recommend though).  The change is small though, so might be better to be incorporated into PR #15754

**Comment by alibektas** [comment]
> Thanks for the instructions!
> 
> I went ahead and took a crack at a fix. I believe the correct course might be to relax the definition of `CrateOrigin::is_local` to include libraries which do not have a repo specified. Since we can't know who the code at that path belongs to really, best to err on the conservative side. I had a look at all the current callsites and they seem to be using it to mean "is possibly user code". It may be worth renaming `is_local` to `is_possibly_user_code` or something like that to convey what it really means (especially with the behavior change I'm proposing).
> 
> ```rust
> impl CrateOrigin {
>     pub fn is_local(&self) -> bool {
>         match self {
>             Self::Local { .. } => true,
>             Self::Library { repo, .. } => repo.is_none(),
>             _ => false,
>         }
>     }
> }
> ```
> 
> This change fixes my project. I am able to rename things in the cross-referenced crates but it still fails if I try to rename a symbol inside `std` and also fails if I try to rename something inside a regular crates.io dependency (I tried with `tokio`).
> 
> I made a PR here [ogapo#1](https://github.com/ogapo/rust-analyzer/pull/1). I wasn't sure enough about the change to want to PR against this repo (happy to do so if you recommend though). The change is small though, so might be better to be incorporated into PR #15754

:wave: Thank you for your answer @ogapo . We were planning to make some changes to how we determine `CrateOrigin`. Let me get back to you in a couple of weeks once I got some time to work on this and I am personally in favor of you making a PR ( assuming that you would like to contribute to the project yourself. )

**Comment by TCROC** [comment]
I have also recently started experiencing this issue in one of the recent updates.

```
rust-analyzer version: 0.3.1730-standalone
rustc 1.73.0 (cc66ad468 2023-10-03)
```

**Comment by Zalathar** [comment]
Unfortunately I may have celebrated too soon.

Renaming does work in `rustc_mir_transform`, but it still doesn't work in `rustc_mir_build`.

Perhaps that crate triggers one of the more complicated scenarios not fixed by #15754.

**Comment by TCROC** [comment]
It is also not working in my crates

**Comment by Veykril** [comment]
That things break down in the rustc workspace is not too surprising to me, the workspace is cursed and r-a barely work in it in the first place.

@TCROC is your project public? Or can you figure out what project structure it is that still breaks here?

**Comment by shepmaster** [comment]
> is your project public

The playground is public and experiencing this problem. To reproduce:

1. Check out https://github.com/rust-lang/rust-playground at f14e3a889d68828c4dd8c91138b1c42d1abfd35a
2. Open `compiler/base/orchestrator/src/coordinator.rs`
3. Attempt to rename `AssemblyFlavor` to `AssemblyFlavor2` (defined on line 39)

I'm using `rust-analyzer 0.0.0 (c7c582afb5 2023-11-28)` on aarch64-apple-darwin via emacs.

I haven't taken any time to produce a minimal test case, however.

**Comment by TCROC** [comment]
Ok so starting up my projects in a brand new session, things are working correctly.  I swear I was getting this error yesterday though.  I'll spend some time developing this week and see if it reappears.

**Comment by Veykril** [comment]
> Ok so starting up my projects in a brand new session, things are working correctly. I swear I was getting this error yesterday though. I'll spend some time developing this week and see if it reappears.

You mightve been still using the old version. VSCode updates the extensions after startup, so you need to reload the window once to actually run the new version.

@shepmaster thanks, that should suffice to figure it out.

**Comment by shepmaster** [comment]
This appears to be a minimized case:

```
compiler/orchestrator/Cargo.toml
compiler/orchestrator/src/lib.rs
ui/Cargo.toml
ui/src/main.rs
```

**compiler/orchestrator/Cargo.toml**

```toml
[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
```

**compiler/orchestrator/src/lib.rs**

```rust
struct AssemblyFlavor;
```

**ui/Cargo.toml**

```toml
[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
orchestrator = { path = "../compiler/orchestrator" }
```

**ui/src/main.rs**

```rust
fn main() {}
```

This should be [an archive of those files](https://github.com/rust-lang/rust-analyzer/files/13503747/repro.zip)

**Comment by TCROC** [comment]
@shepmaster @Veykril I was also able to reproduce this using the archive provided by @shepmaster 

![image](https://github.com/rust-lang/rust-analyzer/assets/24307049/d0856c61-94fe-4d54-bf5e-a9ce27d377da)

**Comment by Veykril** [comment]
Ah, I can tell you why this fails (and why it works fine if the `orchestrator` is moved one level up). The project structure as is means that we only load the `ui` crate, but not the `orchestrator` (because it is too deep, we only scan the root and first level for cargo projects), so the `orchestrator` is considered non local as its not inside the workspace of `ui` (we might be able to cheat around a bit by respecting a crate's position to the opened VSCode/LSP workspace root as well as any cargo workspaces). OTOH if you lift the `orchestrator` up one level we now load it as a cargo workspace as well, where the deduplication fix kicks in, making it just work.

**Comment by shepmaster** [comment]
> The project structure as is

In my real project, the deeper organization is (sadly) somewhat required as I have to move things around to build Docker containers without pulling in too much junk (and not writing huge .dockerignore files) but including just the right things.

> scan the root and first level

Ah, I gotcha! That also suggests a workaround in my case: I can manually add the `orchestrator` directory as a separate lsp-mode workspace. That way a separate rust-analyzer will be started there.

It's sad that I'll lose cross-crate renaming, but perhaps that's an indication that I really should make these into a workspace. I don't recall why they aren't currently, perhaps some more weirdness about how things get built in Docker.

---

Is there a way to indicate to rust-analyzer that a group of projects should be loaded, instead of it scanning?

**Comment by Veykril** [comment]
There is a `linkedProjects` setting which overwrites the scanning behavior

**Comment by ogapo** [comment]
@Veykril Just curious, does the deduplication fix play well with VSCode multi-root workspaces? 

Also will we still be able to refactor 3rd party modules we've got a local checkout of (overriding via .cargo/config.toml for instance)? That's a fairly common workflow for working on forks of other projects you've found a bug in and wish to contribute to (at least for me).

I'm curious why we wouldn't just consider everything imported by path as potentially user code?

**Comment by eggyal** [comment]
I also wonder whether the approach of building distinct crate graphs for each project workspace (that are then subsequently merged) makes this all quite a bit more difficult, and RA wouldn't be better building a singular crate graph from the outset?  In particular, I see duplication in sysroot and rustc_private crates that cause cascading failures to deduplicate downstream crates due to dependency mismatch (though correctly deduplicating these during merge should be able to address that concern).

**Comment by TCROC** [comment]
[refactor-broken-example.zip](https://github.com/rust-lang/rust-analyzer/files/13520868/refactor-broken-example.zip)

Ok so I figured out how to reproduce this issue in minimized environments.  There are 2 ways to cause it.  Below are my findings:

## Linking against 2 proc macros

![image](https://github.com/rust-lang/rust-analyzer/assets/24307049/424e2905-2320-4e15-bed9-80a64c63383f)

The interesting thing is that in this case, only the 2nd proc macro crate breaks and doesn't allow renaming vars:

### example1-macros ✅
![image](https://github.com/rust-lang/rust-analyzer/assets/24307049/256d99c3-6b92-4dfc-8281-fc63a4a019ea)

### example2-macros ❌

 
![image](https://github.com/rust-lang/rust-analyzer/assets/24307049/78a61f6a-e309-4a89-87e9-ca0c02b0a2fb)

And it seems to be directly correlated to the order of the projects that make use of the macros.  If I rearrange the linked project settings to be like so:

```json
{
    "rust-analyzer.linkedProjects": [
        "example2/example2/Cargo.toml",
        "example1/example1/Cargo.toml",
        "example2/example2-macros/Cargo.toml",
        "example1/example1-macros/Cargo.toml",
    ],
}
```

with the example2 being before example1, example2 will work and example1 will break.  The order of the macro projects does not seem to matter, but the order of the project that references the macro project seems to break it.

So if I switched these 2:

```json
        "example1/example1/Cargo.toml",
        "example2/example2/Cargo.toml",
```

To be:

```json
        "example2/example2/Cargo.toml",
        "example1/example1/Cargo.toml",
```

Then example 2 will work and example 1 will break.

## [bitvec](https://docs.rs/bitvec/latest/bitvec/)

Adding a reference to the bitvec crate in example1 or example2 seems to break refactoring in any procedural macro crates.  This can be seen in example1/Cargo.toml.  Uncomment the ``# bitvec = "1.0.1"`` and you will notice that you can no longer refactor things in example1-macros and start getting the "Cannot rename a non-local definition." error.

I attached an archive of the project to reproduce on your machines.  Let me know if you guys have any questions and / or need anything else from me.

Thanks again everyone!  Ur all beautiful human beings and Merry Christmas! ♥️

**Comment by alibektas** [comment]
So finally I found the reason which is a little peculiar. It is that we have for the "proc_macro2" crate different `<Self  as CrateData>.env["OUT_DIR"]` values each time a new workspace is detected but for the deduplication we had previously assumed a one to one overlap of all `Env` hashes. When I relax this condition such that `OUT_DIR` plays no further role the issue is resolved. But before opening a PR I wanted to make sure that nothing speaks against it. 

As to testing : Since the said crate is an external crate collecting metadata and `extend`ing them will not let use detect this error, same goes for the current `slow-tests` infra ( In both situations the error was undetected ). So any suggestions regarding a test case wouldn't be so bad either

**Comment by TCROC** [comment]
@alibektas Great find!  Do you have a link to your branch / fork with this fix?  I would be curious to see :)

**Comment by alibektas** [comment]
Sure let me wrap things up and post the link here

**Comment by alibektas** [comment]
[Link](https://github.com/alibektas/rust-analyzer/tree/15656/proc_macro_dedup_nodbg) but mind you that I didn't thoroughly check all the possible configurations yet so it wouldn't be a surprise if you find some things missing.

**Comment by TCROC** [comment]
@alibektas I'm not a maintainer so I'm not familiar with the codebase at all, but looks like it was a really sneaky bug!  Looks like a simple enough fix from the surface level :)

I'll be curious to see what others think as well!  (Looks good to me tho! 😉)

I'll take a sec to learn how to build ra from source and test on my main project as well to see if it fixes it :)

**Comment by Veykril** [comment]
> So finally I found the reason which is a little peculiar. It is that we have for the "proc_macro2" crate different `<Self as CrateData>.env["OUT_DIR"]` values each time a new workspace is detected but for the deduplication we had previously assumed a one to one overlap of all `Env` hashes. When I relax this condition such that `OUT_DIR` plays no further role the issue is resolved. But before opening a PR I wanted to make sure that nothing speaks against it.
> 
> As to testing : Since the said crate is an external crate collecting metadata and `extend`ing them will not let use detect this error, same goes for the current `slow-tests` infra ( In both situations the error was undetected ). So any suggestions regarding a test case wouldn't be so bad either

Ugh, ye that is annoying... We can't really deduplicate these crates, since the out dirs *should* point into the respective target dirs here. Deduplicating might just work for one crate, but another might break because it now no longer finds its corresponding output.

**Comment by Veykril** [comment]
I think we might just wanna put the accidental library rename prevention behind a config and tell the user in the error message that they can disable it by setting "<config-key>" to false. As I don't see a way to fix this concrete case here (though I am open for ideas), and I know that a bunch of people are annoyed by this issue. (Though at least we managed to push deduplication further thanks to this so thats a net win anyways)

**Comment by Veykril** [comment]
The problem is that the LSP Root directory can be completely unrelated to the workspaces, you can open a workspace in `/foo/bar` and `/foo/baz` but have the LSP root be in `/qux/other`. (An example with vscode being you open a vscode workspace, then you proceed to add random folders as workspace members that are unrelated to the opened workspace).

**Comment by Veykril** [comment]
One thing we should change still though is to treat `path` included dependencies as renamable (as was stated somewhere earlier), it doesn't really make sense to treat them as foreign.

**Comment by flodiebold** [comment]
> An example with vscode being you open a vscode workspace, then you proceed to add random folders (cargo workspaces) as workspace members that are unrelated to the opened workspace.

What would be the problem with that though? I mean, we should allow renaming in all workspace folders of course. But to me it still seems like the VSCode workspace == the set of folders where the user wants to make changes.

**Comment by flodiebold** [comment]
I think that's what I'm saying, yes :sweat_smile: It just fundamentally doesn't make sense to me that we could consider only one version of a crate in a specific folder local and the other not, it should be purely a property of the folder they're in.

**Comment by TCROC** [comment]
> One thing we should change still though is to treat `path` included dependencies as renameable (as was stated somewhere earlier), it doesn't really make sense to treat them as foreign.

Do you mean like ``"rust-analyzer.linkedProjects"`` that are explicitly configured in the ``settings.json``?  If so, I agree.  At the very least, those should be renameable since the developer has explicitly told ra these are the projects I am actively working on.  I have control over them.

At least that's how I interpreted that setting.

**Comment by Veykril** [comment]
Yes, all discovered and loaded projects, whether explicitly set via `linkedProjects` or implicitly loaded.

**Comment by vaniusrb** [comment]
First of all, I would like to say that I am very grateful for this amazing project. I'm aware it has a very complex codebase. 

I don't remember a single occasion where I accidentally renamed an item that wasn't in my project. Now I can't rename anything anymore. This is affecting our workflow. While we don't have a bug fix, is it possible to create a configuration to not do this rename check?

**Comment by TCROC** [comment]
I agree with @vaniusrb.  This has also been quite detrimental to our workflow.  We fine most of our refactoring now consists of "ctrl + f" and "replace" which is less than ideal and prone to errors.

**Comment by alibektas** [comment]
Adding a config was in my TODO list, let me work on it now and get back to you in a few hours. Sorry for the inconvenience!

**Comment by TCROC** [comment]
Thank you @alibektas! :)  No sorries necessary! :)

**Comment by alibektas** [comment]
> First of all, I would like to say that I am very grateful for this amazing project. I'm aware it has a very complex codebase.
> 
> I don't remember a single occasion where I accidentally renamed an item that wasn't in my project. Now I can't rename anything anymore. This is affecting our workflow. While we don't have a bug fix, is it possible to create a configuration to not do this rename check?

So if everything goes well :crossed_fingers:  with today's nightly this config should be available. You will just need to set the following config to "true", we defaulted it to "false" to make the feature visible to users, as it works just fine for most of the time. Here is the related piece in the documentation

```adoc
[[rust-analyzer.rename.allowExternalItems]]rust-analyzer.rename.allowExternalItems (default: `false`)::
+
--
Allow renaming of items not belonging to the loaded workspaces.
--
```

**Comment by alibektas** [comment]
heads up @TCROC @vaniusrb

**Comment by TCROC** [comment]
@alibektas will I be able to test it out in the vs code pre-release version? 

![image](https://github.com/rust-lang/rust-analyzer/assets/24307049/617cc37f-fbab-43df-8fc3-5660b138b040)

Or what is the best way to test it?

**Comment by alibektas** [comment]
Honestly I have always built from the source by running just `cargo xtask install` but I believe you are right with pre-release. In fact if you go to the extension tab and right click on rust-analyzer you can see that the version with the same version number (0.4.1810)  has a `20 hours ago` mark next to it.

**Comment by TCROC** [comment]
@alibektas first initial test seems to indicate that its working! :)  I'm going to try it for a bit and see if I run into any issues with it! :)

**Comment by vaniusrb** [comment]
Hi, @alibektas! I just tried. It worked like a charm! I'm proud of you and this community. Thank you very much.
