### ISSUE TITLE
Documentation of useRustcErrorCode is useless

### ISSUE THREAD

**Issue by Ten0** [rust-lang/rust-analyzer#15666]
https://github.com/rust-lang/rust-analyzer/blob/d3cc3bc00e310ff49268ce0c593eaa6bf4724bbd/editors/code/package.json#L470

Does not provide any information about what effect enabling this option might have. It merely repeats the option name, which is useless.

**Comment by veber-alex** [comment]
Enabling this option causes rust-analyzer to report errors from rustc (cargo check) using the original rustc error code.

For example having an unused variable will report a warning with the code `rustc(unused_variables)`.
With this setting disabled all warnings and errors will be reported with the code `rustc(Click for full compiler diagnostics)`.

I added this setting because without it it's not possible to filter the errors and warnings you get from rust-analyzer, my use case was to hide some warnings in the error lens vscode extension which can be done by error code.

How about "Whether to show diagnostics using the original rustc error codes".

**Comment by Ten0** [comment]
Thanks for this explanation, I think I understand the effect now (or where I should look to find it at least). I think it's also useful to have the "if false" section in the explanation.
