### ISSUE TITLE
The formatter added unessesary brackets.

### ISSUE THREAD

**Issue by pointertobios** [rust-lang/rust-analyzer#15751]
As this image:
![img](https://github.com/rust-lang/rust-analyzer/assets/84652600/07708cfd-4f22-47e3-88d0-f5ed5805bb03)
the formatter always add `()` around in this case.

**Comment by lnicola** [comment]
Which formatter is that? Do they get added when you save the file, expand a macro, or something else?

**Comment by pointertobios** [comment]
I didnt install any extra formatter. as welll as I installed rust-analyzer for vscode it works.
Only when I type the formatting shortcut did.
And I didnt open format-on-save.

**Comment by lnicola** [comment]
Can't reproduce either:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/1ce302db-e1c5-4681-967a-4eb2a703bb1e)

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/4287d5c0-b0bc-47d8-8666-ed47017e0657)

Are you running the `rustup` version or some old binary? Or maybe you have an old toolchain where `rustfmt` does this? What happens if you run `cargo fmt` on your project?

**Comment by lnicola** [comment]
Gentle ping @pointertobios.

**Comment by pointertobios** [comment]
I found it's `cargo fmt` that adds it.
Thank you for caring for my problem!
