### ISSUE TITLE
miss a method to access all `PathType` in `PathSegment`

### ISSUE THREAD

**Issue by Young-Flash** [rust-lang/rust-analyzer#15778]
There are only [`pub fn path_type(&self) -> Option<PathType>`](https://github.com/rust-lang/rust-analyzer/blob/d6afb4fa239fe7b5b34e5cefa9e58148fdff65b8/crates/syntax/src/ast/generated/nodes.rs#L62) for `PathSegment`, which only return the first `PathType`, but there maybe more than one `PathType` in a `PathSegment`, take `<i32 as std::ops::Add>` for example, the AST of it is as the following:
```txt
PATH_SEGMENT@48..70
  L_ANGLE@48..49 "<"
  PATH_TYPE@49..52
    ... // i32
  WHITESPACE@52..53 " "
  AS_KW@53..55 "as"
  WHITESPACE@55..56 " "
  PATH_TYPE@56..69
    ... // std::ops::Add
  R_ANGLE@69..70 ">"
```

So I think there can make a `pub fn path_types(&self) -> Vec<PathType> { support::children(&self.syntax).collect() }` for `PathSegment` to access all `PathType`.

**Comment by Veykril** [comment]
Interesting, our grammar is also wrong here https://github.com/rust-lang/rust-analyzer/blob/d6afb4fa239fe7b5b34e5cefa9e58148fdff65b8/crates/syntax/rust.ungram#L39
That should be
```
| '<' Type ('as' PathType)? '>'
```

and then we should implement the path type accessor manually given the potential overlap, somewhat similar to https://github.com/rust-lang/rust-analyzer/blob/d6afb4fa239fe7b5b34e5cefa9e58148fdff65b8/crates/syntax/src/ast/node_ext.rs#L332-L362

**Comment by Veykril** [comment]
The parser already parses a `Type` instead of a `PathType`, so it's just that the grammar is wrong which we need to fix up. The reason why we can't just make a `path_type` accessor like you say is that the `Type` in in the grammar rule *could* be a `PathType` as well, in which case the `path_type` accessor will yield the wrong one. That's why that special handling is required.
