### ISSUE TITLE
Offer "Extract variable" assist for statements

### ISSUE THREAD

**Issue by Young-Flash** [rust-lang/rust-analyzer#15796]
There is a useful feature in Jetbrain IDEA, which is automatically bind a variable for an expression by a keyboard shotcut (ctrl + alt + v), showing below:

![auto_binding](https://github.com/rust-lang/rust-analyzer/assets/71162630/abef7e21-f4bd-4c38-b453-dbe831ce3e5f)

I think it would be wonderful if rust analyzer have a an feature (maybe impl via a assist💡), I'd like to make a PR if it's ok with rust analyzer team.

**Comment by lnicola** [comment]
Did you see the "Extract into variable" assist?

**Comment by Young-Flash** [comment]
seems not avaiable for the following case, am I miss something?

![image](https://github.com/rust-lang/rust-analyzer/assets/71162630/280219a2-9987-4550-a800-96055d10cc1d)

**Comment by lnicola** [comment]
Try selecting it.

**Comment by Young-Flash** [comment]
I got it. 

It require manually select the code range, can't trigger when the cursor in the line end. May be we can refactor this?

And, can it bind with a keyboard shorcut? It's much convenient.

**Comment by lnicola** [comment]
It might be a good idea to offer it when the statement is a single function/method call (and the return type is not `()`?).

I don't think you can bind a specific assist to a shortcut, but `Ctrl-.` will open the assists menu, and a second `Ctrl-.` will invoke the first one, which in this case is "extract into variable", which seems easy enough.

**Comment by Young-Flash** [comment]
> It might be a good idea to offer it when the statement is a single function/method call (and the return type is not ()?).

yeah, I'd try

**Comment by rsalmei** [comment]
A curiosity @lnicola, please:
Is this "assist" popup always the "Refactor..." context menu? I did a few tests triggering them both in some places like the start and end of a line, as well as selecting it, and they seemed identical.

**Comment by lnicola** [comment]
- this assist is always "refactor" because it's [marked as such](https://github.com/rust-lang/rust-analyzer/blob/11a263d5ee0de9868e834c561ccb1c68ee21f4d8/crates/ide-assists/src/handlers/extract_variable.rs#L84)
 - in other cases, like `let x: Vec<_> = vec![10]` shows up as Rewrite in the menu
 - Light bulb / `Ctrl-.` / right click -> Refactor are the same assists, triggered in different ways
 - the latest version of VS Code will also offers assists for the current line, not just the caret position, which makes https://github.com/rust-lang/rust-analyzer/pull/15809 less important
