### ISSUE TITLE
Trailing whitespace trimmed from doc comments

### ISSUE THREAD

**Issue by MinusGix** [rust-lang/rust-analyzer#15877]
**rust-analyzer version**: 0.4.1728-standalone

**rustc version**: rustc 1.73.0 (cc66ad468 2023-10-03)

Example:  
```rust
/// This is a testing comment to test rustdoc markdown.  
/// This is the next line.
pub fn add(left: usize, right: usize) -> usize {
    left + right
}
```
In rustdoc, this appears like: 
![image](https://github.com/rust-lang/rust-analyzer/assets/13157904/545850d2-e0a2-42c4-bbcf-547cd4622b1e)

However, in VSCode/Lapce, it appears as:  
![image](https://github.com/rust-lang/rust-analyzer/assets/13157904/03a43f9b-6f83-43f2-af9a-d63121334794)
  
The contents of what VSCode receives:  
```json
    "contents": {
        "kind": "markdown",
        "value": "\n```rust\ntesting1\n```\n\n```rust\npub fn add(left: usize, right: usize) -> usize\n```\n\n---\n\nThis is a testing comment to test rustdoc markdown.\nThis is the next line."
    },
```
So it appears that it strips the whitespace at the end of the lines, and then sends it along. Since the receiver is parsing this as markdown, they do the typical behavior of single newlines not being actual linebreaks.  
  
I believe this didn't used to happen until some months back, but I haven't checked which version I remember it being fine on.  
  
It seems to have happened before in #1997 and then been fixed.

**Comment by riverbl** [comment]
Trailing whitespace having semantic meaning seems really horrible to me.

`rustfmt` is clearly aware of trailing spaces having meaning in Markdown, as it will trim a single trailing space from doc comments, but won't trim multiple trailing spaces.

As far as I can tell, either any number of trailing spaces greater than one or a trailing backslash indicates a line break, with no difference in meaning. `rustfmt` allows either of these forms, and does not normalise the number of trailing spaces.

**Comment by Marcono1234** [comment]
> Trailing whitespace having semantic meaning seems really horrible to me.

As side note: CommonMark (which is used by rustdoc) alternatively supports a trailing `\` instead of two spaces to create a hard line break (see [specification](https://spec.commonmark.org/0.30/#hard-line-breaks)).
But you should check whether at that location a hard line break is actually needed (and there is no implicit line break, e.g. due to usage of `> ...` in the next line). At least GitHub seems to render the `\` literally in that case, though it seems rustdoc doesn't but I am not sure if that is guaranteed behavior.
