### ISSUE TITLE
Rust-analyzer in VScode encounters problem when starting server

### ISSUE THREAD

**Issue by Do7and** [rust-lang/rust-analyzer#15927]
I want to use rust-analyzer in vscode so I install the extension by vscode, but when I start to use it, it throws error :[ERROR project_model::rustc_cfg] failed to get rustc cfgs e=系统找不到指定的文件。 (os error 2). And maybe due to this error, I cannot find the "RUN doc-test" button where I write the doc test which can be detected by "cargo doc --open" command.

I take other's example as referrence, but in my rust-analyzer it doesn't work.
![image](https://github.com/rust-lang/rust-analyzer/assets/41378140/9ea0639c-c842-471b-99fd-3b88cf96f22e)

**rust-analyzer version**:v0.3.1730
**rustc version**: 1.74.0

**relevant settings**: NO rust-analyzer*-like setting in setting.json

**Comment by Veykril** [comment]
系统找不到指定的文件 = The system can not find the file specified

How did you install rust? It seems rust-analyzer is unable to run `rustc --print cfg` as `rustc` does not resolve to a command for it

**Comment by Do7and** [comment]
> 系统找不到指定的文件 = The system can not find the file specified
> 
> How did you install rust? It seems rust-analyzer is unable to run `rustc --print cfg` as `rustc` does not resolve to a command for it

I have surely installed rust. And I run  `rustc --print cfg` in the same directory with my code above, it seems no problem.
![image](https://github.com/rust-lang/rust-analyzer/assets/41378140/d8bf9b02-0d2f-4479-b7fc-5644f82b4715)

And in my env path there exists cargo bin directory which contains rustc.exe and so on

I do not know how this rustc_cfg work in this extension, because when I use Everything to search rust_cfg on my local there shows no result.

**Comment by 0xd34db100d** [comment]
Got the same error too on server extension startup:
![изображение](https://github.com/rust-lang/rust-analyzer/assets/54123032/35b8099f-e01a-4ce3-b403-e39fa685978a)

**Comment by AndersHogqvist** [comment]
I just installed Rust as well as rust-analyzer and have the same issue. I can run rustc --print cfg in the terminal but rust-analyzer seems to live in its own environment where it can't find rustc.

**Comment by lnicola** [comment]
@AndersHogqvist if you're on Linux or MacOS, see this part of the manual:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/fc1416e7-5f42-4145-8ef6-89ec4e0b1a9c)

and https://github.com/rust-lang/rust-analyzer/issues/1811.

**Comment by AndersHogqvist** [comment]
I'm on Windows. In PowerShell:

```
C:\playground > rustc --print sysroot
C:\Users\SEANHOG1\.rustup\toolchains\stable-x86_64-pc-windows-msvc
```

Tried specifying the path in settings.json with / instead of \\ but that didn't help either:

```
"rust-analyzer.cargo.sysroot": "C:/Users/SEANHOG1/.rustup/toolchains/stable-x86_64-pc-windows-msvc"
```

```
[ERROR project_model::rustc_cfg] failed to get rustc cfgs e=failed to discover rustc in sysroot: "C:\\Users\\SEANHOG1\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc"
```

**Comment by AndersHogqvist** [comment]
Oh, `rustup component add rust-src` and restarting rust-analyzer solved it! :-)

**Comment by Veykril** [comment]
It can't :) that's a bug

**Comment by ShadowDrakken** [comment]
Same issue occurring here...
ERROR project_model::rustc_cfg: failed to get rustc cfgs e=failed to discover rustc in sysroot: "\<redacted\>\\\\Rust\\\\rustup\\\\toolchains\\\\stable-x86_64-pc-windows-msvc"

Caused by:
    The system cannot find the file specified. (os error 2)

PS> rustc --version                      
rustc 1.76.0 (07dca489a 2024-02-04)

PS> rustup component add rust-src
info: component 'rust-src' is up to date

PS>dir (rustc --print sysroot)
Directory: \<redacted\>\\Rust\\rustup\\toolchains\\stable-x86_64-pc-windows-msvc

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2/10/2024   2:57 PM                bin
d-----         2/10/2024   2:57 PM                etc
d-----         2/10/2024   2:57 PM                lib
d-----         2/10/2024   2:57 PM                libexec
d-----         2/10/2024   2:58 PM                share
