### ISSUE TITLE
Some functions do not show examples on hover

### ISSUE THREAD

**Issue by oloko64** [rust-lang/rust-analyzer#15920]
## Problem

The functions `saturating_mul`, `saturating_add`, `abs`, etc don´t show the examples, however on the [Rust docs](https://doc.rust-lang.org/std/primitive.u8.html#method.saturating_mul) they have examples for those functions.

 Seems to be related to `const fn` functions.

---

### On VSCode

![image](https://github.com/rust-lang/rust-analyzer/assets/49915167/4a40e7f8-3c0c-459e-af14-fc529f9368c5)
![image](https://github.com/rust-lang/rust-analyzer/assets/49915167/6a15fd22-b307-421e-a6d5-f676746bb450)

---

### On Rust docs

![image](https://github.com/rust-lang/rust-analyzer/assets/49915167/722057b0-34c3-45e3-8317-84341a1b9c4e)
 
 ---
 
**rust-analyzer version**: v0.3.1730

**rustc version**: 1.74.0

**relevant settings**: Using VSCode on Linux

**Comment by dfireBird** [comment]
I don't think it's problem with `const` functions. Because in the same `u8` the `is_ascii` method is a `const` function and the hover has examples. I also have tried with other `const` functions as well and the hover has examples as well.

But I did found something, all the `saturating_*` functions (and some other functions in `u8` ) are using the macro `uint_impl!` to generate their implementations as well doc comments and these methods are the one that doesn't have the examples in it. It's possible that it might have some thing to do with that.

**Comment by dfireBird** [comment]
This is not a problem with `const` functions. The `saturating_*` methods all use macro call inside the `#[doc]`, which is not supported by the rust-analyzer.

**Comment by lnicola** [comment]
Probably https://github.com/rust-lang/rust-analyzer/issues/8092?
