### ISSUE TITLE
Failed to spawn one or more proc-macro servers

### ISSUE THREAD

**Issue by oxSaturn** [rust-lang/rust-analyzer#16001]
I'm trying to use rust-analyzer extension for vscode insider, and it keeps showing me the following error:

```
Failed to spawn one or more proc-macro servers.
- cannot find proc-macro-
srv, the workspace /Users/**/projects/branches is missing a sysroot Failed to find sysroot for Cargo.toml file /Users/**/projects/branches/Cargo. toml. Is rust-src installed? can't load standard library from sysroot
- /opt/local
(discovered via ' rustc --print sysroot*)
try installing the Rust source the same way you installed rustc
```

**rust-analyzer version**: rust-analyzer version: 0.3.1748-standalone (237712fa3 2023-11-26)

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

```
$ rustup component list | grep src
rust-src (installed)
```

```
Version: 1.85.0-insider (Universal)
Commit: 92772dcc29bd74108ab61ba9da5ad1f5154639ff
Date: 2023-11-30T18:38:36.579Z
Electron: 25.9.6
ElectronBuildId: 25427645
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
```

There was a relevant issue here https://github.com/rust-lang/rust-analyzer/issues/14868, but none of the solutions there solve my problem.

**Comment by Veykril** [comment]
What does running `rustc --print sysroot` print from within that workspace?

**Comment by lnicola** [comment]
It's built from source, it might look unusual.

**Comment by Veykril** [comment]
How did you install rust itself? Given it says

> rustc version: rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)

it doesn't seem to be done through rustup which I'd recommend doing, otherwise I'm not sure whats going on here either but you don't seem to have sysroot (the standard library sources and stuff)?

**Comment by ryandesign** [comment]
> And obviously the one installed with macports messed up.

And unfortunately nobody reported that to MacPorts until now:

https://trac.macports.org/ticket/68987

And if anybody has any hints for how we at MacPorts can fix this problem I'm sure we would appreciate it.

**Comment by delreluca** [comment]
Today I started learning rust and I decided to use MacPorts to install it. I’ve encountered the same problem but I managed to make it work:

I installed these ports
```console
$ port echo requested | grep "cargo\|rust"
cargo                          @0.76.0_0 
rust                           @1.75.0_0 
rust-analyzer                  @20240226_0 
rust-src                       @1.75.0_0 
```
which give OP’s sysroot:
```console
$ rustc --print sysroot
/opt/local
```
Then I had to set the paths manually (this is for the VSCode extension):
```json
{
    "rust-analyzer.cargo.sysrootSrc": "/opt/local/libexec/rust/src/rustc-1.75.0-src/library/",
    "rust-analyzer.procMacro.server": "/opt/local/bin/rust-analyzer",
    "rust-analyzer.server.path": "/opt/local/bin/rust-analyzer"
}
```

[This comment says](https://github.com/rust-lang/rust-analyzer/issues/4778#issuecomment-640179216) that the sources should be under `$(rustc --print sysroot)/lib/rustlib/src` instead, so I guess we should change

https://github.com/macports/macports-ports/blob/aac698d21828edaba636319628a8f8fcf22c6840/lang/rust/Portfile#L249

As to why I had to install `rust-analyzer` manually (instead of using the VSCode included one) and whether the sysroot is appropriate I don’t know.
