### ISSUE TITLE
Multi-root workspace in vscode

### ISSUE THREAD

**Issue by iamshreeram** [rust-lang/rust-analyzer#16030]
This is how my vscode workspace appears: 

```
~
 | /.cargo/
 | /.cabal/
 | /.nvm/
 | .bash_profile
 | .bashrc
 | /project/
 |  | /Clojure/
 |  |  | /allmycljprojects 
 |  | /Shell/
 |  |  | /allmybashprojects 
 |  | /rust/
 |  |  | /proj
 |  |  |  | /project-1
 |  |  |    | /src
 |  |  |       | main.rs
 |  |  |    | Cargo.toml
 |  |  |    | Cargo.lock
 |  |  |  | /project-2
 |  |  |    | /src
 |  |  |       | lib.rs
 |  |  |    | Cargo.toml
 |  |  |    | Cargo.lock
 |  |  |  | /project-3
 |  |  |    | /src
 |  |  |       | main.rs
 |  |  |    | Cargo.toml
 |  |  |    | Cargo.lock
 |  |  | /wasm
 |  |  |  | http-server
 |  |  |    | /src
 |  |  |       | main.rs
 |  |  |    | Cargo.toml
 |  |  |    | Cargo.lock
 |  |  | /ml
 |  |  |  | /sklearn-rs
 |  |  |    | /src
 |  |  |       | main.rs
 |  |  |    | Cargo.toml
 |  |  |    | Cargo.lock
 |  | /haskell/
 |  |  | /allmyhaskellprojects
 |  | /python/
 |  |  | /allmypythonprojects 
 |  | /go/
 |  |  | /bin
 |  |  | /pkg
 |  |  | /src
 |  |  |  | /github.com
 |  |  |    | /tarekbadrshalaan/
 |  |  |    | /elastic  
 |  |  |  | /gecgithub.com
 |  |  |    | /ers 
 |  |  |      | /ocf-gql
 |  |  |         | go.mod
 |  |  |         | go.lock
 |  |  |         | cmd
 |  |  |      | /dummy-app
 |  |  |         | go.mod 
 |  |  |  | /gitlab.com
 |  |  |  | /golang.org
 |  |  |  | /gopkg.in
 |  | /scala/
 |  |  | /allmyscalaprojects
 |  | /node/
 |  |  | /allmynodeprojects
```
I used `rust-analyzer.linkedProjects` in `settings.json` to enable auto-completion with RALS (Rust Analyzer Language Server). It worked well, but I had to modify the settings whenever I created a new **cargo** project.

To address this, I started updating rust's `workspace.members` manually with all my `Cargo.toml` paths to track them. It is manageable but still requires manual effort. 

1. Is this a recommended practice? 
2. Is there a way to automate this process and allow vscode RALS to track all Cargo.toml files within a specific folder on its own, and by eliminating the need for manual updates?

**Comment by iamshreeram** [comment]
+ @bjorn3 , @matklad for review.

**Comment by alibektas** [comment]
For a multi-language project it is recommended to use  `linkedProjects`. An automation is not amongst our plans as we leave the decision to the user which projects they want rust-analyzer to interact with. I guess you could use a virtual workspace and link to its Cargo.toml

As to the reviewers it would be very kind of you to choose more active maintainers. In fact somebody will eventually answer your questions so you don't really need to ping anyone.

**Comment by iamshreeram** [comment]
@alibektas , Thanks for response. Should we use both linkedProjects and workspace.members or either of it would work?

I've currently listed all my Cargo.toml in workspace and pointed it in linkedProjects. Is this recommended?

**Comment by alibektas** [comment]
You see there is not a single way to answer your question. Normally if you can open your rust workspace as the `$ROOT_DIR` in your editor of choice, `rust-analyzer` should handle the rest and discover the projects for you. If you think that your rust projects should be completely isolated from one another then you should really use `linkedProjects` but this should tell you also that you could have actually opened your editor on one of your projects instead of an ancestor directory. If your projects are related and maintained together then you should gather them under the same workspace. 

As to the error : I don't see the specified path under the directory structure you attached to your initial question. ( Meaning there is no `domfind/Cargo.toml` )

**Comment by Veykril** [comment]
Note that you can have a workspace local vscode settings.json file that specifiy the `linkedProjects`, instead of putting that globally. Otherwise this will have to wait on the `rust-analyzer.toml`. Also, you only need to specify the top most cargo workspaces (any members /dependencies of those workspaces will be automatically considered by r-a)
