### ISSUE TITLE
Auto-closing backticks does not work well combined with triple backtick code blocks.

### ISSUE THREAD

**Issue by Yurihaia** [rust-lang/rust-analyzer#16051]
**rust-analyzer version**: `0.3.1756-standalone`

**rustc version**: `rustc 1.75.0-beta.5`

When writing doc comments with examples, attempting to create a code block by pressing backtick three times ends up creating 4 backticks, which can get quite annoying when writing a lot of them.

Furthermore, unlike normal string literals, extra backticks are not error highlighted of course, which means documentation
can end up with random double backticks scattered throughout the documentation.

Ideally I would line an option to at least disable the autoclosing backticks without having to disable all autoclosing pairs, because any more sophisticated solution will still run into the second issue.

**Comment by Veykril** [comment]
That is indeed annoying and we can't make it work for that situation either. Rather than a config I think we should remove autoclosing for backticks again, making it configurable means we can't use the config file there altogether I think (or at least is gonna be annoying as parts of it are then defined in code, and other parts are not).
