### ISSUE TITLE
Increasing suggestion level for completion?

### ISSUE THREAD

**Issue by soupslurpr** [rust-lang/rust-analyzer#16075]
Could there be an option to increase the level of completion completion suggestions?

I'd like to see more completions that aren't visible until you type the first letter, see https://www.reddit.com/r/rust/comments/18dknqp/how_do_i_get_rustanalyzer_to_analyze_deeper/

**Comment by Veykril** [comment]
We don't offer trait importing completions for empty identifier completions due to performance reasons right now.

**Comment by flodiebold** [comment]
`Write` is a `notable_trait`; maybe we could offer completions for those even if they aren't imported and without any prefix :thinking:

**Comment by dfireBird** [comment]
The traits to be selected for completion is happening at the [`search_dependencies`](https://github.com/rust-lang/rust-analyzer/blob/426d2842c1f0e5cc5e34bb37c7ac3ee0945f9746/crates/hir-def/src/import_map.rs#L389), which returns early when a limit is set. So would it make sense to write a similar function just for `notable_trait` or modify the existing function, so that it returns those traits regardless of limit?

**Comment by Veykril** [comment]
I think we just want to record notable-traits in the import map, then we can go through those directly making it very cheap to query them.

**Comment by dfireBird** [comment]
By import map, do you mean the type `ImportMap`? Also am I correct in assuming by records you mean that RA should collect all notable-traits at startup and have somewhere in memory to easily query the notable traits?

**Comment by Veykril** [comment]
Yes I meant the `ImportMap`. We can collect them while constructing the `ImportMap` since we are already iterating over all the items of a crate there anyways.

**Comment by danielhuang** [comment]
#16207 should deal with this problem, but right now the LSP protocol (as far as I can see) can only support sending all completions all at once, instead of sending incrementally while more completions are computed. In my testing removing the limit completely still works fast enough in medium-sized projects.

**Comment by Veykril** [comment]
On second thought (now that I touched the related code myself the entire day yesterday), do we still need the limit for trait importing completions at all? The slow part now is only generating the completion items, not the searching (as I optimized that heavily now), and I don't think there is a gonna be a huge amount of method completions / assoc item completions from traits.
