### ISSUE TITLE
wrong semantic token type reported for struct at the end of async main function

### ISSUE THREAD

**Issue by LastExceed** [rust-lang/rust-analyzer#16148]
1. paste this snippet in vscode:
```rust
struct MyStruct;

#[tokio::main]
async fn main() {
    MyStruct;
}
```

2. place caret on `MyStruct` inside `main`
3. `Ctrl + Shift + P` -> `Developer: Inspect Editor Tokens and Scopes` -> `semantic token type`
**expected:** `struct`
**got:** `method`

**workaround:** explicitly return `()` at the end of the function

this bug can result in confusing code highlighting colors

---
**rust-analyzer:**
> 0.3.1774-standalone (21b06c1be 2023-12-15)

**rustc:**
> 1.74.1 (a28077b28 2023-12-04)

**Comment by dfireBird** [comment]
While I couldn't find what was the problem (I lack the necessary knowledge :( ), I could find the method and the probable cause of this issue. I hope it helps someone else (or me in the future).

The method [`SemanticsImpl::descend_into_macros_single`](https://github.com/rust-lang/rust-analyzer/blob/337e2abb670d403ae05609c5f1aafcffbd3369a6/crates/hir/src/semantics.rs#L561), tries to descend into the macro expansion and find other token of the same kind for the current token. It somehow finds the `new_multi_thread` (from the expansion of `tokio::main` macro), a method as a potential match and which in turn returns the semantic type of `MyStruct` as method.

**Comment by Veykril** [comment]
Yep, you pretty much found the core issue. Highlighting will generally be tripped up by proc-macros that re-use the spans of tokens. It's difficult to figure out what token in the expansion to base the highlighting on so we can only do a best effort heuristic approach. This regressed because of my recent changes, though the previous behavior had its problems as well. I am open to ideas for making highlighting here smarter, although I don't think we have a lot of options. Ideally proc-macros would have access to def site hygiene, then tokio could mark their extra output with a def site context which would fix this problem fully, but alas that is not yet stable.

**Comment by Veykril** [comment]
This now works as expected, we've improved our heuristics here
