### ISSUE TITLE
Debugger showing initial random value for variable.

### ISSUE THREAD

**Issue by zoeqevans** [rust-lang/rust-analyzer#16203]
Boy this is a weird one. A minimal reproduction:

```
fn main() {
    let w = 0;
    let x = 0;
    let y = 0;
    let z = 0;
}
```

With a breakpoint on the first line of `main()`.

If you then click the `Debug` option that appears in grey above `fn main()`, and step to the `let y = 0` line, the value for `y` in the local variables panel shows as some random, very large number (different every time; screenshot from most recent run). Once you step past the value, it correctly shows as 0.

This was confusing when I ran across it during debugging, as I thought I'd somehow corrupted memory using arcane multithreaded evil.

<img width="663" alt="image" src="https://github.com/rust-lang/rust-analyzer/assets/32969601/1a9f977c-7bab-4b18-8ba8-3afadc545163">

**Comment by zoeqevans** [comment]
rust-analyzer version: 0.3.1782-standalone (85fb463fc 2023-12-24)
rustc 1.74.0 (79e9716c9 2023-11-13)

**Comment by Young-Flash** [comment]
its't a RA bug, `y` hasn't been initialized at the moment, its memory bit could be random so it different every time.

**Comment by zoeqevans** [comment]
That's what I figured, so why show it in the debugger pane if it hasn't yet been initialized? E.g. we don't show `z` in the debugger pane. RA could easily wait until `y` is initialized to show it, and this seems like needlessly confusing behaviour... but maybe there's a good reason for it that I'm not seeing?

**Comment by zoeqevans** [comment]
@lnicola I'm not familiar with how extensions fit together - is there a way to figure out what debugger extension I'm using? I don't think I installed one explicitly, but maybe it's a dependency of RA?

**Comment by lnicola** [comment]
It's not, we support https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools and https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb.

> RA could easily wait until y is initialized to show it

No, that's not easy in languages like C, C++ and Rust. It's only easy in C# and Java. The debug info is a kind of bytecode that debuggers have to interpret in order to understand what's happening in the program. It was designed before Rust (and has no knowledge of it), and it works pretty well given the circumstances.

Here is the same issue in C++ with LLDB:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/01967973-d017-4d28-a6f8-8d70cd2c966b)

And in C++ with GDB:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/de499c5b-6df0-4966-81be-eb178805a49b)

**Comment by zoeqevans** [comment]
Ah, makes sense now - thanks for explaining (and for linking the debugger article as well)!
