### ISSUE TITLE
How to activate unstable feature restricted_std in rust-analyzer?

### ISSUE THREAD

**Issue by lattice0** [rust-lang/rust-analyzer#16232]
**rust-analyzer version**:
0.3.1791-standalone

**rustc version**: rustc 1.77.0-nightly (fb5ed726f 2023-12-28)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

I'm trying to compile for esp32c6 (`riscv32imac-unknown-none-elf`). Actually, `cargo build` runs, but when I save the file rust-analyzer checks it and complains:

```lang-none
error[E0658]: use of unstable library feature 'restricted_std'
   --> /home/lz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/formatters/json.rs:225:55
    |
225 |     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> ::std::fmt::Result {
    |                                                       ^^^^^^^^^^^^^^^^^^
    |
    = help: add `#![feature(restricted_std)]` to the crate attributes to enable
```

As you see, it's complaining about a feature in the std lib, which is strange. I added `#![feature(restricted_std)]` to main.rs but the error is in the standard library where I cannot add this feature. 

I also tried
```lang-yaml
{
    "rust-analyzer.cargo.cfgs": {
        "build-std": ["core", "std", "alloc", "panic_abort"],
        "restricted_std": true
    },
    "rust-analyzer.check.allTargets": false,
    "rust-analyzer.cargo.target": "riscv32imac-unknown-none-elf"
}
```

and other variations without success. Also tried

```lang-toml
[unstable]
features = ["restricted_std"]
```

in `rust-analyzer.toml`.

Also

```lang-sh
~/project1$ rustup toolchain install riscv32imac-unknown-none-elf
error: invalid toolchain name: 'riscv32imac-unknown-none-elf'
```

**Comment by Veykril** [comment]
In what editor is this? It looks like rust-analyzer is trying to compile the standard library for you here which might be an issue with how the editor reports the workspaces.

**Comment by lattice0** [comment]
It's vscode. Any idea on how I can switch this?

-------- Mensagem Original --------
Em 3 de jan. de 2024, 07:00, Lukas Wirth escreveu:

**Comment by lnicola** [comment]
> rustup toolchain install riscv32imac-unknown-none-elf

`rustup +nightly target add riscv32imac-unknown-none-elf`

**Comment by lnicola** [comment]
`riscv32imac-unknown-none-elf` is a no-std target, does `"build-std": ["core", "std", "alloc", "panic_abort"]` even work there?

**Comment by mohe2015** [comment]
You could try the equivalent `cargo build` including the correct target and using -Zbuild-std to check whether this is a rust analyzer issue.

**Comment by mohe2015** [comment]
Maybe this is https://github.com/rust-lang/wg-cargo-std-aware/issues/87 so you forgot #![no_std] ?

**Comment by lattice0** [comment]
@mohe2015 it builds and runs with ˋcargo buildˋ and no ˋ#![no_std]ˋ so I guess no? I actually want to use the std lib. But yeah I added ˋ#![feature(restricted_std)]
#![no_main]ˋ so I could do ˋcargo buildˋ or ˋcargo runˋ etc. How can it work on the command line and not rust-analyzer?

Also @lnicola your suggestion: 

```
rustup +nightly target add riscv32imac-unknown-none-elf
info: component 'rust-std' for target 'riscv32imac-unknown-none-elf' is up to date
```

**Comment by mohe2015** [comment]
Is the rust analyzer config to enable build std correct? I'm not sure whether it accepts the build std at that location because I couldn't find any docs and can't test right now

**Comment by mohe2015** [comment]
Maybe https://users.rust-lang.org/t/rust-analyzer-stops-working-with-build-std-solved/64333/2 helps

**Comment by lattice0** [comment]
Ok, if I understood correctly, I'm trying to build, in rust-analyzer, with std, but I actually can only build with restricted_std, for my target. Is this correct? So rust-analyzer does not know what is my target and therefore tries to use std.

**Comment by mohe2015** [comment]
> Ok, if I understood correctly, I'm trying to build, in rust-analyzer, with std, but I actually can only build with restricted_std, for my target. Is this correct? So rust-analyzer does not know what is my target and therefore tries to use std.

Your target does not support std so I personally would add `#![no_std]` and disable all std features of dependencies. https://github.com/rust-lang/wg-cargo-std-aware/issues/87 is the issue that wants to improve the error message.
See https://github.com/mohe2015/rust-analyzer-issue-16232/tree/main especially the `.cargo/config.toml`, `.vscode/settings.json` and `src/main.rs`.

**Comment by lattice0** [comment]
But it supports restricted_std because it works with cargo build, just not in rust-analyzer. Am I right?

-------- Mensagem Original --------
Em 19 de jan. de 2024, 10:21, Moritz Hedtke escreveu:

**Comment by mohe2015** [comment]
Yeah with cargo it works just not in rust-analyzer. I think I found the issue. I think rust-analyzer sets the build-std "test" because the commit https://github.com/mohe2015/rust-analyzer-issue-16232/commit/143d64a1219de2a091c4dd7ff01d3ccf869d7641 makes it work for cargo but not rust-analyzer and before it's broken for both.

**Comment by lattice0** [comment]
@mohe2015 are you going to merge this?

**Comment by mohe2015** [comment]
> @mohe2015 are you going to merge this?

It's not a commit in rust-analyzer but only in my test project (https://github.com/mohe2015/rust-analyzer-issue-16232/commits/restricted-std). It's also just an assumption what may happen. Somebody would need to find out whether that's actually the case and where in rust analyzer this is set for the project and fix it there. I currently don't have the time to do that.

**Comment by lattice0** [comment]
@mohe2015 yes. Unfortunately I'm on vscode.dev so it's a bit hard to compile my own. Any ideas on how to mitigate this with configurations?

**Comment by jakzale** [comment]
I am having a similar issue, while also targeting a variant of `riscv32`, which doesn't have `std` available.

I noticed that setting `rust-analyzer.check.allTargets` to `false` in `.vscode/settings.json` gives me diagnostic for my code, whereas setting it to `true`, doesn't give me any diagnostics.

I know that running `cargo check --workspace --all-targets` will fail on my codebase with

- similar errors to error reported by the OP, and
- those errors are not related to my codebase or my dependencies, because
- those errors happen in `.rustup/toolchain/<toolchain>/lib/rustlib/src/rust/library/test/src/lib.rs`.

which  seems to cause `rust-analyzer` to fail silently, as there is no diagnostic message produced on saving source files.

Regarding the errors that are reported, as of current prerelease of `rust-analyzer` (`rust-analyzer 1.79.0-nightly (0ad927c0 2024-03-21)`), they occur once, when the server is reloaded, and the are prefixed with
```
2024-03-25T15:16:50.782873Z ERROR rust_analyzer::main_loop: FetchBuildDataError:
error[E0658]: use of unstable library feature 'restricted_std'
  |
  = help: add `#![feature(restricted_std)]` to the crate attributes to enable
  = note: this compiler was built on 2024-03-09; consider upgrading it if it is out of date
```

It looks like the reported error is related to a different step within `rust-analyzer`, that is happening before `cargo check`.

I suspect that there might be two separate bugs here
- `rust-analyzer` using incorrect configuration immediately after server is reloaded, and
- `rust-analyzer` failing silently when default `cargo check` fails due to compilation errors unrelated to the project.

**Comment by Veykril** [comment]
Yes for htese projects you should set `.check/build.allTargets` to `false` as otherwise our cargo invocations try to build test targets which require the standard library. We are doing a bad job at telling the user about that as is evident here.

Note that for the `FetchBuildDataError` we surface that in the status icon (which is not necessarily supported by all clients).

**Comment by jakzale** [comment]
> Yes for htese projects you should set `.check/build.allTargets` to `false` as otherwise our cargo invocations try to build test targets which require the standard library. We are doing a bad job at telling the user about that as is evident here.

I don't think you expose `.build.allTargets` configuration key in VSCode.  Neither the Manual mentions it.

> Note that for the `FetchBuildDataError` we surface that in the status icon (which is not necessarily supported by all clients).

Yeah, noticed that in VSCode.

**Comment by Veykril** [comment]
Ah right, https://github.com/rust-lang/rust-analyzer/pull/16924 hasn't been merged yet. So we'll expose that soon

**Comment by jakzale** [comment]
I confirm that #16924 solves the issue for me.  Just need to put
```json
{
  "rust-analyzer.cargo.allTargets": false,
}
```
in `.vscode/settings.json`.
