### ISSUE TITLE
Assist idea: extract option using let-else

### ISSUE THREAD

**Issue by obsgolem** [rust-lang/rust-analyzer#16390]
In my coding style I make extensive use of let-else to handle invalid cases. Sometimes `?` works, but if I need to diverge in a loop using `break` or `continue` then it isn't sufficient. It would save me some typing if RA had an assist that could convert this:
```rust
fn f() -> Option<i32> {
    None
}

fn g() {
    let |x = f();
}
```
into
```rust
fn f() -> Option<i32> {
    None
}

fn g() {
    let Some(x) = f() else {
        |
    };
}
```
where `|` marks the cursor.

**Comment by dfireBird** [comment]
An assist for converting the last `if-let` to guarded return exists. I suppose, it could be reused for this specific purpose. But the maintainers should take a call on the actual design.

**Comment by Veykril** [comment]
Adding a variant for loop control flow seems useful to me.

**Comment by dfireBird** [comment]
I'll try to implement this then unless the author want's to do it themselves..

**Comment by obsgolem** [comment]
Feel free.

**Comment by dfireBird** [comment]
Well this is embarrassing, but I checked the one loop (`for`) that guarded return assist doesn't support and determined that guarded return didn't support loops. Truly a mistake on my part should've been through.

In saying that, I think it would be nice to have an assist for what the issue was talking about, i.e. an assist that let's you convert `Option` or `Result` value assigned to variable in `let` to guarded return, like a proposal that we can convert it to guarded return (It could couple as an assist to convert it to `if-let`). 

P.S: Is `for` loop intentionally left out? If not, I could create PR or send a patch file that one of maintainers can commit it themselves.

**Comment by Veykril** [comment]
I don't see a reason why we shouldn't support for loops in there either.

**Comment by lnicola** [comment]
@dfireBird this can be closed, right?

**Comment by dfireBird** [comment]
Yeah, this is implemented with my PR.
