### ISSUE TITLE
Snippet edit support for diagnostic quickfixes

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16767]
We currently don't support this but I don't think there is anything blocking us from having it.

**Comment by DropDemBits** [comment]
Related #14262 since some of those assists use snippet edits.

**Comment by DropDemBits** [comment]
Looks like there is already support for snippet edits in diagnostic quickfixes, since quickfixes generate `Assist`s which already supports snippet edits, and they go through the `CodeAction` code path which also already supports snippet edits.

So the main thing is just migrating quickfixes to use `SourceChangeBuilder` and the related structured snippet methods.

**Comment by DropDemBits** [comment]
Ah I just realized that there's no way to access a `SnippetCap` in a diagnostic. The final piece of the puzzle would be to add a `snippet_cap` to `DiagnosticsConfig`, and then update `Config::diagnostics` to create a `SnippetCap` like is done for `AssistConfig`:
https://github.com/rust-lang/rust-analyzer/blob/48cb05918229d6f1141901d0e439fd993e0006bf/crates/rust-analyzer/src/config.rs#L1585-L1587
