### ISSUE TITLE
Postfix snippets no longer work in vscode

### ISSUE THREAD

**Issue by jtraub** [rust-lang/rust-analyzer#17036]
**rust-analyzer version**: 0.4.1909-standalone

**editor or extension**: VSCode with extension v0.4.1909 (pre-release)

Postfix snippets stopped working after I've updated vscode extension. 

After downgrading a few times I found that the last version that has postfix snippets working is v0.4.1908. Upgrading it to v0.4.1909 breaks them.

v0.4.1908
![image](https://github.com/rust-lang/rust-analyzer/assets/153191/28b3afa4-1151-492c-9543-7fc32136b810)

v0.4.1909
![image](https://github.com/rust-lang/rust-analyzer/assets/153191/8e9e2886-b151-4ec7-858a-350a32337995)

**Comment by twhice** [comment]
me too

**Comment by roife** [comment]
Possibly related to #17000.

**Comment by facefaceless** [comment]
Magic completion dosen't show up in the completion list too after upgrading to a newer version.
I use vscode on windows, and RA 0.3.1906 (release version) is the newest version that works fine for me.
Maybe they are the same problem.

**Comment by kericsson-dotnet** [comment]
Postfix snippets seems to be broken in Neovim as well. Working fine in 2024-04-01, not showing up in 2024-04-08

**Comment by pascalkuthe** [comment]
> . I've tried it and this fixes the problem in VS Code, but it seems that helix does not yet support additionalTextEdit

Helix fully support additionalTextEdits. We just dont preview them since we expect them to not be associated with the cursor. Quote from the LSP spec:

>Additional text edits should be used to change text unrelated to the current cursor positition

So we only apply additionalTextEditd when accepting a completion. Qhile the lossy in preview is a bit annoying it's not that big of a deal.

The real problem is that these kinds of edits do not work with multicursor completions. You can map the main completion edit to each cursor (by computing relative positions to the curosr). But you can't do that with `additonalTextEdit` Since they are meant for edits *not associated with the cursor* (like imports) that should not be repeated for each cursor.

It's unofrtunate that vscode has this resrriction for completion edits since these edits are perfectly valid according to the LSP spec. The spec says the completion position must be contained within the edit but not that it must start exactly at the cursor:

> The range of the edit must be a single line range and it must contain the position at which completion has been requested

The reason this gets filtered is not that vacode filters out all edits that precede the cursor position. The reason is that vscode uses the replace range for filtering so to take the example from above if the edit replaces `1.ok` with `Ok` then vscode filters that with `1.ok` (which is spec compliant and what I am working on moving helix towards).

The right way to fix this issue in a spec compliant manner is to adjust the filter text of these completions to include the prefix they are replacing

**Comment by pascalkuthe** [comment]
> So, we should be able to change the replace range here if we also fix up the filter text used for postfix completions. Then VSCode should be happy as well?

Exactly, sorry my comment wasn't perfectly clear. I didn't have my first coffee yet. 

In fact RA already does exactly that for replace edits (the edits where lsp allows the client between just inserting and replacing). These also replace text bwfore  the curosr and they work in VSCode because they set the filtertext correctly. 

I was planning to do a PR that implements what I describe once I have some freetime

**Comment by Veykril** [comment]
Great, thanks for that :) (fwiw in r-a the filter field is called `lookup` in our `CompletionItem`)

**Comment by roife** [comment]
@pascalkuthe, thanks for your correction! I followed your description to add both prefix and postfix to the `lookup` field in `CompletionItem`, and indeed it fixed all the issues (helix & vscode). If you don't mind, may I submit the PR to fix it?

**Comment by mrnossiom** [comment]
Sorry there, I've not received notifications about this. Glad you found another way around.

**Comment by mrnossiom** [comment]
I believe that both fixes for this got reverted because of issues with VSCode and other editors. Still, it would be great if we had proper visualization on Helix.

- https://github.com/rust-lang/rust-analyzer/pull/17054
- https://github.com/rust-lang/rust-analyzer/pull/17081

If this was the spec compliant way, wouldn't it be possible to take a look at VS Code src? I can try.
