### ISSUE TITLE
Borrow<T> leads to T being unknown in a generic blanket impl

### ISSUE THREAD

**Issue by sunrosa** [rust-lang/rust-analyzer#17170]
I am using rust-analyzer VScode extension ``v0.3.1940`` and rustc ``1.77.2``. I am having this issue with borrow(). With the impl below:
![image](https://github.com/intellij-rust/intellij-rust/assets/79175772/514d3abb-6a02-4a53-bb49-289345260858)

It is resolving to unknown and not linting, but has no compiler errors:
![image](https://github.com/intellij-rust/intellij-rust/assets/79175772/e9d6fbe4-c6f0-4876-b272-21be1696bce9)

And of course, there is no linting when trying to access fields of the unknown type.

**Comment by DavidArchibald** [comment]
I believe I've run into this issue as well. Here's my own reproduction:
```rust
fn broken_into_inference(into_string: impl Into<String>) {
    let should_be_string = into_string.into();

    should_be_string.len();
}
```

`should_be_string` is displayed with a type of `{unknown}` and the documentation for stuff like `len` won't show up. Using the wrong methods still shows up as an error but I think that's because of a rustc pass or something.

I'm going to assume the root cause is the same, hence why this isn't its own issue. I just want to make sure it gets looked at alongside this reproduction, just in case the root causes _are_ different.

**Comment by flodiebold** [comment]
Both of these are cases of #5514.
