### ISSUE TITLE
Spaces On Tab

### ISSUE THREAD

**Issue by nasccped** [rust-lang/rust-analyzer#17294]
#### What's up, devs?

---

I'm new to the **Rust** and I learned how to use **Cargo Manager 📦** recently.

I perfectly understand the language conventions, but one thing that bothers me a little is that when pressing `Tab`, 4 `spaces` are skipped instead of 2 (value set in the root configuration of my vs code).

I wanted to know if there is any way to change the value from ***4 to 2 in the Cargo settings*** or something like that.

---

**I thank the attention ❤️🦀**

**Comment by lnicola** [comment]
We have no relation to Cargo Manager or what happens when you press Tab in VS Code. Setting `editor.tabSize` to `2` should work, though. Which setting did you change?

**Comment by nasccped** [comment]
In fact, this configuration has already been defined, both in the:

- *vs code configuration interface*:
![image](https://github.com/rust-lang/rust-analyzer/assets/144759502/52252545-6685-498f-9503-99389e57d501)

- *and in the `settings.json` itself*:
![image](https://github.com/rust-lang/rust-analyzer/assets/144759502/50b61833-3a6d-4081-a269-ccc92b66ec91)

But:
![image](https://github.com/rust-lang/rust-analyzer/assets/144759502/256e4762-4c47-4d48-ab60-80cc300c88db)

---

In fact, this doesn't interfere much with the programming experience, but in the last 6 months, I've been writing code in **`C lang`** and I've gotten used to the 2-space tabs.

Having to organize all the lines into 2 spaces has a huge impact on my workflow.

**Comment by lnicola** [comment]
It works fine for me:

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/4259694c-6858-41c0-80ce-08b30071942d)

However:

 - VS Code detects the indentation by default (`editor.detectIndentation`), see also the status bar
 - I'm using rust-analyzer, but not Cargo Manager
 - if you have "editor.formatOnSave` enabled, you'll need to make a `rustfmt.toml` with `tab_spaces = 2` , otherwise your indent size gets changed back to 4 when you save (or format) the files

**Comment by nasccped** [comment]
**Right.**

Thank you very much for the quick response!

**Comment by lnicola** [comment]
So.. did you figure out what the problem was? Can we close this?
