### ISSUE TITLE
More IDE features for control flow keywords

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#17517]
We currently highlight relevant control flow structures when the cursor is on a relevant keyword, an example being highlighting all `await`s when on an async fn's `async` keyword, or all loop control flow keywords when it is on the loops keyword. We can do more things here I'd say. `Go to def/decl` on `return` could go the relevant closure/fn, `continue` and `break` to the corresponding loop (or block for labeled blocks), go to references could do the same as the highlighting

**Comment by roife** [comment]
For the `return` kw, should we navigate to the def (i.e., the function name) or the `fn` keyword of the function?

**Comment by roife** [comment]
I've encountered some difficulties handling macros:

Currently, for functions, I can correctly handle three scenarios (see GIF):

- Jumping directly to the function.
- Inside a macro, and jump to a function within the macro.
- Inside a macro, but jump to a function outside the macro.

These can be handled using `NavigationTarget::from_named` (`orig_range_with_focus`). However, how should I handle closures? Since closures don't have names, can they be mapped through SpanMap?

**Comment by Veykril** [comment]
They can be mapped just fine, it's just that we have no API in `NavigationTarget` for anything without names.

**Comment by Veykril** [comment]
I think for async blocks we might just wanna highlight await and return together. `{` isnt really intuitive for this
