### ISSUE TITLE
Version == release tag or internal version?

### ISSUE THREAD

**Issue by lcheylus** [rust-lang/rust-analyzer#17570]
I'm packaging `rust-analyzer` for OpenBSD OS.

To define a version for the package, I use the release tag (latest = `2024-07-08`). But in Changelog, I see that there is also an internal version (latest = `v0.3.2029`).

**What is the exact version of `rust-analyzer` to use?**

On Repology, I see that the other OS/Linux distribution uses release tag as version for `rust-analyzer` => https://repology.org/project/rust-analyzer/versions

**Comment by lnicola** [comment]
`rust-analyzer --version` reports something like `rust-analyzer 0.0.0 (a5b21ea0aa 2024-07-07)` for normal builds and `rust-analyzer 0.3.2029-standalone` for binaries you get from GitHub. That `2029` is a GHA run number, so they're not always predictable.

So yeah, we don't have a good story here, and I think either the or the version are fine.

**Comment by lcheylus** [comment]
OK, thanks for the infos. I will continue to use "release tag" (with date) to set the version of `rust-analyzer` in my OpenBSD port (via `CFG_RELEASE` variable, see `crates/rust-analyzer/src/version.rs`).

I think that it would be better to use [SemVer ](https://www.semver.org) for rust-analyzer version.

**Comment by lnicola** [comment]
> I think that it would be better to use [SemVer ](https://www.semver.org/)for rust-analyzer version.

I don't really understand what this means. If we add a new feature like an assist, are we supposed to bump the major version?

**Comment by Veykril** [comment]
One could argue we already kind of do semver releases, though not quite. We bump the patch version on every change which may add new user facing features, changes bugs and the like. Minor and major version bumps would be justified when we break/change/add to our VSCode extension API (which is considered fully unstable), config format (considered unstable though we try to not break it in a backwards incompatible manner) or lsp extensions (unstable). We could make an effort for stabilizing those things and then do proper versioning though I don't see any benefit in doing so.

**Comment by Alunderin** [comment]
As far as I can tell, this is because if you were to install rust-analyzer using rustup, the [standalone installers](https://forge.rust-lang.org/infra/other-installation-methods.html#standalone-installers) or a package manager that includes RA as part of Rust (e.g. [Gentoo](https://packages.gentoo.org/packages/dev-lang/rust-bin)'s), then you'll be getting a build from [rustc's subtree of RA](https://github.com/rust-lang/rust/tree/main/src/tools/rust-analyzer) instead of RA proper.
It's the same code, but when built as part of rustc it seems to inherit its [version number](https://github.com/rust-lang/rust/blob/main/src/version)(?).

> though I don't see any benefit in doing so.

Well, I just spent the past hour trying to figure out whether or not my version of rust-analyzer, 1.95.0 (2026-04-14), supports #11137. 1.95.0 was built 8 days after the release of [0.3.2854 (2026-04-06)](https://github.com/rust-lang/rust-analyzer/releases/tag/2026-04-06), so surely it would be included?
Nope! The RA subtree must have been slightly out of date at that point since the [relevant commit](https://github.com/rust-lang/rust/commit/b9acba65d21fcd6b512ca902243c89cb9183c48e) isn't actually present in the [1.95.0 tag](https://github.com/rust-lang/rust/commits/1.95.0/). Unless I'm missing something, I would have no way of knowing that without scouring the commit history for it.

That, and my initial confusion about getting a version completely different from anything mentioned in the [change-log](https://rust-analyzer.github.io/thisweek) or the [releases](https://github.com/rust-lang/rust-analyzer/releases) is, at least to me, plenty of reason why a consistent versioning scheme might be worth enforcing.

**Comment by lnicola** [comment]
> I just spent the past hour trying to figure out whether or not

Next time feel free to ask? Or simply test.

> 1.95.0 was built 8 days after the release of [0.3.2854 (2026-04-06)](https://github.com/rust-lang/rust-analyzer/releases/tag/2026-04-06), so surely it would be included?

No, it won't. The subtree is generally synced on Tuesday, but not always on every week. And even when it is, we don't backport new features onto the beta branch. Your 1.95 toolchain was branched on February 27, so it would not include anything merged into rust-analyzer in April.

The same actually applies to rustc, Cargo, Clippy and Miri, as far as I know.
