### ISSUE TITLE
renaming library/std items gets InvalidParams: Cannot rename non-local definition

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust-analyzer#17633]
Not all types inside libstd have set-in-stone names that cannot be changed: some are in fact quite arbitrary and deeply internal. It seems that because r-a precomputes `CrateOrigin::Lang` for std, rename-refactors will never work in libstd. This is because of https://github.com/rust-lang/rust-analyzer/pull/15232 I presume.

The "problem" is just that this is a very funny answer when the crate that you have a file open from is uhhh, rust/library/std and the file is library/std/src/sys/pal/unix/stack_overflow.rs and such.

I will go back to multicursor editing, I suppose.

**Comment by Veykril** [comment]
Yes that is known and we aren't going to fix that sorry. I've spent a lot of time trying to make the rustc workspace work nicely with r-a but I've given up, its just not a normal cargo workspace as much as bootstrap is trying to make it look like one. This will have to wait on https://github.com/rust-lang/rust/pull/120611 which hopefully fixes this by telling r-a the concrete structure of the workspace that bootstrap actually knows about (instead of us having to somehow emulate the same).
