### ISSUE TITLE
False positive diagnostic in proc-macro

### ISSUE THREAD

**Issue by laurmaedje** [rust-lang/rust-analyzer#17630]
On the [Typst codebase](https://github.com/typst/typst), rust-analyzer raises a false positive diagnostic since a while. The concrete error message (`typst: explicit parent type required (rust-analyzer macro-error)`) is specific to the codebase since it stems from a proc macro, but the important part is that the command line compiler doesn't produce this diagnostic.

I'm not sure when exactly the diagnostic started, but it used to work and if I switch back to a ~2 months old rust-analyzer release, it works again.

**rust-analyzer version**: 0.3.2037-standalone (https://github.com/rust-lang/rust-analyzer/commit/e9afba57a5a8780285f530172e3ceea1f9c7eff7 2024-07-14)

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VSCode, extension version v0.3.2037

**repository link**: https://github.com/typst/typst

**code snippet to reproduce**: `crates/typst/src/foundations/array.rs`

**Comment by Veykril** [comment]
The problem seems to be that we fail to resolve the `ty` and `scope` macros in the typst codebase. r-a seems to  get confused by the glob re-exports being shadowed by the same named modules

**Comment by Leedehai** [comment]
> r-a seems to get confused by the glob re-exports being shadowed by the same named modules

Hi, am I right to elaborate your finding like this: `crates/typst/src/foundations/ty.rs` re-exports the `ty` and `scope` macros, but since `crates/typst/src/foundations/mod.rs` have `mod ty;` and `mod scope;`, these macro names, which are exported by `pub use self::ty::*;` in that mod.rs file, are shadowed?

Further, I also tried adding `pub use typst_macros::{scope, ty};` directly in that mod.rs and the same issue remains.

**Comment by Veykril** [comment]
Yes, I don't know the exact problem here but the setup of the mod declarations + more visible re-exports is what seems to be tripping up rust-analyzer
