### ISSUE TITLE
Visual Studio Code Does Not Display "Learn about rust-analyzer" Welcome Page Read Only Paths Tip Correctly

### ISSUE THREAD

**Issue by bluk** [rust-lang/rust-analyzer#17788]
**rust-analyzer version**: rust-analyzer version: 0.4.2060-standalone (aa00ddcf6 2024-08-02)

**editor or extension**: 
```
Version: 1.92.0 (Universal)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z (3 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

I think you can get to the Welcome page in VS Code on a Mac via:

```Cmd+Shift P``` > `Welcome: Open Walkthrough...` > `Learn about rust-analyzer`

(I actually got to this page via a link on a general VS Code Welcome Overview page but I have no idea when/how this Welcome page displays this link).

Under the `Useful Setup Tips`, the paths that are displayed do not seem to be correct.

`/.cargo/registry/src//*.rs`
`/lib/rustlib/src/rust/library///*.rs`

Screenshot:

![Screenshot 2024-08-04 at 08 52 31](https://github.com/user-attachments/assets/f31bd946-a03c-48a4-a60b-6a7d5e550ccc)

Based on:

https://github.com/rust-lang/rust-analyzer/blob/aa00ddcf654a35ba0eafe17247cf189958d33182/editors/code/package.json#L3235

It seems the paths should be:

`**/.cargo/registry/src/**/*.rs`
`**/lib/rustlib/src/rust/library/**/*.rs`

Seems like the wrong rendering and an easy first issue.

**Comment by Craig-Macomber** [comment]
I got the same message when installing the the extension on linux. 

There are several issues here:

1. It looks like a json code block was attempted, but must not support triple back tick code blocks and seems to have instead parsed the triple back ticks as an empty code block followed by an unpaired back tick.
2. The double astrix are getting parsed as markdown bold instead of left as is.
3. The text is not selectable/copyable.
