### ISSUE TITLE
feat request: add to mod tree when create .rs file

### ISSUE THREAD

**Issue by Young-Flash** [rust-lang/rust-analyzer#18218]
we have `create_module` assist for unresolved module, which allow user just type `mod xxx;` in a .rs file and use the quickfix to create the corrsponding .rs file automatically.

maybe we could have a assist that automatically add the `mod xxx;` in parent module when user manually create a .rs file, [which alreay support by rust rover](https://blog.jetbrains.com/rust/2024/02/14/q4-2023-features-retrospective/#attaching-new-rust-file-to-module).

Is this make sense with you guys, if so I could have a try.

**Comment by Young-Flash** [comment]
Maybe we can pop up a window asking if they want to join the mod tree after the user creates .rs?(like what rust rover do)

**Comment by Veykril** [comment]
I don't think we have that option with the LSP

**Comment by Young-Flash** [comment]
https://github.com/rust-lang/rust-analyzer/blob/417ee6f04ac831839f415b361f4e94388a39dc58/crates/rust-analyzer/src/lsp/capabilities.rs#L93-L94

how about
```rust
did_create: Some(FileOperationRegistrationOptions {
                    filters: vec![FileOperationFilter {
                        scheme: Some(String::from("file")),
                        pattern: FileOperationPattern {
                            glob: String::from("**/*.rs"),
                            matches: Some(FileOperationPatternKind::File),
                            options: None,
                        },
                    }],
                }),
```

**Comment by Veykril** [comment]
I meant the pop up

**Comment by smheidrich** [comment]
Instead of a popup (which I agree doesn't seem possible given the current LSP spec), it would be cool if there was an opt-in config option to just do it automatically (without asking the user) whenever they add a new `.rs` file, with a user-configurable default choice for the [desired-visibility](https://github.com/rust-lang/rust-analyzer/blob/84e87d5bbaec992e7ded5e79988db2da6c129f6b/crates/ide-diagnostics/src/handlers/unlinked_file.rs#L289-L308) prompt that would pop up if one were to use the existing `unlinked-file` diagnostic's fix.

The existing diagnostic & fix are very useful, but as the existence of this issue shows, some users prefer not having to perform extra keystrokes for this.
