### ISSUE TITLE
rust-analyzer run multiple `cargo check` after I use goto-definition into dependencies

### ISSUE THREAD

**Issue by juchiast** [rust-lang/rust-analyzer#18215]
Every time I use goto-definition to go into a dependency, RA make a new `cargo check` command, the command is run even after I close that file.

How do I stop this from happening after I close the files from dependencies? I'm on neovim (coc and coc-rust-analyzer plugins). Restarting the server of reloading workspace didn't work, I have to close neovim and start a new one.

![Image](https://github.com/user-attachments/assets/a18f5429-0cbe-4f30-b8f7-4bc47573452a)

**Comment by Veykril** [comment]
That sounds like an editor issue, likely the editor is telling r-a the workspace has changed when you change the file (which it shouldn't)

**Comment by flodiebold** [comment]
It might be coc starting a new RA instance for the dependency?

**Comment by rahmonov** [comment]
+1

**Comment by davidbarsky** [comment]
It looks like `coc-rust-analyzer` calls this issue out [here](https://github.com/fannheyward/coc-rust-analyzer/tree/878c5a2ee023b4ad527ffa82828833159d5a2bb7?tab=readme-ov-file#notes). There was a discussion on [this issue](https://github.com/fannheyward/coc-rust-analyzer/issues/1117) and was fixed for non-vendored Cargo sources in https://github.com/neoclide/coc.nvim/pull/5084/. I'll close this issue as it's not something rust-analyzer could reasonably fix right now, but has been been fixed by `coc` and `coc-rust-analyzer`.
