### ISSUE TITLE
Debug use vscode lldb-dap extension

### ISSUE THREAD

**Issue by kouhe3** [rust-lang/rust-analyzer#18257]
Now we have  another lldb debug extension
https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.lldb-dap

Can we add this?

Just out of curiosity, this looks the same as codelldb

**Comment by kouhe3** [comment]
Well, Just to add, I prefer this official `lldb-dap` extension, which uses path's lldb instead of packaging `lldb.exe` and `Python39.dll` in vsix (Codelldb do this), it's smaller and Cross-platform

**Comment by lnicola** [comment]
Sounds good, do you want to file a PR? See https://github.com/rust-lang/rust-analyzer/blob/2b750da1a1a2c1d2c70896108d7096089842d877/editors/code/src/debug.ts#L222 and https://github.com/rust-lang/rust-analyzer/blob/2b750da1a1a2c1d2c70896108d7096089842d877/editors/code/src/debug.ts#L105.

**Comment by kouhe3** [comment]
I am writing, now can use lldb-dap + rust analyzer. But there are still some tasks todo. 
lldb-dap requires arrays for env and sourcemap, instead of dict.

**Comment by itrumper** [comment]
I am trying to use lldb-dap extension instead of CodeLLDB, but after uninstalling the CodeLLDB extension and configuring lldb-dap (set $PATH with the proper location for lldb-dap) I cannot get rust-analyzer to run the debug lens action. It compiles my program, but then before printing the generated debug configuration (in the output window of VScode) an error is generated saying, "Cannot read properties of undefined (reading 'uri')" with a button to open 'launch.json'.

Could you please share the configuration you are using with lldb-dap to work with rust-analyzer? Did I miss some configuration steps in the above?
