### ISSUE TITLE
Quickfix to turn manual counter into `.enumerate()` breaks existing code.

### ISSUE THREAD

**Issue by iago-lito** [rust-lang/rust-analyzer#18306]
RA offers a clever quickfix in the following situation:
```rust
fn f(v: Vec<u64>) {
    let mut i = 0;
    for e in &v {  // consider using: `for (i, e) in v.iter().enumerate()`
        println!("{i}: {e}");
        i += 1;
    }
}
```
But applying the quickfix breaks the code:
```rs
fn f(v: &[u64]) {
    let mut i = 0;
    for (i, e) in v.iter().enumerate() {
        println!("{i}: {e}");
        i += 1; // /!\ cannot assign twice to immutable variable `i`
    }
}
```

I would expect the quickfix to remove the original `i` variable?

```sh
$ rust-analyzer --version
rust-analyzer 1.83.0-nightly (eb4e234 2024-10-09)
$ rustc --version
rustc 1.83.0-nightly (eb4e23467 2024-10-09)
$ nvim --version
NVIM v0.11.0-dev-944+gb3109084c2
Build type: Release
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info
```

**Comment by ChayimFriedman2** [comment]
This diagnostic doesn't come from rust-analyzer, but from Clippy, which you probably configured to run on save. The fix is also provided by Clippy, and it is marked as MaybeIncorrect, so it is allowed to produce non-working code. As such, there is nothing we can do here. You can try report this to the Clippy devs, but I don't know if they have a way to declare a multi-range fix.

**Comment by iago-lito** [comment]
Okay, sorry for the noise. I've just repeated the issue there in case they have anything interesting to add :)
https://github.com/rust-lang/rust-clippy/issues/13572
