### ISSUE TITLE
Go to definition on `..`/`..=` should go to the corresponding `Range*` type

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18342]
As in `1..2` should go to `Range`, `1..` to `RangeExclusive` etc

**Comment by duncpro** [comment]
I'm going to work on this today.

@rustbot claim

**Comment by duncpro** [comment]
Like [Goto Type Definition](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_typeDefinition), the [Goto Definition](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition) request consists of a file id and then a cursor offset. 

Currently, Goto *Type* Definition links to `Range` in the following cases...

| Pattern       | Links to `Range*`  | Note                       |
| ----------- |------------------- | ------------------|
|  \|(a..b)       |  Yes                          |
|  \|a..b          |  No                           | (links to `a` instead)
|  a\|..b          |  No                           | (links to `a` instead)
|  a.\|.b          |  Yes                          | 
|  a..\|b          |  No                           | (links to `b` instead) 
|  a..b\|          |  No                           | (links to `b` instead) 
|  (a..b)\|       |  Sometimes             | (yes if followed by a space, no otherwise)

(I believe this behavior is a consequence of `SyntaxNode::token_at_offset`'s behavior.)

Right now Goto Definition never links to `Range`. Is our desire to simply make Goto Definition behave the same as Goto *Type* Definition currently does (for ranges)?

@Veykril Can you offer guidance?

**Comment by Veykril** [comment]
> (I believe this behavior is a consequence of SyntaxNode::token_at_offset's behavior.)

Yes it is, given the cursor is always in between two characters (not on a character) so there is some decision logic as to whether we consider the char to the left or right (which unfortunately can make things feel inconsistent at times)
