### ISSUE TITLE
VS Code: `Generate launch configuration` does not respect `RUSTUP_HOME` correctly

### ISSUE THREAD

**Issue by TheNathannator** [rust-lang/rust-analyzer#18468]
**rust-analyzer version**: 0.3.2162-standalone (3b3a87fe9 2024-10-27) (VS Code extension bundled)

**rustc version**: 1.82.0 (f6e511eec 2024-10-15)

**editor or extension**: VS Code, extension v0.3.2162

**platform**: Windows 10

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
- `CARGO_HOME`: `E:\.dots\.cargo`
- `RUSTUP_HOME`: `E:\.dots\.rustup`

---

Using the `Generate launch configuration` command in VS Code fails with the following output:

![Image](https://github.com/user-attachments/assets/8b3b48fe-5e3c-40cb-998e-200f5239ad26)

```
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
```

As best as I can tell, `RUSTUP_HOME` is being ignored, and it instead uses the default per-user location of `C:\Users\<user>\.rustup`. Deleting the per-user folder and running the command again will re-generate the folder, with a default `settings.toml` which contains only the following:

```toml
profile = "default"
version = "12"

[overrides]
```

Copy-pasting the contents of the `settings.toml` in my `RUSTUP_HOME` into this one makes it work, but it then installs an independent Cargo into my user folder and re-fetches dependencies to there, which is not ideal, as I moved the directory to a secondary drive due to the limited space on my primary drive.

**Comment by vrptnc** [comment]
I have a similar problem on Ubuntu 22.04. Whenever I try to run the "Generate launch configuration" task, it gives me:
`Cargo invocation has failed: Error: could not launch cargo: error: spawn cargo ENOENT`
I have debugged the extension and the problem seems to be in the `debug.ts` file. The [following change](https://github.com/rust-lang/rust-analyzer/commit/7e94f3fd3cbbb7d2d4f26a6a9e8559030408d3a0#diff-9602295c0f5a2832d525e142adddc64cba5a5586b4c367b84bd2ec159581f831R18) 3 months ago seems to have caused it.
As part of the `getDebugConfiguration` call, a cargo process is spawned, and as part of that child_process.spawn call, an env Object is passed along. This env object is created by the `prepareEnv` function in `run.ts`. Previously, all calls to that method would include the `process.env` environment in the generated env Object, which also means your PATH variable is passed along. Now, an `inheritEnv` parameter is used, which is set to `false` for the call made from `makeDebugConfig`. Which means that the `process.env` is not included, which means the spawned process isn't given your PATH env variable, which means it is never able to find the cargo executable.

The only way to remedy this is to set the `rust-analyzer.runnables.extraEnv` variable to include a copy of PATH (not that you can't use `{ "PATH": "${env:PATH}" }`, because the prepareEnv routine doesn't support interpolation of this variable).

I'm guessing your problem is related. You probably have your environment variables set correctly, but they just aren't passed along to the spawned cargo process.

**Comment by szszoke** [comment]
I am likely also affected by what @vrptnc described on Arch Linux. In my case the issue manifested as error running `rustc -vV` when run the `Generate launch configuration` command. The suggested fix of explicitly setting the `PATH` environment variable resolved the error and I was able to generate a launch configuration.

```bash
echo $PATH
```

```JSON
"rust-analyzer.runnables.extraEnv": {
  "PATH": "<output from echo $PATH goes here>"
}
```

**Comment by Veykril** [comment]
@vrptnc thanks for debugging this, I see the issue now. A fix is on the way
