### ISSUE TITLE
Could not debug, lldb

### ISSUE THREAD

**Issue by nephi-dev** [rust-lang/rust-analyzer#18535]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
rust-analyzer version: 0.3.2188-standalone (ba56d9b9b 2024-11-17) [c:\Users\matth\.vscode\extensions\rust-lang.rust-analyzer-0.3.2188-win32-x64\server\rust-analyzer.exe]
**rustc version**: (eg. output of `rustc -V`)
rustc 1.82.0 (f6e511eec 2024-10-15)
**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable)
VSCode
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
...
**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))
...
**code snippet to reproduce**: 
`Could not find LLDB data formatters in your Rust toolchain`, and after installing it, the same message appears again

**Comment by lnicola** [comment]
Which debugging extension are you using?

**Comment by josephgruber-umbra** [comment]
Just here to adds, I’m also seeing this issue. Also using rust-analyzer/CodeLLDB

**Comment by VincePayne42** [comment]
Also having this issue

**Comment by birne67** [comment]
Me as well.

**Comment by gbegerow** [comment]
+1 VSCode, CodeLLDB, Rust nightly, Full Visual Studio 2022 installed.

Loading Rust formatters from C:\Users\gbegerow\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/etc
Could not find LLDB data formatters in your Rust toolchain.  Consider installing the x86_64-pc-windows-gnu target by running `rustup target add x86_64-pc-windows-gnu`.

Maybe this is a conflict between LLDB and MSVC toolchain?

**Comment by Robo210** [comment]
As a workaround, copying the files from the windows-gnu\lib\rustlib\etc toolchain directory to the windows-msvc\lib\rustlib\etc directory makes the warning go away.

**Comment by Veykril** [comment]
Ah, https://github.com/vadimcn/codelldb/wiki/Windows#debugging-rust-on-windows talks about this, quoting:


## Debugging Rust on Windows
The default toolchain installed on Windows by Rustup is the `x86_64-pc-windows-msvc` toolchain. This toolchain does not include Rust-specific formatters for LLDB, as it is assumed that users will primarily use WinDbg or Microsoft Visual Studio's debugger for this target.
If you prefer to use CodeLLDB for debugging, you have two options:
1. **Use the `x86_64-pc-windows-gnu` toolchain to compile your Rust project**: This option ensures full LLDB visualization support for Rust types.
2. **Compile with the `x86_64-pc-windows-msvc` toolchain but use LLDB formatters from `x86_64-pc-windows-gnu`**: To use this option, install the `x86_64-pc-windows-gnu` toolchain via `rustup toolchain add x86_64-pc-windows-gnu`.
   Then, configure CodeLLDB to load its formatters by adding the following entry to your workspace configuration:
   `"lldb.script": { "lang.rust.toolchain": "x86_64-pc-windows-gnu" }`

   Note that this setup is less ideal due to differences in the debug information layout emitted by the Rust compiler for `enum` data types when targeting MSVC, which means enums may not be visualized correctly. However, LLDB formatters will work for standard collections like strings and vectors.

For more information on Rust toolchains for Windows, see the [Rustup Installation Guide for Windows](https://rust-lang.github.io/rustup/installation/windows.html).



I'll close this as this is not a rust-analyzer issue

**Comment by tanveerbadar** [comment]
> "lldb.script": { "lang.rust.toolchain": "x86_64-pc-windows-gnu" }

No longer works.

**Comment by OZ1** [comment]
Where is my workspace configuration? Where should I write that magic line to?
