### ISSUE TITLE
Request completionItem/resolve failed

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#18640]
This randomly occured, when it clearly shouldn't, not reproduction unfortunately
```
[Error - 9:18:48 AM] Request completionItem/resolve failed.
  Message: Import edit overlaps with the original completion edits, this is not LSP-compliant
  Code: -32603 
```

**Comment by SomeoneToIgnore** [comment]
This seems similar to what's been described in https://github.com/rust-lang/rust-analyzer/issues/18547#issuecomment-2525373488 and another implication of the issue with the completions resolve impl.

I liked the proposed hash lookup strategy, should we try to implement that, instead of the caching approach?

**Comment by Veykril** [comment]
Yes let's do that, the server is stateless wrt to requests so the caching would be quite annoying to implement I think (and we probably don't want to do that)
