### ISSUE TITLE
internal error: entered unreachable code: mapping more input nodes than there are output nodes

### ISSUE THREAD

**Issue by noakodaren** [rust-lang/rust-analyzer#18780]
**rust-analyzer version**: [rust-analyzer 0.3.2228-standalone](https://github.com/rust-lang/rust-analyzer/releases/download/2024-12-23/rust-analyzer-x86_64-unknown-linux-gnu.gz)

**rustc version**: rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: neovim 0.10.3

**relevant settings**: no configuration

**code snippet to reproduce**: 
```rust
fn f() {
    match () {
        _ => {
            //{
        }
        _ => (),
        _ => Ok(())
    }
}
```
If I uncomment the commented line, rust-analyzer immediately panics:
```
Panic context:
> 
version: 0.3.2228-standalone
request: textDocument/diagnostic DocumentDiagnosticParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/noa/programmering/rust/rust_analyzer_tests/test1/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    identifier: None,
    previous_result_id: None,
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at /__w/rust-analyzer/rust-analyzer/crates/syntax/src/syntax_editor/mapping.rs:249:21:
internal error: entered unreachable code: mapping more input nodes than there are output nodes
stack backtrace:
   0:     0x63408edcd2ca - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x63408d7a5853 - core::fmt::write::h7550c97b06c86515
   2:     0x63408edc90d3 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x63408edcd122 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x63408edce5e4 - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x63408edce42e - std::panicking::default_hook::hf614597d3c67bbdb
   6:     0x63408edeff82 - stdx::panic_context::PanicContext::init::{{closure}}::h81e99e619f2e422b
   7:     0x63408edcec58 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   8:     0x63408edce9f6 - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
   9:     0x63408edcd779 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
  10:     0x63408edce6cc - rust_begin_unwind
  11:     0x63408d66b430 - core::panicking::panic_fmt::h0c3082644d1bf418
  12:     0x63408e5ca2f8 - syntax::syntax_editor::mapping::SyntaxMappingBuilder::map_children::h087f721edb3c0c6b
  13:     0x63408e5b1771 - syntax::ast::syntax_factory::constructors::<impl syntax::ast::syntax_factory::SyntaxFactory>::block_expr::hd3c4c772b6bc3681
  14:     0x63408e5b95a6 - ide_diagnostics::handlers::type_mismatch::fixes::h546b7e3f50072574
  15:     0x63408e5b61d8 - ide_diagnostics::handlers::type_mismatch::type_mismatch::h698df6eb12af0586
  16:     0x63408e60cd3e - ide_diagnostics::semantic_diagnostics::hda736b9454de8d0a
  17:     0x63408e60dce2 - ide_diagnostics::full_diagnostics::hd76f7b730df90d70
  18:     0x63408e11fc99 - ra_salsa::Cancelled::catch::h06d1d3b161f0a434
  19:     0x63408e09b251 - ide::Analysis::full_diagnostics::h8256a1075adf99ea
  20:     0x63408ea5f2bc - rust_analyzer::handlers::request::handle_document_diagnostics::h5bfe17171d2d1cc5
  21:     0x63408e937ae7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hca2123e5a267f936
  22:     0x63408edee806 - std::sys::backtrace::__rust_begin_short_backtrace::h23ecc61d03986826
  23:     0x63408edecea5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h436c9b879a2d4f80
  24:     0x63408edd309b - std::sys::pal::unix::thread::Thread::new::thread_start::hcc78f3943333fa94
  25:     0x77669ceae39d - <unknown>
  26:     0x77669cf3349c - <unknown>
  27:                0x0 - <unknown>
```

**Comment by ChayimFriedman2** [comment]
So... it appears this is quite a big problem.

In summary: in the new `SyntaxMappingBuilder`, we need to map between new and old nodes. The new nodes are created with `make`. The problem in this case, and I suspect in many unknown others, is that the code is invalid, causing parser recovery to kick in. The first time parser recovery enters the picture is when parsing the original code. It causes the block to have few nodes, including some error nodes. The following is the statement list:
```
[
    EXPR_STMT@51..62
      BLOCK_EXPR@51..62
        STMT_LIST@51..62
          L_CURLY@51..52 "{"
          WHITESPACE@52..61 "\n        "
          R_CURLY@61..62 "}"
    ,
    EXPR_STMT@71..72
      UNDERSCORE_EXPR@71..72
        UNDERSCORE@71..72 "_"
    ,
    EXPR_STMT@76..78
      TUPLE_EXPR@76..78
        L_PAREN@76..77 "("
        R_PAREN@77..78 ")"
    ,
]
```
Importantly, this omits the `=>` tokens, which are marked inside `ERROR` nodes (and thus not statements). But when we call `make::block_expr()` with this statement list, and due to `make` being textual, it returns the following statements list:
```
[
    EXPR_STMT@6..17
      BLOCK_EXPR@6..17
        STMT_LIST@6..17
          L_CURLY@6..7 "{"
          WHITESPACE@7..16 "\n        "
          R_CURLY@16..17 "}"
    ,
    EXPR_STMT@22..30
      CALL_EXPR@22..30
        UNDERSCORE_EXPR@22..23
          UNDERSCORE@22..23 "_"
        WHITESPACE@23..28 "\n    "
        ARG_LIST@28..30
          L_PAREN@28..29 "("
          R_PAREN@29..30 ")"
    ,
]
```
Notably, the two last statements were unified into one, because without the `=>`, parser recovery marks them as one. And so we have a mismatch in the mapping, which leads to the panic.

This is pretty inherent to how `make` is operating, and I don't really have an idea how to fix this other than rewrite `make` to something more sensible. @Veykril do you have an idea?

**Comment by Veykril** [comment]
Oof that is annoying. Well, the make  API was always meant to be replaced by something that does not do this textual reparsing but instead re-uses the nodes properly. That is supported by rowan, it is just a bit more annoying to do (where as the textual stuff was easily done). I do recall trying to generate the make constructors from the grammar in https://github.com/rust-lang/rust-analyzer/pull/6532 (where the generated stuff would be using proper rowan re-constructions), but I ran into problems with fully generating that. Either way if you have a look at the generated make.rs file in there https://github.com/rust-lang/rust-analyzer/pull/6532/files#diff-853cc186b7361590869ff003b9fa4987fbf308363e048c3547bd9e0b04067d0c that is what these functions ought to be actually doing instead of being re-parsed. Maybe its good enough for us to migrate the current make stuff to it in a manually written manner for now for the ones we have, as I don't think we want to generate these from the grammar until we have switched over to the new trivia model as that will force us to change a couple of ungrammar grammar rules (it has more restrictions on how a node can look like in terms of composition).
