### ISSUE TITLE
Every time there's an update, the extension stops working until I install it

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust-analyzer#3617]
I don't know if this is intended behaviour, but frequently I'll open my editor (VSCode) and find that the extension just isn't working at all. If I restart it I get the notification that a new version of rust-analyzer is available and the option to download it. If I do, the extension starts working again.

I don't know why rust-analyzer can't keep working in the meantime though?

**Comment by bjorn3** [comment]
The extension and the language server have to be kept in sync as rust-analyzer often creates extensions to the lsp protocol to implement certain features.

I think the extension should tell about the new version of the language server the first time you open vscode after an update though.

**Comment by Veetaha** [comment]
Hmm... I need more info. Might I ask you to add
```json
{
    "rust-analyzer.trace.extension": true
}
```
to your `settings.json` and send the logs from `Help > Toggle Developer Tools > Console` when this happens again?

**Comment by Veetaha** [comment]
Also, how frequently that happens? It is expected that you get the `Download now` suggestion to install the server every monday when we make new releases (if you open rust projects in vscode on mondays).

**Comment by Diggsey** [comment]
> I think the extension should tell about the new version of the language server the first time you open vscode after an update though.

It's possible that it is showing it and that I'm just not seeing it because I'm not looking at VSCode when it pops up. Does it have a timeout on the message or something?

> Hmm... I need more info.

I've enabled that option.

> Also, how frequently that happens? It is expected that you get the Download now suggestion to install the server every monday when we make new releases.

That sounds about right. It happened today and the time before was probably a week ago.

**Comment by Veetaha** [comment]
My diagnose is that you might miss that `Download now` popup. It is not dismissed automatically, `vscode` just minimizes it to notifications bell button in the right bottom edge:
![image](https://user-images.githubusercontent.com/36276403/76807443-0494eb80-67ed-11ea-8596-b905a5adb3ce.png).

If you open the notifications list next time you have this behavior, you should see the download proposal there.
This is actually very important since you cannot use `rust-analyzer` if you don't download the proper language server version so the whole application actually waits for your attention on that notification...

My suggestion for your particular issue would be to disable that notification and always download the server automatically:
```json
{ "rust-analyzer.updates.askBeforeDownload": false }
```

I know you will not like it @matklad, but make the users draw attention to the notification we may make it a modal window. So... since you don't like it (and neither do I) I see another option: add a timeout so when the user doesn't see the notification we recreate it in a loop so that it stays visible and never minimised.

**Comment by Diggsey** [comment]
That sounds plausible to me: might I suggest putting a yellow or red warning sign in the status bar when the extension is not able to work for whatever reason?

**Comment by lnicola** [comment]
@Diggsey are you still having trouble?

**Comment by damccull** [comment]
Maybe change the notification's text, as well. "The rust-analyzer language server version x.x.x.x is not installed." is confusing until you read an issue like this where there's a bit of explanation. For months I've been like "Yes, it is you stupid machine. I just installed it last week!" without ever realizing it was getting updates.

I suggest some kind of text like: "There is an updated version of the language server (version x.x.x.x) that must be downloaded before rust-analyzer can be used."

**Comment by Veykril** [comment]
This is no longer a problem now that the server ships with the extension.
