### ISSUE TITLE
Assist: create field in struct definition

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust-analyzer#4563]
It'd be cool if rust-analyzer could jump to creating a new field when I reference a field which doesn't exist.

Before:
```rust
#[derive(Default)]
struct Config {
    opt1: u32,
    opt2: u32,
}
fn main() {
    let conf = Config::default();
    let my_thing = conf.opt3<I>;
}
```
After:
```rust
#[derive(Default)]
struct Config {
    opt1: u32,
    opt2: u32,
    opt3: <I>,
}
fn main() {
    let conf = Config::default();
    let my_thing = conf.opt3;
}
```

It'd be cool if rust-analyzer could figure out the type rust expects `opt3` to be, and autocomplete that (selecting it after), but I think that's optional. That would be a completion like this:

Before:
```rust
#[derive(Default)]
struct Config {
    opt1: u32,
    opt2: u32,
}
fn main() {
    let conf = Config::default();
    let my_float: f32 = conf.opt3<I>;
}
```
After:
```rust
#[derive(Default)]
struct Config {
    opt1: u32,
    opt2: u32,
    opt3: <f32>(type is selected),
}
fn main() {
    let conf = Config::default();
    let my_float: f32 = conf.opt3;
}
```

My main experience using this has been with IntelliJ's Java support.

Before:
![image](https://user-images.githubusercontent.com/1152146/82620130-9d007100-9b8c-11ea-9126-2596edab12c2.png)
After:
![image](https://user-images.githubusercontent.com/1152146/82620296-f49edc80-9b8c-11ea-84cc-1cc887183906.png)

Let me know if there's anything else I can do to support this feature request.

**Comment by matklad** [comment]
Yup, we need this. cc @TimoFreiberg who implemented similar feature for functions. 

In general, I feel like this shouldn't really be an assist, but a quick-fix for a diagnostic about unreoslved reference. And we should probably have a separate `crete_from_usage` module to handle all similar cases...

**Comment by matklad** [comment]
Marking both medium and hard:

* medium because just writing code to do this is not to hard, it's possible to just drop more stuff into ra_assisrs
* hard because for long-term sustainability we really need an infrastructure here.

**Comment by TimoFreiberg** [comment]
Sounds like a good plan :+1: I also think this needs some infrastructure.
I wasn't really aware of the differences between assists and quick-fixes until now, so I'm definitely still missing some knowledge about the current state - I'm probably going to try and get some feedback from you or the other experienced team members about any nontrivial designs before I build anything big :sweat_smile:

**Comment by matklad** [comment]
Yup, so assists and quick fixes are indeed similar things, but annoying different things. Both are code transformation. 

QuickFixes are responses for diagnostics. That is, on every change we compute the full set of errors, and than for some errors we produce quick fixes. QuickFixes also can make use of information collected when detecting errors (see, for example, downcasting [here](https://github.com/rust-analyzer/rust-analyzer/blob/f4f5fca10175b8d5fdfa36563c103f81b2b0acd3/crates/ra_ide/src/diagnostics.rs#L75-L105)).
 QuickFixes also should be actual fixes (ie, they should make code more correct).

Assists are just contextual helpers. They are not computed for the whole file, they are always computed at the specified cursor position. They also don't need to fix anything, they can just be potentially useful transformations.

I guess, my original though was that QuickFixes are computed eagerly on change, while assists are computed lazily for cursor position. Now that I think about it, I wonder if it makes sense to compute fixes lazily as well? We can compute them like quick-fixes, but, instead of the current cursor position, we can stuff current diagnostics into the assist context.

**Comment by wyatt-herkamp** [comment]
Hey, I would like to claim this issue. I have it partly working. I don't know how to make the caret go to the line that was added so that the user can specify the type?

https://github.com/rust-lang/rust-analyzer/assets/11785959/8231dee4-b2da-43f5-9e23-f35a1753e30c

@rustbot claim

**Comment by Veykril** [comment]
You want to look into how r-a handles `snippet`s/`SnippetCap`, that's what allows moving the cursor.
