### ISSUE TITLE
🙏🏻 REQ/enhancement: Add "Rust Analyzer: stop server" command

### ISSUE THREAD

**Issue by rivy** [rust-lang/rust-analyzer#4697]
The analyzer takes a  lot of resources and that sometimes gets in the way of rapid iteration.
I would like to have the option to stop the service in those cases.

**Comment by ruabmbua** [comment]
The vscode C++ plugin adds a button the C/C++ menu in the bottom right to stop / restart analysis.

**Comment by rivy** [comment]
If this isn't going to be implemented, how about adding a user-customizable delay after file saves before re-compiling? That would allow faster CLI recompiles and code iteration.

**Comment by OWissett** [comment]
I am often finding myself writing code on the train (and subsequently having very slow internet). This is an issue with the rust analyzer, since it takes a slow time for it to fetch the metadata, and blocks me from doing other things, which is somewhat frustrating. I appreciate that this is probably not a very common problem (and I should probably just not write code on the train so much), however, this feature would be nice.

**Comment by lnicola** [comment]
@OWissett you still need that metadata to compile your code. RA just does it a bit earlier.

**Comment by OWissett** [comment]
Is it required for the install of new crates? Since it would be convenient to be able to install new crates, so I can start writing code whilst the metadata is fetched. I admit I am not thoroughly acquainted with how the RA works.

**Comment by lnicola** [comment]
Yes, it's required in order to load the project. There's some discussion in https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/how.20to.20fix.3A.20.20blocking.20waiting.20for.20file.20lock.20on.20build.20di.2E.2E.2E.

**Comment by OWissett** [comment]
Ah, thanks for the speedy replies.
