### ISSUE TITLE
Open VSX Registry: Awareness and Important Steps

### ISSUE THREAD

**Issue by brianking** [rust-lang/rust-analyzer#7284]
@hybras has published this extension in the [Open VSX Registry](https://open-vsx.org/extension/matklad/rust-analyzer).

The service was recently transferred to the Eclipse Foundation and we want to ensure a seamless transition for our users. To ensure uninterrupted service and more exposure for your extension, I recommend the following.

**To the maintainers**: If you would like to take over publishing to open-vsx.org, here’s how: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**To the current publisher**: Please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf). The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

**Claiming ownership of the namespace for your extension(s)**. To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access
As owner you can add more namespace members (including service accounts) yourself in https://open-vsx.org/user-settings/namespaces. Note that publishing can be done by any contributor to the extension, namely those you add as namespace members once they have signed the Publisher Agreement as well.

Please also note that a license is now mandatory for publishing your extension to Open VSX. If your project doesn't have any license, please add one, preferably an [open source license](https://opensource.org/licenses) such as MIT. The publishing tool [ovsx](https://www.npmjs.com/package/ovsx) offers to automatically add the MIT license when you try to publish without a license.

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. We hope you join us on this journey as we continue to build the Open VSX community. 
We look forward to continued innovation from you in 2021!

**Comment by hybras** [comment]
Omg I completely forgot about this... Some more context:

I while ago I set up a GitHub action at [this since deleted repo](https://github.com/hybras/Rust-Analyzer-Open-Vsix) to publish the RA extension to Open VSX Registry, a store of extensions for open source VS Code forks (like vs codium). Since then, the registry came under new management and publishers needed to sign the linked agreement. I did not, having gone back to using vs code and forgetting about my action. Since then, it has been autopublished by open vsx's own bot, becoming abandonware. This all happened without the knowledge of anyone here (I think I asked around in the rust zulip before publishing if anyone wanted to do this, and decided to go ahead anyways)

I've since lost the source code (idk why I deleted the repo?). If anyone else wants to keep publishing the extension to open vsx, I can help in recreating the github action I made. My apologies for not keeping up with the publishing beforehand

**Comment by bjorn3** [comment]
Depending on when you deleted the repo, it may still be restorable at https://github.com/settings/deleted_repositories. According to https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/restoring-a-deleted-repository you have 90 days the time after deletion.

**Comment by hybras** [comment]
I've restored the repo, it says it may take up to an hour. I will disable my publishing action. The only benefit to keeping it running would be to claim ownership, since its now being autopublished by open vsx. 

[Issue 4936](https://github.com/rust-analyzer/rust-analyzer/issues/4936) explains why you weren't already publishing yourselves (mainly the extra work associating with publishing).

**Comment by Progdrasil** [comment]
Would this change the stance from #4936? Since i'm using the VsCode build from my package manager i've stopped getting updates from Rust-Analyzer.

**Comment by nyanpasu64** [comment]
If there was supposed to be an auto-publishing system, I think it's broken; https://open-vsx.org/extension/matklad/rust-analyzer is now outdated (0.2.637) compared to https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer (0.2.678), and Arch's vscode-oss has stopped getting updates.

**Comment by brianking** [comment]
Related issue:
https://github.com/open-vsx/publish-extensions/issues/342

I suggest filing a new issue there.

**Comment by lnicola** [comment]
@matklad I think we should look into this. The Marketplace split is unfortunate, but VSCodium seems to be getting more and more popular and it seems unfair to exclude those users.

If we do this, we'll probably vendor `publish-vscode-extension`, like we did with `gihub-release`.

**Comment by matklad** [comment]
sgtm! Is the `publish-vscode-extension` github action required? Or can we add `ovsx` as a dev dependency and add an extra line here https://github.com/rust-analyzer/rust-analyzer/blob/3c5827cc18e0d1f0ec9fe32f731a362d27f2cfae/.github/workflows/release.yaml#L322 ?

**Comment by bjorn3** [comment]
`ovsx` is used for the actual publishing it seems.

**Comment by cortopy** [comment]
The version in vsx registry is now well behind current: 0.2.784 vs 0.2.817

Would it be possible to update it?

**Comment by lnicola** [comment]
@hybras (or anyone else), do you know if Open VSX supports the platform-specific extensions introduced in https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions?

CC #11080

**Comment by brianking** [comment]
> @hybras (or anyone else), do you know if Open VSX supports the platform-specific extensions introduced in https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions?

Not yet (and no timeframe currently). It is being tracked at https://github.com/eclipse/openvsx/issues/336

**Comment by hybras** [comment]
I'm no longer interested in publishing RA to open vsx. please do not ping me

**Comment by lnicola** [comment]
Sorry to bother you, then.

I still think this is something we should do, after the `openvsx` issues get sorted out.

**Comment by lnicola** [comment]
@matklad would you be able to make an open-vsx.org account, get an access token, maybe claim the `rust-analyzer` namespace (I'm not sure how that works, though), and add it to the secrets on GitHub Actions?

This isn't urgent, as I suspect https://github.com/eclipse/openvsx/issues/336 will take more time to be implemented, but it would be nice to be prepared by then.

**Comment by lnicola** [comment]
@matklad never mind, I've made an account for myself.

**Comment by jonas-schievink** [comment]
Now that we'll publish under `rust-lang.rust-analyzer` instead of `matklad.rust-analyzer` on the VS Code marketplace, we should probably get the `rust-lang` namespace claimed on Open VSX too (not sure which account should own it though). I guess we'll see how well Open VSX handles the publisher move on monday.

**Comment by lnicola** [comment]
`rust-lang.rust-analyzer` is now available on OpenVSX as a pre-release version. If nothing goes wrong, a stable release will be published as usual, next Monday.

Note that if you're still running `matklad.rust-analyzer`, it won't be automatically updated to the new version.
