### ISSUE TITLE
Constants in arrays are not resolved yet

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust-analyzer#7432]
Const generics highlighting is still very new, so this is kinda expected to not really work fully yet. One case I've noticed are constants in arrays:

![https://i.imgur.com/9633wVv.png](https://i.imgur.com/9633wVv.png)

Neither const generics nor normal constants are resolved (unresolvedReference / brown color).

**Comment by Veykril** [comment]
The problem here is that we don't lower const param expressions yet(regarding arrays we actually just discard the length expression entirely), so this case here also doesn't properly resolve, notice the const param of the return type not being highlighted:
![image](https://user-images.githubusercontent.com/3757771/105767751-b51a6280-5f5b-11eb-84b5-51a9bb84b8fa.png)

The only reason why it works for simple const params that are just a path is that they are actually parsed as type args instead.

**Comment by Veykril** [comment]
Blocked on #7434

**Comment by Veykril** [comment]
With https://github.com/rust-analyzer/rust-analyzer/pull/11915 we should mostly resolve the paths in that position for IDE purposes (opposed to type checking and such)

**Comment by lnicola** [comment]
The original examples are now working, let's close this:

![image](https://github.com/user-attachments/assets/45f1af33-5386-4de9-be02-1063539c232b)
