### ISSUE TITLE
Load crates.io dependencies of the standard library

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust-analyzer#7637]
The standard library may depend on crates from crates.io, and some of them can be required to properly analyze libstd, like `cfg_if`, which caused https://github.com/rust-analyzer/rust-analyzer/issues/6038 in the past. We currently use a hard-coded dependency graph for the sysroot, but have no mechanism to detect or obtain the sources of crates.io dependencies.

We should figure out a way to properly solve this. There are a few options:

* The `rust-src` component could vendor the sources of crates.io dependencies (this seems insufficient though, we might still need to address one of the points below).
* We can use the Cargo.lock of the rust-lang/rust monorepo to resolve libstd dependencies via `cargo metadata`, but this requires creating a temporary directory or mutating rustup-installed directories, which is a bad idea.
* The compiler and standard library could be split into 2 workspaces, each with their own `Cargo.lock`. Then we could run `cargo metadata --locked` without requiring any disk operations besides index and crate downloads.

**Comment by jyn514** [comment]
> We can use the Cargo.lock of the rust-lang/rust monorepo to resolve libstd dependencies via cargo metadata, but this requires creating a temporary directory or mutating rustup-installed directories

Why does this require mutating rustup directories? Why doesn't cargo metadata --locked work?

**Comment by jonas-schievink** [comment]
Because the lockfile is in `$SYSROOT/lib/rustlib/src/rust/Cargo.lock`, while the manifest of libstd is in `$SYSROOT/lib/rustlib/src/rust/library/std/Cargo.toml`. Running `cargo metadata --locked` expects the lockfile to be next to `Cargo.toml` (because the workspace configuration is not shipped with rust-src either).

**Comment by jyn514** [comment]
Would it help if rust-src shipped with a symlink from Cargo.lock to library/std/Cargo.lock? That would be a lot easier than separating the standard library into its own workspace.

**Comment by jonas-schievink** [comment]
The lockfile is currently shipped as part of the `rustc-src` component, so I think we'd have to duplicate that. It seems that even then, `cargo metadata --locked` will fail, since the lockfile contains all compiler dependencies too and would have to be updated to just contain libstd dependencies.

**Comment by Aaron1011** [comment]
@jonas-schievink What's the current status of this issue? Setting `RustcSource::Discover`, it looks like rust-analyzer was able to run `cargo metadata` successfully.

**Comment by bjorn3** [comment]
That only works for rust**c**-src, not rust-src as most people will have.

**Comment by Veykril** [comment]
Opened a zulip stream for discussion: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/rust-lang.2Frust.2Flibrary.20workspace

**Comment by Veykril** [comment]
A previous attempt at this (with corresponding discussion) can be found here https://github.com/rust-lang/rust/pull/76533

**Comment by HKalbasi** [comment]
> We can use the Cargo.lock of the rust-lang/rust monorepo to resolve libstd dependencies via cargo metadata, but this requires creating a temporary directory or mutating rustup-installed directories, which is a bad idea.

How bad it is? I can guess that mutating rustup-installed directories is very bad, and temporary directory per each project can consume disk space and make start time worse, but what is the problem with a global directory which contains one std source and it dependencies for each toolchain?

**Comment by Veykril** [comment]
Mutating the rustup install directory is a no-go. Dropping things in the target dir would be okay, but I looked into that at some point and the way cargo works I couldn't make it work.

> but what is the problem with a global directory which contains one std source and it dependencies for each toolchain?

I'm not sure I understand what you mean with this

**Comment by HKalbasi** [comment]
> Dropping things in the target dir would be okay, but I looked into that at some point and the way cargo works I couldn't make it work.

I copied my `~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src` directory into a temp directory, then added this `Cargo.toml` file to it:
```toml
[workspace]
members = [
    "library/alloc",
    "library/core",
    "library/panic_unwind",
    "library/proc_macro",
    # "library/rtstartup",
    "library/rustc-std-workspace-core",
    "library/std",
    "library/test",
    # "library/backtrace",
    "library/panic_abort",
    # "library/portable-simd",
    "library/profiler_builtins",
    "library/rustc-std-workspace-alloc",
    "library/rustc-std-workspace-std",
    # "library/stdarch",
    "library/unwind",
]
```
(backtrace and portable-simd are workspace themselves, and rtstartup and stdarch didn't have a `Cargo.toml`)

Then `cargo metadata` in that directory printed some json (I can provide it if helps), and r-a was able to resolve `hashbrown` from the `alloc` inside it. Does it mean anything? I'm pretty clueless about how things work and should work in cargo and `CrateGraph`.

> I'm not sure I understand what you mean with this

It was just a suggestion to improve performance, by sharing those temp directories. We can go with per project local temp directory at first if it is acceptable.

**Comment by Veykril** [comment]
Ah, I only tried to synthesize the Cargo.toml but keeping the source in the sysroot which unfortunately does not work because cargo expects certain filesystem hierarchies. I am not sure I like copying around the entire sysroot source on every project load (nor synthesizing a custom sysroot with proper cargo setups globally somewhere as this will be tricky to handle properly)

**Comment by lnicola** [comment]
Maybe we could make some symlinks to the sources instead of making a copy?

**Comment by HKalbasi** [comment]
Using symlinks instead of copy also work for me on linux. For the record, I created a symlink to the `library` folder (which is inside the folder I copied above), and copied the `Cargo.lock` next to it. I didn't create a symlink to the `rust` directory to keep it unchanged. It worked exactly like above.

**Comment by Veykril** [comment]
Turns out https://github.com/rust-lang/rust/pull/108865 added a sysroot crate which brings us closer to supporting this as we can run cargo metadata against that file (meaning we only get the std library dependencies). We still have the problem of no lock file being present though which means we can't run metadata as there is no `dry` run mode.

**Comment by j-h-a** [comment]
Forgive my incompetence and ignorance on this, I'm guessing that the source in `~/.rustup` is a snapshot of the installed toolchains, and since these are managed by rustup, could there not be a rustup command (or it could just do it by default) to pull the Cargo.lock file for the correct release, and put it where it needs to go?

I'm thinking maybe it would also need to do something to ensure the cargo-managed sources were pulled into `~/.cargo` (maybe create a dummy project with all the correct dependencies and build it - or something less dumb if a better command exists).

Then the file mapping that @HKalbasi mentioned above plus the Cargo.lock file could be applied, and `rust-analyzer` would work... right? So this is more of a `rustup` issue than `rust-analyzer`?

**Comment by lnicola** [comment]
@j-h-a if that lockfile existed, it would already be installed in the sysroot, so `rustup` wouldn't have to do anything extra. But since it doesn't exist, `rustup` has no way of downloading it.
