### ISSUE TITLE
Remove Result fix changes signature

### ISSUE THREAD

**Issue by jan-auer** [rust-lang/rust-analyzer#7713]
When using "remove `Result` from the return type", the return type signature is changed:
- Inside modules, the full path to the module is added, which may not be in scope
- `Self` and `type` aliases are replaced with the name of the type

## Example

```rust
mod foo {
    struct Foo;

    impl Foo {
        fn create() -> Result<Self, ()> {
            Ok(Self)
        }
    }
}
```

## Actual Result

```rust
mod foo {
    struct Foo;

    impl Foo {
        fn create() -> foo::Foo {  // failed to resolve: use of undeclared crate or module `foo` 
                                   // use of undeclared crate or module `foo`rustcE0433
            Ok(Self)
        }
    }
}
```

## Expected Result

```rust
mod foo {
    struct Foo;

    impl Foo {
        fn create() -> Self {  // or `Foo` would be correct, but the ideally the same alias is used
            Ok(Self)           // the error in this line is fine for this fix
        }
    }
}
```

**Comment by lnicola** [comment]
I have a feeling this might be related to #1666.

**Comment by flodiebold** [comment]
Hm. That we're replacing `Self` by the actual type is #1666, though we could maybe fix that in this case by doing the transformation syntactically instead of going by the type. That we're qualifying the name wrongly is a separate bug; it seems we're using the scope of the containing file instead of the specific location of the function. That would also be fixed by simply doing the transformation syntactically and not qualifying though.

**Comment by jan-auer** [comment]
The challenge with syntactic transformations could be type definitions on the result type, such as `anyhow::Result` or `io::Result`, where the `Ok` type may not be part of the original syntax.
