### ISSUE TITLE
Duplicate `Some` in match, visible tab stops

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#9085]
![image](https://user-images.githubusercontent.com/308347/120221212-a8c64f00-c246-11eb-8ffb-0bd12c7f54e8.png)

**Comment by Veykril** [comment]
The first completion here is the pattern completion, which currently renders the tabstops in there because I wasn't sure how to show that better and still don't. The second completion is the normal completion which with call parens enabled is almost the same as we add the parens for tuple structs/variants in that case as well.

So we probably should remove the latter if its in pattern position as these are basically duplicates in this specific case.

**Comment by Veykril** [comment]
Closing as this is intentional given my previous comment
