### ISSUE TITLE
Cannot find current rust-analyzer version in VS Code

### ISSUE THREAD

**Issue by ChaiTRex** [rust-lang/rust-analyzer#9336]
According to [the troubleshooting section in the rust-analyzer manual](https://rust-analyzer.github.io/manual.html#troubleshooting), the rust-analyzer version in VS Code can be found by:

> Start with looking at the rust-analyzer version. Try `Rust Analyzer: Show RA Version` in VS Code...

However, it's completely unclear where to find that in VS Code. It doesn't appear in the lightbulbs next to code. It doesn't appear in any of the window menus. It doesn't appear in `File > Preferences > Extensions > rust-analyzer`.

Please add where that option appears on that web page section, perhaps with a screenshot.

**Comment by lnicola** [comment]
You can access the command panel by pressing F1. If you type "Show RA Version" and it doesn't show up, it might have been removed. In that case, you can show the Output window ("Show Output"), then pick "Rust Analyzer Client" from the top-right list.

**Comment by tcmal** [comment]
I think there might be some issue with the latest release. Using NixOS, The dev console shows:

```
Extension 'matklad.rust-analyzer cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
abstractExtensionService.ts:909 [matklad.rust-analyzer]: configuration.properties property '$generated-start' must be an object
abstractExtensionService.ts:909 [matklad.rust-analyzer]: configuration.properties property '$generated-end' must be an object
mainThreadExtensionService.ts:95 Activating extension 'matklad.rust-analyzer' failed: Cannot find module '/nix/store/55a4nnzai8a725v4l5cngnnavmxp4awq-vscode-extensions/share/vscode/extensions/matklad.rust-analyzer/out/src/main'
Require stack:
- /nix/store/v8mi5lfsk98jrpd1k4x5h7bdlall2w5g-vscode-1.57.0/lib/vscode/resources/app/out/vs/loader.js
- /nix/store/v8mi5lfsk98jrpd1k4x5h7bdlall2w5g-vscode-1.57.0/lib/vscode/resources/app/out/bootstrap-amd.js
- /nix/store/v8mi5lfsk98jrpd1k4x5h7bdlall2w5g-vscode-1.57.0/lib/vscode/resources/app/out/bootstrap-fork.js.
```

because the src folder is missing entirely:

```
$ ls /nix/store/csrd2c619yp5dz09mcrxq108r7ff79i3-vscode-extension-rust-analyzer-2021-06-07//share/vscode/extensions/matklad.rust-analyzer/                                                                                                                                                        
icon.png  language-configuration.json  package.json  package-lock.json  ra_syntax_tree.tmGrammar.json  README.md
```

I would file this with nixpkgs, but it looks like their packaging code ([1](https://github.com/NixOS/nixpkgs/tree/bad3ccd099ebe9a8aa017bda8500ab02787d90aa/pkgs/misc/vscode-extensions/rust-analyzer) [2](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/tools/rust/rust-analyzer)) hasn't changed in months, and this only started the latest update for me.

All this code does is clone [rust-analyzer/rust-analyzer at 2021-06-07](https://github.com/rust-analyzer/rust-analyzer/tree/2021-06-07), then package `editors/code` up and put it in vscode-extensions. Did something change recently to break this?

**Comment by lnicola** [comment]
That sounds like an entirely different issue, but I'm not sure why it might have stopped working.

**Comment by tcmal** [comment]
Sorry, I think I misunderstood what this issue was.

**Comment by lnicola** [comment]
The manual now explains how to open the command palette:

> Try Rust Analyzer: Show RA Version in VS Code (using Command Palette feature typically activated by Ctrl+Shift+P)
