### ISSUE TITLE
unresolved-macro-call: vec! in library/proc_macro/src/bridge

### ISSUE THREAD

**Issue by lf-** [rust-lang/rust-analyzer#9446]
r-a version: 11b9233fc

`.vim/coc-settings.json`:

```json
{
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./x.py",
        "check",
        "--json-output"
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
      "./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt"
    ],
    "rust-analyzer.cargo.runBuildScripts": false,
    "rust-analyzer.procMacro.enable": false
}
```

Reproduction steps:
* Open `library/proc_macro/src/bridge/buffer.rs` in the rust repo (I happened to use 64de4979) with the recommended config.
* Get an unresolved-macro-call here:
```rust
impl<T: Copy> Default for Buffer<T> {
    fn default() -> Self {
        Self::from(vec![])
                // ^^^
    }
}
```

cc #8915

**Comment by jonas-schievink** [comment]
This happens because we use libstd and liballoc from the workspace and turn on `cfg(test)` for them. The `vec!` macro has a `#[macro_export]`ed version behind `#[cfg(not(test))]` [here](https://github.com/rust-lang/rust/blob/master/library/alloc/src/macros.rs#L37), and a private version behind `#[cfg(test)]` [here](https://github.com/rust-lang/rust/blob/master/library/alloc/src/macros.rs#L59).
