### ISSUE TITLE
GAT support

### ISSUE THREAD

**Issue by flodiebold** [rust-lang/rust-analyzer#9673]
Since generic associated types are on their way to stabilization, we'll need to start looking into implementing them :sweat_smile:

**Comment by Dessix** [comment]
#9602 was a step on the way there. I haven't run into other issues where they fail to parse since then, but I imagine more information can be modeled around them for refactoring and introspection.

**Comment by wada314** [comment]
// I'm not sure if here is the proper place to ask about this though,
One thing I'm suffered by is similar to #9602 but its rustfmt side support. rustfmt has already merged [a PL](https://github.com/rust-lang/rustfmt/issues/4802) to support GAT in associated type constraints, though rustfmt version is not bumped since February so the code is not yet in the released version.
Is there a way to specify a certain rustfmt git commit version to use in rust-analyzer?

**Comment by lnicola** [comment]
@wada314 we run the installed `rustfmt`, but you can override the command to e.g. `cargo +nightly rustfmt` or `gat-rustfmt` if that works.

**Comment by wada314** [comment]
Thanks for the info!
I was thinking the change is already merged into rustfmt, but actually I couldn't trigger that feature so I'm asking at their issue thread about how to use the feature.

**Comment by lnicola** [comment]
Even in the `nightly`, I think `rustfmt` is only updated periodically and testing on play.rust-lang.org shows that it's still mangling GATs.

But you can also build your own `rustfmt` from source, it's easier than I expected.

**Comment by wada314** [comment]
I think I'm missing some command-line config parameters to use the feature... I cloned the repository by myself and added a testcase for handling GAT in constraints, but it didn't work. I posted on [their thread](https://github.com/rust-lang/rustfmt/issues/4802) so I wait for the response, thanks!

**Comment by lnicola** [comment]
Yeah, it doesn't work for me either.
